from django.urls import path

from . import feedback, views

urlpatterns = [
    # Reusable feedback-form engine. Staff management and learner-owned routes
    # are separate so each view can enforce the narrowest role/ownership rule.
    path('feedback/csrf/', feedback.csrf_token, name='feedback-csrf'),
    path('feedback/forms/', feedback.forms_collection, name='feedback-forms'),
    path('feedback/forms/<int:pk>/', feedback.form_detail, name='feedback-form-detail'),
    path('feedback/forms/<int:pk>/status/', feedback.form_status, name='feedback-form-status'),
    path('feedback/forms/<int:pk>/duplicate/', feedback.form_duplicate, name='feedback-form-duplicate'),
    path('feedback/forms/<int:pk>/assignments/', feedback.form_assignments, name='feedback-form-assignments'),
    path('feedback/learners/', feedback.learner_options, name='feedback-learners'),
    path('feedback/responses/', feedback.responses_collection, name='feedback-responses'),
    path('feedback/responses/<int:pk>/', feedback.response_detail, name='feedback-response-detail'),
    path('feedback/analytics/', feedback.analytics, name='feedback-analytics'),
    path('feedback/my-forms/', feedback.learner_forms, name='feedback-my-forms'),
    path('feedback/my-forms/<int:pk>/', feedback.learner_form_detail, name='feedback-my-form-detail'),
    path('feedback/my-forms/<int:pk>/response/', feedback.learner_response_save, name='feedback-my-form-response'),
    path('rewards/', views.rewards_collection, name='rewards-collection'),
    path('rewards/<int:pk>/', views.reward_detail, name='reward-detail'),
    path('voucher-claims/', views.voucher_claims_collection, name='voucher-claims-collection'),
    path('voucher-claims/<int:pk>/', views.voucher_claim_detail, name='voucher-claim-detail'),
    path('recognitions/', views.recognitions_collection, name='recognitions-collection'),
    path('recognitions/<int:pk>/', views.recognition_detail, name='recognition-detail'),
    path('events/', views.events_collection, name='events-collection'),
    path('events/<int:pk>/', views.event_detail, name='event-detail'),
    path('event-bookings/', views.event_bookings_collection, name='event-bookings-collection'),
    path('event-bookings/<int:pk>/', views.event_booking_detail, name='event-booking-detail'),
    path('clubs/', views.clubs_collection, name='clubs-collection'),
    path('clubs/<int:pk>/', views.club_detail, name='club-detail'),
    path('clubs/<int:club_id>/meetings/', views.club_meetings_collection, name='club-meetings-collection'),
    path('clubs/<int:club_id>/meetings/<int:pk>/', views.club_meeting_detail, name='club-meeting-detail'),
    path('clubs/<int:club_id>/members/', views.club_members_collection, name='club-members-collection'),
    path('clubs/<int:club_id>/members/<str:learner_id>/', views.club_member_detail, name='club-member-detail'),
    path('clubs/<int:club_id>/meetings/<int:meeting_id>/attendance/', views.club_meeting_attendance_collection, name='club-meeting-attendance'),
    path('events/<int:event_id>/attendance/', views.event_attendance_collection, name='event-attendance'),
    path('reports/<str:report_id>/', views.report_data, name='report-data'),
    path('points-rules/', views.points_rules_collection, name='points-rules-collection'),
    path('points-grants/', views.points_grants_collection, name='points-grants-collection'),
    path('points/me/', views.points_me, name='points-me'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('stats/overview/', views.stats_overview, name='stats-overview'),
    path('learner-analytics/', views.learner_analytics, name='learner-analytics'),
    path('attendance-interventions/', views.attendance_interventions_collection, name='attendance-interventions-collection'),
    path('attendance-interventions/<int:pk>/', views.attendance_intervention_detail, name='attendance-intervention-detail'),
    path('points-rules/<int:pk>/', views.points_rule_detail, name='points-rule-detail'),
    path('points-rules/<int:rule_id>/grants/', views.points_rule_grants, name='points-rule-grants'),
    # Flash-card deck builder. Static paths precede <int:...> so they aren't shadowed.
    path('flash-cards/training-plan-options/', views.training_plan_options, name='flash-cards-training-plan-options'),
    path('flash-cards/ai/generate/', views.generate_flashcards_view, name='flash-cards-ai-generate'),
    path('flash-cards/decks/', views.flash_card_decks, name='flash-card-decks'),
    path('flash-cards/decks/<int:pk>/', views.flash_card_deck_detail, name='flash-card-deck-detail'),
    path('flash-cards/decks/<int:pk>/cards/', views.flash_card_deck_cards, name='flash-card-deck-cards'),
    path('flash-cards/<int:card_id>/flip/', views.flash_card_flip, name='flash-card-flip'),
]
