// @ts-nocheck -- route search types are generated by the embedded app.
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ChevronLeft, ChevronRight, Database, Plus, Search } from "lucide-react";
import { ActivityTableHeader, InlineActivityCreateRow, InlineActivityRow } from "@/features/audit/learner-log-pro-hours-test/components/InlineActivityRow";
import { Button } from "@/features/audit/learner-log-pro-hours-test/components/ui/button";
import { Table, TableBody, TableCell, TableHeader, TableRow } from "@/features/audit/learner-log-pro-hours-test/components/ui/table";
import { getActivityLearners, getAttendanceSession, getLearnerActivities } from "@/features/audit/learner-log-pro-hours-test/lib/api";

const pageSize = 20;

// Per-activity hours shown to 2 dp across the log tables.
function roundHours(value: number | null | undefined) {
  // Round to 2 dp (not whole hours — 2.5h must stay "2.5", not become "3"),
  // dropping any trailing zeros so 11.0 shows as "11".
  return value == null ? "—" : String(Math.round(value * 100) / 100);
}

export function MreTable({
  learner,
  component,
  attendanceKey,
  programme,
  completionFilter = "all",
  onCompletionFilterChange,
}: {
  learner?: string;
  component?: string;
  attendanceKey?: string;
  programme?: string;
  completionFilter?: "all" | "reading" | "quiz" | "activity";
  onCompletionFilterChange?: (value: "all" | "reading" | "quiz" | "activity") => void;
}) {
  const [search, setSearch] = useState("");
  const [page, setPage] = useState(0);
  const [addingActivity, setAddingActivity] = useState(false);
  // Three modes: a live session's attendees (attendanceKey), all learners on one
  // activity (component), or one learner's own records (default).
  const bySession = Boolean(attendanceKey);
  const byComponent = !bySession && Boolean(component);
  const singlePage = bySession || byComponent;
  const query = useQuery({
    queryKey: ["mre", learner, component, attendanceKey, programme, search, page],
    queryFn: () =>
      bySession
        ? getAttendanceSession(attendanceKey as string, programme)
        : byComponent
        ? getActivityLearners({ component: component as string, search, programme })
        : getLearnerActivities({ learner, search, offset: page * pageSize, limit: pageSize }),
  });
  // The session endpoint returns every attendee at once (no server-side search),
  // so filter client-side to keep the search box working in that mode.
  const searchedItems = bySession && search.trim()
    ? (query.data?.items ?? []).filter((activity) =>
        activity.learner.toLowerCase().includes(search.trim().toLowerCase())
      )
    : query.data?.items ?? [];
  const items = searchedItems.filter((activity) => {
    if (!byComponent || completionFilter === "all") return true;
    if (completionFilter === "reading") return activity.reading_completed === true;
    if (completionFilter === "quiz") return activity.quiz_attempted === true;
    return activity.completed === true;
  });
  const totalPages = singlePage ? 1 : Math.max(1, Math.ceil((query.data?.total ?? 0) / pageSize));
  const addLearner = learner
    ? items.find((item) => item.learner.toLowerCase() === learner.toLowerCase() || String(item.learner_id) === learner)
    : !singlePage ? items[0] : undefined;

  return (
    <section id="learner-activity-records" className="rounded-lg border border-border bg-card shadow-panel">
      <header className="flex flex-wrap items-end justify-between gap-4 border-b border-border px-7 py-5">
        <div>
          <div className="flex items-center gap-2">
            <Database className="h-4 w-4 text-success" aria-hidden />
            <h2 className="font-serif text-lg text-foreground">Learner activity records</h2>
          </div>
          <p className="mt-1 text-sm text-muted-foreground">
            {bySession
              ? "All learners who attended this live session, matched by session date + group."
              : byComponent
              ? "All learners who have this activity, with their own log entry on it."
              : learner
              ? `Live Neon activity records for ${learner}.`
              : "Student columns from Neon are converted into one real activity row per learner."}
          </p>
          {byComponent && completionFilter !== "all" ? (
            <div className="mt-2 flex items-center gap-2 text-xs">
              <span className="rounded-full bg-success/10 px-2.5 py-1 font-semibold text-success">
                Showing {completionFilter === "reading" ? "reading completed" : completionFilter === "quiz" ? "quiz attempted" : "activity completed"}
              </span>
              <button type="button" onClick={() => onCompletionFilterChange?.("all")} className="font-medium text-primary hover:underline">Show all learners</button>
            </div>
          ) : null}
        </div>
        <div className="flex w-full max-w-lg items-center gap-2">
          <label className="relative block min-w-0 flex-1">
            <Search className="pointer-events-none absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" />
            <input value={search} onChange={(event) => { setSearch(event.target.value); setPage(0); }} placeholder="Search learner, plan or activity…" className="h-9 w-full rounded-md border border-border bg-background pl-9 pr-3 text-sm outline-none focus:border-primary" />
          </label>
          {addLearner ? <Button size="sm" disabled={addingActivity} onClick={() => setAddingActivity(true)}><Plus className="h-3.5 w-3.5" /> Add</Button> : null}
        </div>
      </header>

      {query.isError ? (
        <div className="px-7 py-10 text-center text-sm text-destructive">
          {query.error instanceof Error ? query.error.message : "The database API is unavailable."}
        </div>
      ) : (
        <div className="overflow-x-auto">
          <Table>
            <TableHeader><ActivityTableHeader /></TableHeader>
            <TableBody>
              {addingActivity && addLearner ? <InlineActivityCreateRow learnerId={Number(addLearner.learner_id)} learnerName={addLearner.learner} onCancel={() => setAddingActivity(false)} /> : null}
              {query.isLoading && (
                <TableRow><TableCell colSpan={10} className="py-10 text-center text-sm text-muted-foreground">Loading learner data from Neon…</TableCell></TableRow>
              )}
              {items.map((activity) => (
                <InlineActivityRow key={activity.id} row={activity} />
              ))}
              {!query.isLoading && items.length === 0 && (
                <TableRow><TableCell colSpan={10} className="py-10 text-center text-sm text-muted-foreground">No learner activity records were returned by this database branch.</TableCell></TableRow>
              )}
            </TableBody>
          </Table>
        </div>
      )}

      <footer className="flex items-center justify-between border-t border-border px-7 py-4 text-xs text-muted-foreground">
        <span>{query.data ? `${singlePage ? items.length : query.data.total} records` : "Connecting…"}</span>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="icon" disabled={page === 0} onClick={() => setPage((value) => value - 1)} aria-label="Previous page">
            <ChevronLeft className="h-4 w-4" />
          </Button>
          <span className="font-mono">{page + 1} / {totalPages}</span>
          <Button variant="outline" size="icon" disabled={page + 1 >= totalPages} onClick={() => setPage((value) => value + 1)} aria-label="Next page">
            <ChevronRight className="h-4 w-4" />
          </Button>
        </div>
      </footer>
    </section>
  );
}
