-- Coach calendar consistency and idempotency schema changes.
-- This script is intentionally idempotent and can be run directly on PostgreSQL.

BEGIN;

ALTER TABLE "Coach".coach_calendar_event
    ADD COLUMN IF NOT EXISTS operation_id uuid,
    ADD COLUMN IF NOT EXISTS idempotency_key varchar(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS sync_state varchar(24),
    ADD COLUMN IF NOT EXISTS sync_attempt_count integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_sync_attempt_at timestamp with time zone;

UPDATE "Coach".coach_calendar_event
SET operation_id = gen_random_uuid()
WHERE operation_id IS NULL;

UPDATE "Coach".coach_calendar_event
SET sync_state = CASE
    WHEN status = 'cancelled' THEN 'cancelled'
    WHEN COALESCE(graph_event_id, '') <> '' THEN 'synced'
    WHEN COALESCE(last_graph_sync_error, '') <> '' THEN 'failed'
    ELSE 'failed'
END
WHERE sync_state IS NULL;

ALTER TABLE "Coach".coach_calendar_event
    ALTER COLUMN operation_id SET DEFAULT gen_random_uuid(),
    ALTER COLUMN operation_id SET NOT NULL,
    ALTER COLUMN sync_state SET DEFAULT 'pending',
    ALTER COLUMN sync_state SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS coach_calendar_operation_id_uniq
    ON "Coach".coach_calendar_event (operation_id);

CREATE UNIQUE INDEX IF NOT EXISTS coach_calendar_owner_idempotency_uniq
    ON "Coach".coach_calendar_event (owner_email, idempotency_key)
    WHERE idempotency_key <> '';

CREATE UNIQUE INDEX IF NOT EXISTS coach_calendar_booking_seq_uniq
    ON "Coach".coach_calendar_event (learner_id, event_type, sequence)
    WHERE event_type IN (
        'catch-up',
        'student-support',
        'eligibility-review',
        'workspace',
        'training-plan'
    );

CREATE INDEX IF NOT EXISTS coach_calendar_sync_state_idx
    ON "Coach".coach_calendar_event (sync_state);

CREATE TABLE IF NOT EXISTS "Coach".coach_calendar_sequence (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    learner_id integer NOT NULL,
    event_type varchar(32) NOT NULL,
    last_sequence integer NOT NULL DEFAULT 0,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT coach_calendar_sequence_scope_uniq
        UNIQUE (learner_id, event_type),
    CONSTRAINT coach_calendar_sequence_nonnegative
        CHECK (last_sequence >= 0)
);

INSERT INTO "Coach".coach_calendar_sequence (
    learner_id,
    event_type,
    last_sequence,
    updated_at
)
SELECT
    learner_id,
    event_type,
    MAX(sequence),
    CURRENT_TIMESTAMP
FROM "Coach".coach_calendar_event
WHERE event_type IN (
    'catch-up',
    'student-support',
    'eligibility-review',
    'workspace',
    'training-plan'
)
GROUP BY learner_id, event_type
ON CONFLICT (learner_id, event_type)
DO UPDATE SET
    last_sequence = GREATEST(
        "Coach".coach_calendar_sequence.last_sequence,
        EXCLUDED.last_sequence
    ),
    updated_at = CURRENT_TIMESTAMP;

COMMIT;
