import { afterEach, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import type { ReactNode } from 'react';
import Page from './page';
import { deleteCoach, emptyLinks, listCoaches, saveCoach } from '@/api/coachBookingDirectory';
vi.mock('../_shared/AdminPage', () => ({ AdminPage: ({ children, actions }: { children: ReactNode; actions: ReactNode }) => <>{actions}{children}</> }));
vi.mock('@/api/coachBookingDirectory', async original => ({ ...await original<typeof import('@/api/coachBookingDirectory')>(), listCoaches: vi.fn(), saveCoach: vi.fn(), deleteCoach: vi.fn() }));
afterEach(() => { cleanup(); vi.clearAllMocks(); vi.restoreAllMocks(); });
it('creates a coach with four booking links and shows its public page', async () => {
  const coach = { id: 1, version: 1, name: 'Example Coach', slug: 'example-coach', links: { ...emptyLinks(), first_session: 'https://example.org/book' } };
  vi.mocked(listCoaches).mockResolvedValueOnce({ coaches: [] }).mockResolvedValue({ coaches: [coach] });
  vi.mocked(saveCoach).mockResolvedValue(coach);
  render(<MemoryRouter><Page /></MemoryRouter>);
  await screen.findByText('No coaches found.');
  fireEvent.click(screen.getByRole('button', { name: 'Add coach' }));
  fireEvent.change(screen.getByLabelText('Coach name'), { target: { value: coach.name } });
  fireEvent.change(screen.getByLabelText('First session URL'), { target: { value: coach.links.first_session } });
  fireEvent.submit(screen.getByRole('form', { name: 'Coach editor' }));
  await waitFor(() => expect(saveCoach).toHaveBeenCalledWith({ name: coach.name, links: coach.links }));
  expect(await screen.findByRole('link', { name: 'Open booking page' })).toHaveAttribute('href', '/coach-booking/example-coach');
});
it('retains editor values if saving fails', async () => {
  vi.mocked(listCoaches).mockResolvedValue({ coaches: [] });
  vi.mocked(saveCoach).mockRejectedValue(new Error('Coach changed. Reload and retry.'));
  render(<MemoryRouter><Page /></MemoryRouter>);
  await screen.findByText('No coaches found.');
  fireEvent.click(screen.getByRole('button', { name: 'Add coach' }));
  fireEvent.change(screen.getByLabelText('Coach name'), { target: { value: 'Keep edits' } });
  fireEvent.submit(screen.getByRole('form', { name: 'Coach editor' }));
  expect(await screen.findByRole('alert')).toHaveTextContent('Coach changed');
  expect(screen.getByDisplayValue('Keep edits')).toBeInTheDocument();
});
it('explains removal and sends no delete until the administrator confirms', async () => {
  const coach = { id: 8, version: 3, name: 'Example Coach', slug: 'example-coach', links: emptyLinks() };
  vi.mocked(listCoaches).mockResolvedValue({ coaches: [coach] });
  vi.mocked(deleteCoach).mockResolvedValue({ deleted: true });
  const confirm = vi.spyOn(window, 'confirm').mockReturnValue(false);
  render(<MemoryRouter><Page /></MemoryRouter>);
  fireEvent.click(await screen.findByRole('button', { name: 'Remove' }));
  expect(confirm).toHaveBeenCalledWith(expect.stringContaining('This does not delete their LMS account or cancel existing bookings.'));
  expect(deleteCoach).not.toHaveBeenCalled();
  expect(screen.getByText('Example Coach')).toBeInTheDocument();
  confirm.mockReturnValue(true);
  vi.mocked(listCoaches).mockResolvedValue({ coaches: [] });
  fireEvent.click(screen.getByRole('button', { name: 'Remove' }));
  await waitFor(() => expect(deleteCoach).toHaveBeenCalledWith(coach));
  await screen.findByText('No coaches found.');
});
