// @ts-nocheck -- route search types are generated by the embedded app.
import { useEffect, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { createFileRoute, Link, useRouter } from "@tanstack/react-router";
import Swal from "sweetalert2";
import { MreTable } from "@/features/audit/learner-log-pro-copy/components/MreTable";
import { QuizBody } from "@/features/audit/learner-log-pro-copy/components/QuizAttemptBody";
import { toGoogleEmbedUrl } from "@/features/audit/learner-log-pro-copy/lib/googleEmbed";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/features/audit/learner-log-pro-copy/components/ui/table";
import {
  getActivityDetail,
  getLearnerActivities,
} from "@/features/audit/learner-log-pro-copy/lib/api";

export const Route = createFileRoute("/activity")({
  // Numeric-looking values in hand-typed URLs arrive as numbers — accept both.
  validateSearch: (search: Record<string, unknown>) => ({
    learner: typeof search.learner === "string" ? search.learner : typeof search.learner === "number" ? String(search.learner) : "",
    activity: typeof search.activity === "string" ? search.activity : typeof search.activity === "number" ? String(search.activity) : "",
  }),
  component: ActivityLogPage,
});

const toast = Swal.mixin({
  toast: true,
  position: "top-end",
  showConfirmButton: false,
  timer: 2800,
  timerProgressBar: true,
});

// Colour the KSB code badge by its type: Knowledge / Skill / Behaviour.
function ksbBadgeClass(type: string) {
  switch ((type || "").toUpperCase()) {
    case "K": return "bg-primary/15 text-primary";
    case "S": return "bg-success/15 text-success";
    case "B": return "bg-amber-500/15 text-amber-600";
    default: return "bg-muted text-muted-foreground";
  }
}

// Colour a bundle item badge by its material: quiz / pdf / reading.
function materialBadgeClass(material: string) {
  switch ((material || "").toLowerCase()) {
    case "quiz": return "bg-primary/15 text-primary";
    case "pdf": return "bg-amber-500/15 text-amber-600";
    case "text":
    case "reading": return "bg-success/15 text-success";
    default: return "bg-muted text-muted-foreground";
  }
}

// QuizBody moved to components/QuizAttemptBody.tsx — shared with the ledger.

// One bundle sub-activity row. The title still drills into the item's own
// detail; a quiz additionally gets a "View quiz" toggle that reveals the
// focused learner's graded body + score inline.
function BundleItem({ item, aptemId, learnerName, onNavigate }: {
  item: any;
  aptemId?: number;
  learnerName: string;
  onNavigate: () => void;
}) {
  const materialType = typeof item.material_type === "string" ? item.material_type : "activity";
  const itemLabel = typeof item.activity === "string"
    ? item.activity
    : typeof item.front_end_name === "string"
      ? item.front_end_name
      : typeof item.title === "string" ? item.title : "Untitled activity";
  const isQuiz = materialType.toLowerCase() === "quiz";
  const [open, setOpen] = useState(false);
  return (
    <li className="px-7 py-3">
      <div className="flex items-center justify-between gap-3">
        <button type="button" onClick={onNavigate} className="flex min-w-0 items-center gap-2 text-left">
          <span className={`shrink-0 rounded-sm px-1.5 py-0.5 text-[10px] font-semibold uppercase ${materialBadgeClass(materialType)}`}>{materialType}</span>
          <span className="truncate text-sm font-medium text-foreground hover:text-primary hover:underline">{itemLabel}</span>
        </button>
        <div className="flex shrink-0 items-center gap-3">
          {isQuiz && (
            <button type="button" onClick={() => setOpen((value) => !value)} className="text-xs font-medium text-primary hover:underline">
              {open ? "Hide learner response" : "View learner response"}
            </button>
          )}
          {item.iframe_url && (
            <a href={item.iframe_url} target="_blank" rel="noreferrer" className="text-xs font-medium text-primary hover:underline">Open ↗</a>
          )}
        </div>
      </div>
      {isQuiz && open && (
        <div className="mt-2 overflow-hidden rounded-md border border-border bg-card">
          <QuizBody aptemId={aptemId} learnerName={learnerName} component={item.component_id} />
        </div>
      )}
    </li>
  );
}

function roundHours(value: number | null | undefined) {
  return value == null ? "—" : String(Math.round(value * 100) / 100);
}

// A number|null field pre-fill: "" when absent so the input starts empty.
function asInput(value: number | null | undefined) {
  return value == null ? "" : String(value);
}

function localDateTimeOnActivityDate(value: string | null | undefined, activityDate: string | null | undefined) {
  if (!value) return "";
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) return "";
  const local = new Date(parsed.getTime() - parsed.getTimezoneOffset() * 60_000).toISOString().slice(0, 16);
  return activityDate ? `${activityDate}${local.slice(10)}` : local;
}

// One editable participant row (+ an expandable editor beneath it).
function ParticipantRow({
  participant,
  category,
  componentId,
  isPrimary,
  onFocus,
  onSaved,
}: {
  participant: any;
  category: string;
  componentId: string | number;
  isPrimary: boolean;
  onFocus: (participant: any) => void;
  onSaved: (learnerId: number, patch: any) => Promise<void>;
}) {
  const isAttendance = category === "attendance";
  const [open, setOpen] = useState(false);
  const [planned, setPlanned] = useState(asInput(participant.planned));
  const [actual, setActual] = useState(asInput(participant.actual));
  const [attended, setAttended] = useState(Boolean(participant.completed));
  const isUserInput = String(participant.timestamp_display || "").trim().toLowerCase() === "input";
  const initialStartedAt = isUserInput ? "" : localDateTimeOnActivityDate(participant.timestamp_from, participant.date);
  const initialCompletedAt = isUserInput ? "" : localDateTimeOnActivityDate(participant.timestamp_to, participant.date);
  const [startedAt, setStartedAt] = useState(initialStartedAt);
  const [completedAt, setCompletedAt] = useState(initialCompletedAt);
  const [journal, setJournal] = useState("");
  const [saving, setSaving] = useState(false);

  // Re-seed if the underlying data changes after a refetch.
  useEffect(() => {
    setPlanned(asInput(participant.planned));
    setActual(asInput(participant.actual));
    setAttended(Boolean(participant.completed));
    setStartedAt(initialStartedAt);
    setCompletedAt(initialCompletedAt);
  }, [participant.planned, participant.actual, participant.completed, initialStartedAt, initialCompletedAt]);

  function buildPatch() {
    const patch: any = {};
    if (planned !== asInput(participant.planned) && planned !== "") patch.planned_hours = Number(planned);
    if (isAttendance) {
      if (attended !== Boolean(participant.completed)) patch.attended = attended;
    } else if (actual !== asInput(participant.actual) && actual !== "") {
      patch.actual_hours = Number(actual);
    }
    if (!isUserInput && startedAt && startedAt !== initialStartedAt) patch.started_at = new Date(startedAt).toISOString();
    if (!isUserInput && completedAt && completedAt !== initialCompletedAt) patch.completed_at = new Date(completedAt).toISOString();
    if (journal.trim()) patch.journal = journal.trim();
    return patch;
  }

  async function save() {
    const patch = buildPatch();
    if (Object.keys(patch).length === 0) {
      toast.fire({ icon: "info", title: "Nothing changed to save." });
      return;
    }
    setSaving(true);
    try {
      await onSaved(participant.learner_id, patch);
      toast.fire({ icon: "success", title: `Saved ${participant.learner_name}.` });
      setStartedAt("");
      setCompletedAt("");
      setJournal("");
      setOpen(false);
    } catch (error) {
      toast.fire({ icon: "error", title: error instanceof Error ? error.message : "Save failed." });
    } finally {
      setSaving(false);
    }
  }

  // In read mode the whole row is clickable to re-focus the activity on this
  // learner; while editing it isn't, so the inputs work normally.
  const rowClickable = !open;
  return (
    <>
      <TableRow
        role={rowClickable ? "button" : undefined}
        tabIndex={rowClickable ? 0 : undefined}
        title={rowClickable ? "Focus this activity on this learner" : undefined}
        onClick={rowClickable ? () => onFocus(participant) : undefined}
        onKeyDown={
          rowClickable
            ? (event) => {
                if (event.key === "Enter" || event.key === " ") { event.preventDefault(); onFocus(participant); }
              }
            : undefined
        }
        className={
          open
            ? "bg-[#eaf1f8]"
            : `cursor-pointer hover:bg-[#eaf1f8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-primary ${isPrimary ? "bg-primary/5" : ""}`
        }
      >
        <TableCell className="pl-7 text-sm font-medium text-foreground">
          {participant.learner_name}
          {isPrimary && <span className="ml-2 rounded-sm bg-primary/15 px-1.5 py-0.5 text-[10px] font-semibold uppercase text-primary">focused</span>}
        </TableCell>
        <TableCell className="font-mono text-xs text-muted-foreground">{participant.learner_id}</TableCell>
        <TableCell className="whitespace-nowrap font-mono text-xs text-muted-foreground">{participant.date ?? "—"}</TableCell>
        <TableCell className="whitespace-nowrap text-center font-mono text-xs text-muted-foreground">{participant.timestamp_display || "—"}</TableCell>
        <TableCell className="text-xs text-muted-foreground">{category}</TableCell>
        <TableCell className="max-w-md text-sm text-foreground">
          {participant.activity}
          {participant.item_title && <span className="mt-0.5 block text-xs text-muted-foreground">{participant.item_title}</span>}
        </TableCell>
        <TableCell className="text-right font-mono text-sm">
          {open ? (
            <input type="number" step="0.25" min="0" value={planned} onChange={(e) => setPlanned(e.target.value)} className="h-8 w-20 rounded-md border border-border bg-card px-2 text-right text-sm outline-none focus:border-primary" />
          ) : roundHours(participant.planned)}
        </TableCell>
        <TableCell className="text-right font-mono text-sm text-success">
          {open ? (
            isAttendance ? (
              <label className="flex items-center justify-end gap-1.5 text-xs text-foreground">
                <input type="checkbox" checked={attended} onChange={(e) => setAttended(e.target.checked)} /> attended
              </label>
            ) : (
              <input type="number" step="0.25" min="0" value={actual} onChange={(e) => setActual(e.target.value)} className="h-8 w-20 rounded-md border border-border bg-card px-2 text-right text-sm outline-none focus:border-primary" />
            )
          ) : roundHours(participant.actual)}
        </TableCell>
        <TableCell className="pr-7 text-right">
          <button
            type="button"
            onClick={(event) => { event.stopPropagation(); setOpen((value) => !value); }}
            className="rounded-md border border-border bg-card px-2.5 py-1 text-xs font-semibold text-foreground hover:bg-secondary"
          >
            {open ? "Cancel" : "Edit"}
          </button>
        </TableCell>
      </TableRow>
      {open && (
        <TableRow className="bg-[#f7f9fc] hover:bg-[#f7f9fc]">
          <TableCell colSpan={9} className="px-7 py-4">
            <div className="grid gap-4 lg:grid-cols-[repeat(2,minmax(0,1fr))_2fr]">
              {isUserInput ? (
                <div className="lg:col-span-2">
                  <span className="label-caps">Timestamp</span>
                  <p className="mt-1.5 h-9 rounded-md border border-border bg-muted px-2.5 py-2 font-mono text-sm text-muted-foreground">input</p>
                </div>
              ) : (
                <>
                  <label className="block">
                    <span className="label-caps">Started at</span>
                    <input type="datetime-local" value={startedAt} onChange={(e) => setStartedAt(e.target.value)} className="mt-1.5 h-9 w-full rounded-md border border-border bg-card px-2.5 text-sm outline-none focus:border-primary" />
                  </label>
                  <label className="block">
                    <span className="label-caps">Completed at</span>
                    <input type="datetime-local" value={completedAt} onChange={(e) => setCompletedAt(e.target.value)} className="mt-1.5 h-9 w-full rounded-md border border-border bg-card px-2.5 text-sm outline-none focus:border-primary" />
                  </label>
                </>
              )}
              <label className="block">
                <span className="label-caps">Journal entry</span>
                <textarea value={journal} onChange={(e) => setJournal(e.target.value)} rows={2} placeholder="Off-the-job reflection for this learner…" className="mt-1.5 w-full rounded-md border border-border bg-card px-2.5 py-2 text-sm outline-none focus:border-primary" />
              </label>
            </div>
            <div className="mt-3 flex items-center gap-3">
              <button type="button" onClick={save} disabled={saving} className="rounded-md bg-primary px-3.5 py-1.5 text-sm font-medium text-primary-foreground hover:opacity-90 disabled:opacity-60">
                {saving ? "Saving…" : "Save row"}
              </button>
              <span className="text-xs text-muted-foreground">
                {isUserInput
                  ? `Edits ${participant.learner_name}'s record only. This is a user-input record, so no system timestamp is required.`
                  : `Edits ${participant.learner_name}'s record only. Timestamp dates default to the activity date.`}
              </span>
            </div>
          </TableCell>
        </TableRow>
      )}
    </>
  );
}

function ActivityLogPage() {
  const router = useRouter();
  const { learner, activity: componentId } = Route.useSearch();
  const [completionFilter, setCompletionFilter] = useState<"all" | "reading" | "quiz" | "activity">("all");

  // The activity + its sub-activities + participants come from the /activity endpoint.
  const detail = useQuery({
    queryKey: ["activity-detail", learner, componentId],
    queryFn: () => getActivityDetail(componentId, learner),
    enabled: Boolean(componentId),
  });
  const data = detail.data;
  useEffect(() => setCompletionFilter("all"), [componentId]);

  // The snapshot's Mapped KSBs + content iframe come from the /activities row payload.
  const row = useQuery({
    queryKey: ["activity-row", learner, componentId],
    queryFn: () => getLearnerActivities({ learner: learner || undefined, search: componentId || "", limit: 1, offset: 0 }),
    enabled: Boolean(componentId),
  });
  const activityRow = row.data?.items[0];

  // The focused learner: the one from the route if present, else the first
  // participant. Quiz results and the snapshot render for this learner.
  const primary =
    data?.participants.find((p) => p.learner_name.toLowerCase() === (learner || "").toLowerCase()) ??
    data?.participants[0];

  const category = data?.category ?? activityRow?.activity_category ?? "";
  // Quiz results use Aptem identity; the name is display text only.
  const focusedLearnerName = primary?.learner_name || learner || "";
  const showCompletedLearners = (filter: "reading" | "quiz" | "activity") => {
    setCompletionFilter(filter);
    window.requestAnimationFrame(() => {
      document.getElementById("learner-activity-records")?.scrollIntoView({ behavior: "smooth", block: "start" });
    });
  };

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border bg-surface">
        <div className="mx-auto flex max-w-[1700px] flex-wrap items-center justify-between gap-4 px-6 py-4">
          <div className="flex items-baseline gap-3">
            <span className="font-serif text-base text-foreground">OTJ&nbsp;Ledger</span>
            <span className="label-caps">Activity detail</span>
          </div>
          <div className="flex items-center gap-4 text-xs text-muted-foreground">
            {activityRow?.month_unit && <span className="font-mono">{activityRow.month_unit}</span>}
            <button type="button" onClick={() => router.history.back()} className="font-medium text-foreground hover:underline">← Back</button>
            <Link to="/search" className="font-medium text-foreground hover:underline">Search</Link>
            <Link
              to="/journal"
              search={{ learner: learner || primary?.learner_name?.toLowerCase() || "", period: activityRow?.activity_period || "" }}
              className="font-medium text-foreground hover:underline"
            >
              Monthly journal →
            </Link>
            <span className="rounded-sm border border-success/40 bg-success/10 px-2 py-1 font-semibold text-success">Live data</span>
          </div>
        </div>
      </header>

      <main className="mx-auto w-full max-w-[1700px] space-y-6 px-6 py-8">
        {detail.isLoading && (
          <div className="rounded-lg border border-border bg-card px-7 py-16 text-center text-sm text-muted-foreground">Loading activity…</div>
        )}
        {detail.isError && (
          <div className="rounded-lg border border-border bg-card px-7 py-16 text-center text-sm text-destructive">
            {detail.error instanceof Error ? detail.error.message : "Could not load this activity."}
          </div>
        )}

        {data && (
          <div className="grid gap-6 lg:grid-cols-3">
            <article className="space-y-6 lg:col-span-2">
              {/* Bundle sub-activities. */}
              {data.items.length > 0 && (
                <section className="rounded-lg border border-border bg-card shadow-panel">
                  <header className="border-b border-border px-7 py-5">
                    <h2 className="font-serif text-lg text-foreground">Activities inside this bundle</h2>
                    <p className="mt-1 text-sm text-muted-foreground">{data.item_count} item{data.item_count === 1 ? "" : "s"}. Click one to drill into its own participants.</p>
                  </header>
                  <ul className="divide-y divide-border">
                    {data.items.map((item) => (
                      <BundleItem
                        key={item.component_id}
                        item={item}
                        aptemId={primary?.learner_id}
                        learnerName={focusedLearnerName}
                        onNavigate={() => router.navigate({ to: "/activity", search: { learner, activity: String(item.component_id) } })}
                      />
                    ))}
                  </ul>
                </section>
              )}

              {/* A drilled-into quiz leaf (no sub-items): show the focused
                  learner's graded body + score directly. */}
              {data.items.length === 0 && data.has_quiz === true && (
                <section className="rounded-lg border border-border bg-card shadow-panel">
                  <header className="border-b border-border px-7 py-5">
                    <h2 className="font-serif text-lg text-foreground">Quiz result</h2>
                    <p className="mt-1 text-sm text-muted-foreground">
                      {primary?.learner_name ? `${primary.learner_name}'s graded attempt.` : "Graded attempt for the focused learner."}
                    </p>
                  </header>
                  <QuizBody aptemId={primary?.learner_id} learnerName={focusedLearnerName} component={data.component_id} />
                </section>
              )}

              {/* Activity content preview (video / audio / reading). */}
              {activityRow?.source_url && (
                <section className="rounded-lg border border-border bg-card shadow-panel">
                  <header className="flex items-center justify-between border-b border-border px-7 py-5">
                    <h2 className="font-serif text-lg text-foreground">Activity content</h2>
                    <a href={activityRow.source_url} target="_blank" rel="noreferrer" className="text-xs font-medium text-primary hover:underline">Open in new tab ↗</a>
                  </header>
                  <div className="p-5">
                    <div className="aspect-video w-full overflow-hidden rounded-md border border-border bg-black/5">
                      <iframe src={toGoogleEmbedUrl(activityRow.source_url)} title={data.activity} className="h-full w-full" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen />
                    </div>
                  </div>
                </section>
              )}

              {/* The same inline CRUD row used by search and journal. */}
              <MreTable
                component={String(data.component_id)}
                learner={primary?.learner_name}
                programme={data.programme}
                completionFilter={completionFilter}
                onCompletionFilterChange={setCompletionFilter}
              />
            </article>

            {/* Snapshot + activity-level editing. */}
            <aside className="activity-snapshot overflow-hidden rounded-lg border border-border bg-card shadow-panel">
              <header className="bg-primary px-6 py-5 text-primary-foreground">
                <p className="snapshot-label label-caps">Activity snapshot</p>
                <h2 className="mt-1 font-serif text-xl font-bold text-primary-foreground">{data.activity}</h2>
              </header>
              <dl className="grid gap-5 px-6 py-6">
                <div>
                  <dt className="label-caps">Category</dt>
                  <dd className="mt-1 text-sm capitalize text-foreground">{category || "—"}</dd>
                </div>
                <div>
                  <dt className="label-caps">Component ID</dt>
                  <dd className="mt-1 font-mono text-sm text-foreground">{data.component_id}</dd>
                </div>
                {activityRow?.week && (
                  <div>
                    <dt className="label-caps">Lecture / week</dt>
                    <dd className="mt-1 text-sm text-foreground">{activityRow.week}</dd>
                  </div>
                )}
              </dl>

              <section className="border-t border-border px-6 py-6">
                <h3 className="label-caps">Completion on Aptem</h3>
                <div className="mt-3 space-y-3">
                  {data.has_reading ? (
                    <div className="rounded-md border border-border bg-background/40 p-3">
                      <div className="flex items-center justify-between gap-3">
                        <div>
                          <p className="text-xs font-semibold text-foreground">Reading viewed</p>
                          <p className="mt-0.5 font-mono text-sm text-success">{data.reading_completed_count ?? 0} / {data.participant_count}</p>
                        </div>
                        <button type="button" onClick={() => showCompletedLearners("reading")} className="rounded-md border border-border bg-card px-2.5 py-1.5 text-xs font-semibold text-primary hover:bg-secondary">See learners completed</button>
                      </div>
                    </div>
                  ) : null}
                  {data.has_quiz ? (
                    <div className="rounded-md border border-border bg-background/40 p-3">
                      <div className="flex items-center justify-between gap-3">
                        <div>
                          <p className="text-xs font-semibold text-foreground">Quiz attempted</p>
                          <p className="mt-0.5 font-mono text-sm text-primary">{data.quiz_attempted_count ?? 0} / {data.participant_count}</p>
                          <p className="mt-0.5 text-[10px] text-muted-foreground">{data.quiz_completed_count ?? 0} passed</p>
                        </div>
                        <button type="button" onClick={() => showCompletedLearners("quiz")} className="rounded-md border border-border bg-card px-2.5 py-1.5 text-xs font-semibold text-primary hover:bg-secondary">See learners completed</button>
                      </div>
                    </div>
                  ) : null}
                  <div className="rounded-md border border-success/30 bg-success/5 p-3">
                    <div className="flex items-center justify-between gap-3">
                      <div>
                        <p className="text-xs font-semibold text-foreground">Activity complete</p>
                        <p className="mt-0.5 font-mono text-sm text-success">{data.completed_count} / {data.participant_count}</p>
                      </div>
                      <button type="button" onClick={() => showCompletedLearners("activity")} className="rounded-md bg-primary px-2.5 py-1.5 text-xs font-semibold text-primary-foreground hover:opacity-90">See learners completed</button>
                    </div>
                  </div>
                </div>
              </section>

              {/* Mapped KSBs from the /activities row payload. */}
              <section className="border-t border-border px-6 py-6">
                <h3 className="label-caps">Mapped KSBs</h3>
                {activityRow?.ksbs && activityRow.ksbs.length > 0 ? (
                  <ul className="mt-3 space-y-2">
                    {activityRow.ksbs.map((ksb, index) => (
                      <li key={`${ksb.code}-${index}`}>
                        <details className="rounded-md border border-border bg-background/40 px-3 py-2">
                          <summary className="flex cursor-pointer list-none items-center gap-2 [&::-webkit-details-marker]:hidden">
                            <span className={`rounded-sm px-1.5 py-0.5 text-xs font-semibold ${ksbBadgeClass(ksb.type)}`}>{ksb.code}</span>
                            <span className="ml-auto text-xs text-muted-foreground">▸</span>
                          </summary>
                          <div className="mt-2">
                            <span className="text-xs font-medium text-muted-foreground">{ksb.type_label}</span>
                            {ksb.description && <p className="mt-1 text-sm leading-6 text-foreground">{ksb.description}</p>}
                            {ksb.reason && <p className="mt-1 text-xs italic leading-5 text-muted-foreground">Why: {ksb.reason}</p>}
                          </div>
                        </details>
                      </li>
                    ))}
                  </ul>
                ) : (
                  <p className="mt-2 text-sm text-muted-foreground">No KSBs mapped in the programme structure.</p>
                )}
              </section>

            </aside>
          </div>
        )}

        <p className="pb-4 text-xs text-muted-foreground">
          Activity and participant data are served live from this platform's Last_audit mirror.
        </p>
      </main>
    </div>
  );
}
