// @ts-nocheck -- route search types are generated by the embedded app.
import { useEffect, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { createFileRoute, Link, useRouter } from "@tanstack/react-router";
import Swal from "sweetalert2";
import { MreTable } from "@/features/audit/learner-log-pro-copy/components/MreTable";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/features/audit/learner-log-pro-copy/components/ui/table";
import {
  editActivity,
  getActivityDetail,
  getLearnerActivities,
  getQuizAttempt,
  invalidateOtjhCaches,
} from "@/features/audit/learner-log-pro-copy/lib/api";

export const Route = createFileRoute("/activity")({
  validateSearch: (search: Record<string, unknown>) => ({
    learner: typeof search.learner === "string" ? search.learner : "",
    activity: typeof search.activity === "string" ? search.activity : "",
  }),
  component: ActivityLogPage,
});

const toast = Swal.mixin({
  toast: true,
  position: "top-end",
  showConfirmButton: false,
  timer: 2800,
  timerProgressBar: true,
});

// Colour the KSB code badge by its type: Knowledge / Skill / Behaviour.
function ksbBadgeClass(type: string) {
  switch ((type || "").toUpperCase()) {
    case "K": return "bg-primary/15 text-primary";
    case "S": return "bg-success/15 text-success";
    case "B": return "bg-amber-500/15 text-amber-600";
    default: return "bg-muted text-muted-foreground";
  }
}

// Colour a bundle item badge by its material: quiz / pdf / reading.
function materialBadgeClass(material: string) {
  switch ((material || "").toLowerCase()) {
    case "quiz": return "bg-primary/15 text-primary";
    case "pdf": return "bg-amber-500/15 text-amber-600";
    case "text":
    case "reading": return "bg-success/15 text-success";
    default: return "bg-muted text-muted-foreground";
  }
}

// Colour a quiz status chip by pass/fail status.
function scoreClass(status: string | null) {
  const value = (status || "").toLowerCase();
  if (value === "passed") return "bg-success/15 text-success";
  if (value === "failed") return "bg-destructive/15 text-destructive";
  return "bg-muted text-muted-foreground";
}

// One learner's graded quiz attempt: a score header + every question with the
// learner's answer marked right/wrong. Fetched lazily (only once opened) from
// the Django match-ledger, since the live evidence feed carries no quiz bodies.
function QuizBody({ learner, component }: { learner: string; component: string | number }) {
  const query = useQuery({
    queryKey: ["quiz-attempt", learner, String(component)],
    queryFn: () => getQuizAttempt({ learner, component: String(component) }),
    enabled: Boolean(learner && component),
  });
  if (query.isLoading) return <p className="px-4 py-3 text-xs text-muted-foreground">Loading quiz…</p>;
  if (query.isError) return <p className="px-4 py-3 text-xs text-destructive">Could not load the quiz body.</p>;
  const attempt = query.data?.attempt;
  if (!attempt) return <p className="px-4 py-3 text-xs text-muted-foreground">No graded attempt stored for {learner || "this learner"}.</p>;
  const questions = attempt.quiz_body?.questions ?? [];
  const total = questions.length;
  const correct = questions.filter((q) => q.is_correct).length;
  const percent = total ? Math.round((correct / total) * 100) : null;
  return (
    <div className="space-y-3 px-4 py-3">
      {/* Score header — the pass/fail status and the derived percentage. */}
      <div className="flex flex-wrap items-center gap-2">
        {attempt.status && (
          <span className={`rounded-sm px-1.5 py-0.5 text-[10px] font-semibold uppercase ${scoreClass(attempt.status)}`}>{attempt.status}</span>
        )}
        {percent != null && (
          <span className="rounded-sm bg-primary/15 px-1.5 py-0.5 text-[10px] font-semibold text-primary">{percent}%</span>
        )}
        <span className="text-xs text-muted-foreground">{correct}/{total} correct</span>
      </div>
      {questions.map((question, qi) => (
        <div key={question.question_id ?? qi} className="rounded-md border border-border bg-background/40 p-3">
          <p className="text-sm leading-6 text-foreground">
            <span className="mr-1.5 font-semibold text-muted-foreground">Q{question.question_order ?? qi + 1}.</span>
            {question.question_text}
            <span className={`ml-2 text-xs font-semibold ${question.is_correct ? "text-success" : "text-destructive"}`}>
              {question.is_correct ? "✓ correct" : "✗ incorrect"}
            </span>
          </p>
          <ul className="mt-2 space-y-1">
            {(question.answer_options ?? []).map((option, oi) => (
              <li
                key={oi}
                className={`flex items-start gap-2 rounded-sm px-2 py-1 text-sm ${
                  option.is_correct
                    ? "bg-success/10 text-foreground"
                    : option.is_selected
                    ? "bg-destructive/10 text-foreground"
                    : "text-muted-foreground"
                }`}
              >
                <span className="mt-0.5 shrink-0 text-xs">
                  {option.is_correct ? "✓" : option.is_selected ? "✗" : "•"}
                </span>
                <span>
                  {option.option_text}
                  {option.is_selected && <span className="ml-1.5 text-xs font-medium text-muted-foreground">(learner's answer)</span>}
                </span>
              </li>
            ))}
          </ul>
        </div>
      ))}
    </div>
  );
}

// One bundle sub-activity row. The title still drills into the item's own
// detail; a quiz additionally gets a "View quiz" toggle that reveals the
// focused learner's graded body + score inline.
function BundleItem({ item, learner, onNavigate }: { item: any; learner: string; onNavigate: () => void }) {
  const isQuiz = (item.material_type || "").toLowerCase() === "quiz";
  const [open, setOpen] = useState(false);
  return (
    <li className="px-7 py-3">
      <div className="flex items-center justify-between gap-3">
        <button type="button" onClick={onNavigate} className="flex min-w-0 items-center gap-2 text-left">
          <span className={`shrink-0 rounded-sm px-1.5 py-0.5 text-[10px] font-semibold uppercase ${materialBadgeClass(item.material_type)}`}>{item.material_type}</span>
          <span className="truncate text-sm font-medium text-foreground hover:text-primary hover:underline">{item.activity || item.title}</span>
        </button>
        <div className="flex shrink-0 items-center gap-3">
          {isQuiz && (
            <button type="button" onClick={() => setOpen((value) => !value)} className="text-xs font-medium text-primary hover:underline">
              {open ? "Hide quiz" : "View quiz"}
            </button>
          )}
          {item.iframe_url && (
            <a href={item.iframe_url} target="_blank" rel="noreferrer" className="text-xs font-medium text-primary hover:underline">Open ↗</a>
          )}
        </div>
      </div>
      {isQuiz && open && (
        <div className="mt-2 overflow-hidden rounded-md border border-border bg-card">
          <QuizBody learner={learner} component={item.component_id} />
        </div>
      )}
    </li>
  );
}

function roundHours(value: number | null | undefined) {
  return value == null ? "—" : String(Math.round(value * 100) / 100);
}

// A number|null field pre-fill: "" when absent so the input starts empty.
function asInput(value: number | null | undefined) {
  return value == null ? "" : String(value);
}

// One editable participant row (+ an expandable editor beneath it).
function ParticipantRow({
  participant,
  category,
  componentId,
  isPrimary,
  onFocus,
  onSaved,
}: {
  participant: any;
  category: string;
  componentId: string | number;
  isPrimary: boolean;
  onFocus: (participant: any) => void;
  onSaved: (learnerId: number, patch: any) => Promise<void>;
}) {
  const isAttendance = category === "attendance";
  const [open, setOpen] = useState(false);
  const [planned, setPlanned] = useState(asInput(participant.planned));
  const [actual, setActual] = useState(asInput(participant.actual));
  const [attended, setAttended] = useState(Boolean(participant.completed));
  const [startedAt, setStartedAt] = useState("");
  const [completedAt, setCompletedAt] = useState("");
  const [journal, setJournal] = useState("");
  const [saving, setSaving] = useState(false);

  // Re-seed if the underlying data changes after a refetch.
  useEffect(() => {
    setPlanned(asInput(participant.planned));
    setActual(asInput(participant.actual));
    setAttended(Boolean(participant.completed));
  }, [participant.planned, participant.actual, participant.completed]);

  function buildPatch() {
    const patch: any = {};
    if (planned !== asInput(participant.planned) && planned !== "") patch.planned_hours = Number(planned);
    if (isAttendance) {
      if (attended !== Boolean(participant.completed)) patch.attended = attended;
    } else if (actual !== asInput(participant.actual) && actual !== "") {
      patch.actual_hours = Number(actual);
    }
    if (startedAt) patch.started_at = new Date(startedAt).toISOString();
    if (completedAt) patch.completed_at = new Date(completedAt).toISOString();
    if (journal.trim()) patch.journal = journal.trim();
    return patch;
  }

  async function save() {
    const patch = buildPatch();
    if (Object.keys(patch).length === 0) {
      toast.fire({ icon: "info", title: "Nothing changed to save." });
      return;
    }
    setSaving(true);
    try {
      await onSaved(participant.learner_id, patch);
      toast.fire({ icon: "success", title: `Saved ${participant.learner_name}.` });
      setStartedAt("");
      setCompletedAt("");
      setJournal("");
      setOpen(false);
    } catch (error) {
      toast.fire({ icon: "error", title: error instanceof Error ? error.message : "Save failed." });
    } finally {
      setSaving(false);
    }
  }

  // In read mode the whole row is clickable to re-focus the activity on this
  // learner; while editing it isn't, so the inputs work normally.
  const rowClickable = !open;
  return (
    <>
      <TableRow
        role={rowClickable ? "button" : undefined}
        tabIndex={rowClickable ? 0 : undefined}
        title={rowClickable ? "Focus this activity on this learner" : undefined}
        onClick={rowClickable ? () => onFocus(participant) : undefined}
        onKeyDown={
          rowClickable
            ? (event) => {
                if (event.key === "Enter" || event.key === " ") { event.preventDefault(); onFocus(participant); }
              }
            : undefined
        }
        className={
          open
            ? "bg-[#eaf1f8]"
            : `cursor-pointer hover:bg-[#eaf1f8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-primary ${isPrimary ? "bg-primary/5" : ""}`
        }
      >
        <TableCell className="pl-7 text-sm font-medium text-foreground">
          {participant.learner_name}
          {isPrimary && <span className="ml-2 rounded-sm bg-primary/15 px-1.5 py-0.5 text-[10px] font-semibold uppercase text-primary">focused</span>}
        </TableCell>
        <TableCell className="font-mono text-xs text-muted-foreground">{participant.learner_id}</TableCell>
        <TableCell className="whitespace-nowrap font-mono text-xs text-muted-foreground">{participant.date ?? "—"}</TableCell>
        <TableCell className="whitespace-nowrap text-center font-mono text-xs text-muted-foreground">{participant.timestamp_display || "—"}</TableCell>
        <TableCell className="text-xs text-muted-foreground">{category}</TableCell>
        <TableCell className="max-w-md text-sm text-foreground">
          {participant.activity}
          {participant.item_title && <span className="mt-0.5 block text-xs text-muted-foreground">{participant.item_title}</span>}
        </TableCell>
        <TableCell className="text-right font-mono text-sm">
          {open ? (
            <input type="number" step="0.25" min="0" value={planned} onChange={(e) => setPlanned(e.target.value)} className="h-8 w-20 rounded-md border border-border bg-card px-2 text-right text-sm outline-none focus:border-primary" />
          ) : roundHours(participant.planned)}
        </TableCell>
        <TableCell className="text-right font-mono text-sm text-success">
          {open ? (
            isAttendance ? (
              <label className="flex items-center justify-end gap-1.5 text-xs text-foreground">
                <input type="checkbox" checked={attended} onChange={(e) => setAttended(e.target.checked)} /> attended
              </label>
            ) : (
              <input type="number" step="0.25" min="0" value={actual} onChange={(e) => setActual(e.target.value)} className="h-8 w-20 rounded-md border border-border bg-card px-2 text-right text-sm outline-none focus:border-primary" />
            )
          ) : roundHours(participant.actual)}
        </TableCell>
        <TableCell className="pr-7 text-right">
          <button
            type="button"
            onClick={(event) => { event.stopPropagation(); setOpen((value) => !value); }}
            className="rounded-md border border-border bg-card px-2.5 py-1 text-xs font-semibold text-foreground hover:bg-secondary"
          >
            {open ? "Cancel" : "Edit"}
          </button>
        </TableCell>
      </TableRow>
      {open && (
        <TableRow className="bg-[#f7f9fc] hover:bg-[#f7f9fc]">
          <TableCell colSpan={9} className="px-7 py-4">
            <div className="grid gap-4 lg:grid-cols-[repeat(2,minmax(0,1fr))_2fr]">
              <label className="block">
                <span className="label-caps">Started at</span>
                <input type="datetime-local" value={startedAt} onChange={(e) => setStartedAt(e.target.value)} className="mt-1.5 h-9 w-full rounded-md border border-border bg-card px-2.5 text-sm outline-none focus:border-primary" />
              </label>
              <label className="block">
                <span className="label-caps">Completed at</span>
                <input type="datetime-local" value={completedAt} onChange={(e) => setCompletedAt(e.target.value)} className="mt-1.5 h-9 w-full rounded-md border border-border bg-card px-2.5 text-sm outline-none focus:border-primary" />
              </label>
              <label className="block">
                <span className="label-caps">Journal entry</span>
                <textarea value={journal} onChange={(e) => setJournal(e.target.value)} rows={2} placeholder="Off-the-job reflection for this learner…" className="mt-1.5 w-full rounded-md border border-border bg-card px-2.5 py-2 text-sm outline-none focus:border-primary" />
              </label>
            </div>
            <div className="mt-3 flex items-center gap-3">
              <button type="button" onClick={save} disabled={saving} className="rounded-md bg-primary px-3.5 py-1.5 text-sm font-medium text-primary-foreground hover:opacity-90 disabled:opacity-60">
                {saving ? "Saving…" : "Save row"}
              </button>
              <span className="text-xs text-muted-foreground">
                Edits {participant.learner_name}'s record only. Time fields are optional; leave blank to keep the current value.
              </span>
            </div>
          </TableCell>
        </TableRow>
      )}
    </>
  );
}

function ActivityLogPage() {
  const router = useRouter();
  const queryClient = useQueryClient();
  const { learner, activity: componentId } = Route.useSearch();

  // The activity + its sub-activities + participants come from the /activity endpoint.
  const detail = useQuery({
    queryKey: ["activity-detail", componentId],
    queryFn: () => getActivityDetail(componentId),
    enabled: Boolean(componentId),
  });
  const data = detail.data;

  // The snapshot's Mapped KSBs + content iframe come from the /activities row payload.
  const row = useQuery({
    queryKey: ["activity-row", learner, componentId],
    queryFn: () => getLearnerActivities({ learner: learner || undefined, search: componentId || "", limit: 1, offset: 0 }),
    enabled: Boolean(componentId),
  });
  const activityRow = row.data?.items[0];

  // The learner whose per-learner edits the activity-level form writes to: the
  // one from the route if present, else the first participant.
  const primary =
    data?.participants.find((p) => p.learner_name.toLowerCase() === (learner || "").toLowerCase()) ??
    data?.participants[0];

  // Activity-level (shared) edit form.
  const [nameInput, setNameInput] = useState("");
  const [plannedInput, setPlannedInput] = useState("");
  const [actualInput, setActualInput] = useState("");
  const [ksbNotesInput, setKsbNotesInput] = useState("");
  const [editedByInput, setEditedByInput] = useState("");
  const [applyAll, setApplyAll] = useState(false);
  const [savingActivity, setSavingActivity] = useState(false);

  useEffect(() => {
    if (data) setNameInput(data.activity ?? "");
  }, [data?.activity]);
  useEffect(() => {
    setPlannedInput(asInput(primary?.planned));
    setActualInput(asInput(primary?.actual));
  }, [primary?.planned, primary?.actual]);

  // Refetch this activity + bust the shared read caches so the cohort/activity
  // log totals pick up the change too.
  async function refreshAfterEdit() {
    invalidateOtjhCaches();
    await queryClient.invalidateQueries({ queryKey: ["activity-detail"] });
    await queryClient.invalidateQueries({ queryKey: ["activity-row"] });
    // Cohort table + activity log + journal read from these.
    queryClient.invalidateQueries({ queryKey: ["learner-summaries"] });
    queryClient.invalidateQueries({ queryKey: ["learner-activities-search"] });
    queryClient.invalidateQueries({ queryKey: ["journal-activities"] });
    queryClient.invalidateQueries({ queryKey: ["journal-summary"] });
    queryClient.invalidateQueries({ queryKey: ["search-filter-options"] });
  }

  async function saveActivityLevel() {
    if (!primary) return;
    const patch: any = {};
    if (nameInput && nameInput !== data?.activity) patch.front_end_name = nameInput;
    if (plannedInput !== "" && plannedInput !== asInput(primary.planned)) patch.planned_hours = Number(plannedInput);
    if (actualInput !== "" && actualInput !== asInput(primary.actual)) patch.actual_hours = Number(actualInput);
    if (ksbNotesInput.trim()) patch.ksb_notes = ksbNotesInput.trim();
    if (editedByInput.trim()) patch.edited_by = editedByInput.trim();
    if (Object.keys(patch).length === 0) {
      toast.fire({ icon: "info", title: "Nothing changed to save." });
      return;
    }
    setSavingActivity(true);
    try {
      const response = await editActivity({
        aptem_id: primary.learner_id,
        component_id: data!.component_id,
        patch,
        apply_shared_to_all: applyAll,
      });
      const also = response.also_applied_to?.length ? ` · applied to ${response.also_applied_to.length + 1} learners` : "";
      toast.fire({ icon: "success", title: `Activity saved${also}.` });
      setKsbNotesInput("");
      await refreshAfterEdit();
    } catch (error) {
      toast.fire({ icon: "error", title: error instanceof Error ? error.message : "Save failed." });
    } finally {
      setSavingActivity(false);
    }
  }

  const category = data?.category ?? activityRow?.activity_category ?? "";
  // The learner whose per-learner quiz attempt (score + graded body) we read.
  const focusedLearner = (primary?.learner_name || learner || "").toLowerCase();

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border bg-surface">
        <div className="mx-auto flex max-w-[1700px] flex-wrap items-center justify-between gap-4 px-6 py-4">
          <div className="flex items-baseline gap-3">
            <span className="font-serif text-base text-foreground">OTJ&nbsp;Ledger</span>
            <span className="label-caps">Activity detail</span>
          </div>
          <div className="flex items-center gap-4 text-xs text-muted-foreground">
            {activityRow?.month_unit && <span className="font-mono">{activityRow.month_unit}</span>}
            <button type="button" onClick={() => router.history.back()} className="font-medium text-foreground hover:underline">← Back</button>
            <Link to="/search" className="font-medium text-foreground hover:underline">Search</Link>
            <Link
              to="/journal"
              search={{ learner: learner || primary?.learner_name?.toLowerCase() || "", period: activityRow?.activity_period || "" }}
              className="font-medium text-foreground hover:underline"
            >
              Monthly journal →
            </Link>
            <span className="rounded-sm border border-success/40 bg-success/10 px-2 py-1 font-semibold text-success">Live data</span>
          </div>
        </div>
      </header>

      <main className="mx-auto w-full max-w-[1700px] space-y-6 px-6 py-8">
        {detail.isLoading && (
          <div className="rounded-lg border border-border bg-card px-7 py-16 text-center text-sm text-muted-foreground">Loading activity…</div>
        )}
        {detail.isError && (
          <div className="rounded-lg border border-border bg-card px-7 py-16 text-center text-sm text-destructive">
            {detail.error instanceof Error ? detail.error.message : "Could not load this activity."}
          </div>
        )}

        {data && (
          <div className="grid gap-6 lg:grid-cols-3">
            <article className="space-y-6 lg:col-span-2">
              {/* Bundle sub-activities. */}
              {data.items.length > 0 && (
                <section className="rounded-lg border border-border bg-card shadow-panel">
                  <header className="border-b border-border px-7 py-5">
                    <h2 className="font-serif text-lg text-foreground">Activities inside this bundle</h2>
                    <p className="mt-1 text-sm text-muted-foreground">{data.item_count} item{data.item_count === 1 ? "" : "s"}. Click one to drill into its own participants.</p>
                  </header>
                  <ul className="divide-y divide-border">
                    {data.items.map((item) => (
                      <BundleItem
                        key={item.component_id}
                        item={item}
                        learner={focusedLearner}
                        onNavigate={() => router.navigate({ to: "/activity", search: { learner, activity: String(item.component_id) } })}
                      />
                    ))}
                  </ul>
                </section>
              )}

              {/* A drilled-into quiz leaf (no sub-items): show the focused
                  learner's graded body + score directly. */}
              {data.items.length === 0 && category.toLowerCase().includes("quiz") && (
                <section className="rounded-lg border border-border bg-card shadow-panel">
                  <header className="border-b border-border px-7 py-5">
                    <h2 className="font-serif text-lg text-foreground">Quiz result</h2>
                    <p className="mt-1 text-sm text-muted-foreground">
                      {primary?.learner_name ? `${primary.learner_name}'s graded attempt.` : "Graded attempt for the focused learner."}
                    </p>
                  </header>
                  <QuizBody learner={focusedLearner} component={data.component_id} />
                </section>
              )}

              {/* Activity content preview (video / audio / reading). */}
              {activityRow?.source_url && (
                <section className="rounded-lg border border-border bg-card shadow-panel">
                  <header className="flex items-center justify-between border-b border-border px-7 py-5">
                    <h2 className="font-serif text-lg text-foreground">Activity content</h2>
                    <a href={activityRow.source_url} target="_blank" rel="noreferrer" className="text-xs font-medium text-primary hover:underline">Open in new tab ↗</a>
                  </header>
                  <div className="p-5">
                    <div className="aspect-video w-full overflow-hidden rounded-md border border-border bg-black/5">
                      <iframe src={activityRow.source_url} title={data.activity} className="h-full w-full" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen />
                    </div>
                  </div>
                </section>
              )}

              {/* The same inline CRUD row used by search and journal. */}
              <MreTable component={String(data.component_id)} learner={primary?.learner_name} />
            </article>

            {/* Snapshot + activity-level editing. */}
            <aside className="activity-snapshot overflow-hidden rounded-lg border border-border bg-card shadow-panel">
              <header className="bg-primary px-6 py-5 text-primary-foreground">
                <p className="snapshot-label label-caps">Activity snapshot</p>
                <h2 className="mt-1 font-serif text-xl font-bold text-primary-foreground">{data.activity}</h2>
              </header>
              <dl className="grid gap-5 px-6 py-6">
                <div>
                  <dt className="label-caps">Category</dt>
                  <dd className="mt-1 text-sm capitalize text-foreground">{category || "—"}</dd>
                </div>
                <div>
                  <dt className="label-caps">Component ID</dt>
                  <dd className="mt-1 font-mono text-sm text-foreground">{data.component_id}</dd>
                </div>
                {activityRow?.week && (
                  <div>
                    <dt className="label-caps">Lecture / week</dt>
                    <dd className="mt-1 text-sm text-foreground">{activityRow.week}</dd>
                  </div>
                )}
              </dl>

              {/* Mapped KSBs from the /activities row payload. */}
              <section className="border-t border-border px-6 py-6">
                <h3 className="label-caps">Mapped KSBs</h3>
                {activityRow?.ksbs && activityRow.ksbs.length > 0 ? (
                  <ul className="mt-3 space-y-2">
                    {activityRow.ksbs.map((ksb, index) => (
                      <li key={`${ksb.code}-${index}`}>
                        <details className="rounded-md border border-border bg-background/40 px-3 py-2">
                          <summary className="flex cursor-pointer list-none items-center gap-2 [&::-webkit-details-marker]:hidden">
                            <span className={`rounded-sm px-1.5 py-0.5 text-xs font-semibold ${ksbBadgeClass(ksb.type)}`}>{ksb.code}</span>
                            <span className="ml-auto text-xs text-muted-foreground">▸</span>
                          </summary>
                          <div className="mt-2">
                            <span className="text-xs font-medium text-muted-foreground">{ksb.type_label}</span>
                            {ksb.description && <p className="mt-1 text-sm leading-6 text-foreground">{ksb.description}</p>}
                            {ksb.reason && <p className="mt-1 text-xs italic leading-5 text-muted-foreground">Why: {ksb.reason}</p>}
                          </div>
                        </details>
                      </li>
                    ))}
                  </ul>
                ) : (
                  <p className="mt-2 text-sm text-muted-foreground">No KSBs mapped in the programme structure.</p>
                )}
              </section>

              {/* Activity-level edits. */}
              <div className="space-y-4 border-t border-border px-6 py-6">
                <p className="label-caps">Edit activity</p>
                <label className="block">
                  <span className="text-xs font-medium text-muted-foreground">Activity name</span>
                  <input value={nameInput} onChange={(e) => setNameInput(e.target.value)} className="mt-1.5 h-9 w-full rounded-md border border-border bg-card px-2.5 text-sm text-foreground outline-none focus:border-primary" />
                </label>
                <div>
                  {primary && <span className="text-xs font-medium text-muted-foreground">Hours · {primary.learner_name}</span>}
                  <div className="mt-1.5 grid grid-cols-2 gap-3">
                    <label className="block">
                      <span className="text-[10px] uppercase tracking-wide text-muted-foreground">Planned</span>
                      <input type="number" step="0.25" min="0" value={plannedInput} onChange={(e) => setPlannedInput(e.target.value)} className="mt-1 h-9 w-full rounded-md border border-border bg-card px-2.5 text-sm text-foreground outline-none focus:border-primary" />
                    </label>
                    <label className="block">
                      <span className="text-[10px] uppercase tracking-wide text-muted-foreground">Actual</span>
                      <input type="number" step="0.25" min="0" value={actualInput} onChange={(e) => setActualInput(e.target.value)} className="mt-1 h-9 w-full rounded-md border border-border bg-card px-2.5 text-sm text-foreground outline-none focus:border-primary" />
                    </label>
                  </div>
                </div>
                <label className="block">
                  <span className="text-xs font-medium text-muted-foreground">Auditor KSB notes</span>
                  <textarea value={ksbNotesInput} onChange={(e) => setKsbNotesInput(e.target.value)} rows={3} placeholder="Notes or extra KSB mappings…" className="mt-1.5 w-full rounded-md border border-border bg-card px-2.5 py-2 text-sm text-foreground outline-none focus:border-primary" />
                </label>
                <label className="block">
                  <span className="text-xs font-medium text-muted-foreground">Edited by</span>
                  <input value={editedByInput} onChange={(e) => setEditedByInput(e.target.value)} placeholder="Your name" className="mt-1.5 h-9 w-full rounded-md border border-border bg-card px-2.5 text-sm text-foreground outline-none focus:border-primary" />
                </label>
                <label className="flex items-start gap-2 text-xs text-muted-foreground">
                  <input type="checkbox" checked={applyAll} onChange={(e) => setApplyAll(e.target.checked)} className="mt-0.5" />
                  <span>Apply shared fields (name, notes) to all {data.participant_count} learners on this activity.</span>
                </label>
                <button type="button" onClick={saveActivityLevel} disabled={!primary || savingActivity} className="rounded-md bg-primary px-3.5 py-1.5 text-sm font-medium text-primary-foreground hover:opacity-90 disabled:opacity-60">
                  {savingActivity ? "Saving…" : "Save activity"}
                </button>
              </div>
            </aside>
          </div>
        )}

        <p className="pb-4 text-xs text-muted-foreground">
          Activity, participants and edits are served live by the evidence API at{" "}
          <span className="font-mono">fetch-evidence.kentbusinesscollege.net</span>.
        </p>
      </main>
    </div>
  );
}
