// @ts-nocheck -- route search types are generated by the embedded app.
import { useEffect, useRef, useState } from "react";
import { keepPreviousData, useQuery, useQueryClient } from "@tanstack/react-query";
import { createFileRoute, Link, useRouter } from "@tanstack/react-router";
import SignaturePad from "signature_pad";
import Swal from "sweetalert2";
import { ArrowLeft, ArrowRight, CheckCircle2, Download, LoaderCircle, PenLine, RotateCcw, Save, Trash2 } from "lucide-react";
import { fetchAuditSignoff, saveAuditSignoff } from "@/features/audit/api";
import { Button } from "@/features/audit/learner-log-pro-copy/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/features/audit/learner-log-pro-copy/components/ui/table";
import { getLearnerActivities, getLearnerProfile, getLearners } from "@/features/audit/learner-log-pro-copy/lib/api";
import { downloadLearnerJournalPdf } from "@/features/audit/learner-log-pro-copy/lib/journal-pdf";

export const Route = createFileRoute("/journal/")({
  validateSearch: (search: Record<string, unknown>) => ({
    learner: typeof search.learner === "string" ? search.learner : "",
    period: typeof search.period === "string" ? search.period : "",
  }),
  component: JournalPage,
});

const activityPageSize = 20;

async function getAllJournalActivities(learner: string, period: string) {
  const firstPage = await getLearnerActivities({ learner, period, search: "", limit: 100, offset: 0 });
  if (firstPage.items.length >= firstPage.total) return firstPage.items;
  const remainingOffsets = Array.from(
    { length: Math.ceil((firstPage.total - firstPage.items.length) / 100) },
    (_, index) => firstPage.items.length + index * 100,
  );
  const remainingPages = await Promise.all(
    remainingOffsets.map((offset) => getLearnerActivities({ learner, period, search: "", limit: 100, offset })),
  );
  return [...firstPage.items, ...remainingPages.flatMap((page) => page.items)];
}

function SignatureCapture({ label, signer, value, onChange, onRemove, canRemove, isRemoving }: { label: string; signer: string; value: string; onChange: (value: string) => void; onRemove: () => void; canRemove: boolean; isRemoving: boolean }) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const padRef = useRef<SignaturePad | null>(null);
  const onChangeRef = useRef(onChange);

  useEffect(() => {
    onChangeRef.current = onChange;
  }, [onChange]);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ratio = Math.max(window.devicePixelRatio || 1, 1);
    const rect = canvas.getBoundingClientRect();
    canvas.width = Math.max(Math.floor(rect.width * ratio), 1);
    canvas.height = Math.max(Math.floor(rect.height * ratio), 1);
    canvas.getContext("2d")?.scale(ratio, ratio);
    const pad = new SignaturePad(canvas, {
      backgroundColor: "rgb(255, 255, 255)",
      penColor: "rgb(24, 45, 72)",
      minWidth: 0.8,
      maxWidth: 2.4,
      velocityFilterWeight: 0.7,
    });
    padRef.current = pad;
    const handleEndStroke = () => onChangeRef.current(pad.isEmpty() ? "" : pad.toDataURL("image/png"));
    pad.addEventListener("endStroke", handleEndStroke);
    return () => {
      pad.removeEventListener("endStroke", handleEndStroke);
      pad.off();
      padRef.current = null;
    };
  }, []);

  useEffect(() => {
    const pad = padRef.current;
    const canvas = canvasRef.current;
    if (!pad || !canvas) return;
    if (!value) {
      pad.clear();
      return;
    }
    const image = new Image();
    image.onload = () => {
      const context = canvas.getContext("2d");
      if (!context) return;
      pad.clear();
      context.drawImage(image, 0, 0, canvas.clientWidth, canvas.clientHeight);
    };
    image.src = value;
  }, [value]);

  return (
    <div className="rounded-lg border border-border bg-background/40 p-4">
      <div className="mb-3 flex items-start justify-between gap-4">
        <div>
          <p className="label-caps">{label}</p>
          <p className="mt-1 text-sm font-medium text-foreground">{signer || "—"}</p>
        </div>
        <div className="flex items-center gap-2">
          {canRemove && (
            <Button type="button" variant="outline" size="sm" disabled={isRemoving} onClick={onRemove} className="border-red-200 text-red-700 hover:bg-red-50 hover:text-red-800">
              <Trash2 className="h-3.5 w-3.5" /> Remove
            </Button>
          )}
          <Button type="button" variant="outline" size="sm" disabled={!value || isRemoving} onClick={() => { padRef.current?.clear(); onChange(""); }}>
            <RotateCcw className="h-3.5 w-3.5" /> Clear
          </Button>
        </div>
      </div>
      <div className="relative h-32 overflow-hidden rounded-md border border-border bg-white">
        <canvas ref={canvasRef} className="h-full w-full touch-none cursor-crosshair" aria-label={`${label} drawing area`} />
        {!value && (
          <div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center text-muted-foreground/60">
            <PenLine className="mb-2 h-5 w-5" />
            <span className="text-xs">Sign here using mouse or touch</span>
          </div>
        )}
        <div className="pointer-events-none absolute inset-x-8 bottom-7 border-b border-dashed border-border" />
      </div>
    </div>
  );
}

function Stat({ label, value, tone = "navy" }: { label: string; value: string; tone?: "navy" | "purple" | "success" | "warning" }) {
  const accent = {
    navy: "bg-[#182d48]",
    purple: "bg-[#673ab7]",
    success: "bg-emerald-600",
    warning: "bg-red-600",
  }[tone];
  return (
    <div className="relative overflow-hidden rounded-lg bg-[#f6f8fb] px-5 py-4">
      <span className={`absolute inset-y-0 left-0 w-1.5 ${accent}`} />
      <p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">{label}</p>
      <p className="mt-2 font-mono text-xl font-semibold text-[#182d48]">{value}</p>
    </div>
  );
}

function otjhStatusLabel(status: string) {
  switch ((status || "").toLowerCase()) {
    case "over_target": return "Over target";
    case "below_target": return "Below target";
    case "happy_conflict": return "Conflict";
    case "rebuilt": return "Rebuilt (in band)";
    case "happy": return "In band";
    case "skipped_empty": return "No activity";
    default: return status || "—";
  }
}

// Per-month off-the-job-hours adjustment: the engineered hour breakdown vs the
// Aptem actual, plus the review flag.
function OtjhCard({ otjh }: { otjh?: any }) {
  if (!otjh) return null;
  const hour = (value: number | null | undefined) =>
    value == null ? "—" : `${Number(value).toFixed(2)} h`;
  const flagged = Boolean(otjh.flagged);
  return (
    <div className={`rounded-lg border px-5 py-4 ${flagged ? "border-red-300 bg-red-50" : "border-border bg-[#f6f8fb]"}`}>
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div>
          <p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">Off-the-job hours (engineered)</p>
          {otjh.applied_date && <p className="mt-0.5 text-xs text-muted-foreground">Adjustment applied {otjh.applied_date}</p>}
        </div>
        <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${flagged ? "bg-red-600 text-white" : "bg-emerald-600/10 text-emerald-700"}`}>
          {flagged ? "⚑ " : ""}{otjhStatusLabel(otjh.status)}
        </span>
      </div>
      <div className="mt-3 grid gap-3 sm:grid-cols-3 lg:grid-cols-5">
        <div><p className="text-[10px] uppercase text-muted-foreground">Attendance</p><p className="mt-0.5 font-mono text-sm text-[#182d48]">{hour(otjh.att_h)}</p></div>
        <div><p className="text-[10px] uppercase text-muted-foreground">Assignments</p><p className="mt-0.5 font-mono text-sm text-[#182d48]">{hour(otjh.asg_h)}</p></div>
        <div><p className="text-[10px] uppercase text-muted-foreground">LMS</p><p className="mt-0.5 font-mono text-sm text-[#182d48]">{hour(otjh.lms_h)}</p></div>
        <div><p className="text-[10px] uppercase text-muted-foreground">Computed total</p><p className="mt-0.5 font-mono text-sm font-semibold text-[#182d48]">{hour(otjh.computed_total_h)}</p></div>
        <div><p className="text-[10px] uppercase text-muted-foreground">Aptem actual</p><p className="mt-0.5 font-mono text-sm text-[#182d48]">{hour(otjh.aptem_actual_h)}</p></div>
      </div>
      {(otjh.n_media != null || otjh.n_bundles != null || otjh.n_reading_items != null) && (
        <p className="mt-3 text-xs text-muted-foreground">
          {otjh.n_media ?? 0} media · {otjh.n_bundles ?? 0} bundles · {otjh.n_reading_items ?? 0} reading items
        </p>
      )}
      {flagged && (
        <p className="mt-2 text-xs font-medium text-red-700">Flagged for manual review — best-effort engineered hours may not match the Aptem actual.</p>
      )}
      {otjh.note && (
        <p className="mt-2 border-t border-border/60 pt-2 text-xs italic leading-5 text-muted-foreground">{otjh.note}</p>
      )}
    </div>
  );
}

function ProfileGroup({ label, value, secondaryLabel, secondaryValue }: { label: string; value: string; secondaryLabel: string; secondaryValue: string }) {
  return (
    <div className="space-y-4 px-5 py-4 first:pl-0 last:pr-0 lg:border-r lg:border-border lg:last:border-r-0">
      <div>
        <p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">{label}</p>
        <p className="mt-1.5 text-sm font-semibold text-[#182d48]">{value || "—"}</p>
      </div>
      <div>
        <p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">{secondaryLabel}</p>
        <p className="mt-1.5 font-mono text-sm font-medium text-[#182d48]">{secondaryValue || "—"}</p>
      </div>
    </div>
  );
}

function JournalPage() {
  const router = useRouter();
  const queryClient = useQueryClient();
  const routeSearch = Route.useSearch();
  const [learnerChoice, setLearnerChoice] = useState(routeSearch.learner);
  const [periodChoice, setPeriodChoice] = useState(routeSearch.period);
  const [activityPage, setActivityPage] = useState(0);
  const [isPreparingPdf, setIsPreparingPdf] = useState(false);
  const [learnerSignature, setLearnerSignature] = useState("");
  const [coachSignature, setCoachSignature] = useState("");
  const [learnerSignatureSaved, setLearnerSignatureSaved] = useState(false);
  const [coachSignatureSaved, setCoachSignatureSaved] = useState(false);
  const [isSavingSignatures, setIsSavingSignatures] = useState(false);
  const [signatureError, setSignatureError] = useState("");
  const signaturesSaved = learnerSignatureSaved && coachSignatureSaved;

  const metadata = useQuery({ queryKey: ["journal-metadata"], queryFn: () => getLearners() });
  useEffect(() => {
    if (!metadata.data) return;
    if (!learnerChoice && metadata.data.learners[0]) {
      setLearnerChoice(metadata.data.learners[0].id);
    }
    if (!periodChoice && metadata.data.periods.length) {
      setPeriodChoice(metadata.data.periods[metadata.data.periods.length - 1]!.value);
    }
  }, [metadata.data, learnerChoice, periodChoice]);

  const selectedLearner = learnerChoice;
  const selectedPeriod = periodChoice;

  const monthSummaries = useQuery({
    queryKey: ["journal-summary", selectedPeriod],
    queryFn: () => getLearners({ period: selectedPeriod }),
    enabled: Boolean(selectedPeriod),
  });
  const activities = useQuery({
    queryKey: ["journal-activities", selectedLearner, selectedPeriod, activityPage],
    queryFn: () => getLearnerActivities({
      learner: selectedLearner,
      period: selectedPeriod,
      search: "",
      limit: activityPageSize,
      offset: activityPage * activityPageSize,
    }),
    enabled: Boolean(selectedLearner && selectedPeriod),
    placeholderData: keepPreviousData,
  });
  const learnerProfile = useQuery({
    queryKey: ["learner-profile", selectedLearner],
    queryFn: () => getLearnerProfile(selectedLearner),
    enabled: Boolean(selectedLearner),
  });
  const savedSignoff = useQuery({
    queryKey: ["journal-signoff", learnerProfile.data?.aptem_id, selectedPeriod],
    queryFn: () => fetchAuditSignoff(learnerProfile.data!.aptem_id, selectedPeriod),
    enabled: Boolean(learnerProfile.data?.aptem_id && selectedPeriod),
  });

  useEffect(() => {
    if (!savedSignoff.data) return;
    const savedLearnerSignature = savedSignoff.data.signoffs.learner?.signature_data ?? "";
    const savedCoachSignature = savedSignoff.data.signoffs.coach?.signature_data ?? "";
    setLearnerSignature(savedLearnerSignature);
    setCoachSignature(savedCoachSignature);
    setLearnerSignatureSaved(Boolean(savedLearnerSignature));
    setCoachSignatureSaved(Boolean(savedCoachSignature));
    setSignatureError("");
  }, [savedSignoff.data]);

  const learner = monthSummaries.data?.learners.find((item) => item.id === selectedLearner);
  const cumulativeLearner = metadata.data?.learners.find((item) => item.id === selectedLearner);
  const monthLabel = metadata.data?.periods.find((item) => item.value === selectedPeriod)?.label ?? selectedPeriod;
  const activityTotal = activities.data?.total ?? 0;
  const activityTotalPages = Math.max(1, Math.ceil(activityTotal / activityPageSize));
  const activityFrom = activityTotal === 0 ? 0 : activityPage * activityPageSize + 1;
  const activityTo = Math.min((activityPage + 1) * activityPageSize, activityTotal);

  async function handleDownloadPdf() {
    if (!learner || !learnerProfile.data || !selectedLearner || !selectedPeriod) return;
    setIsPreparingPdf(true);
    try {
      const allRows = await getAllJournalActivities(selectedLearner, selectedPeriod);
      await downloadLearnerJournalPdf(learner, monthLabel, allRows, cumulativeLearner, learnerProfile.data, {
        learner: learnerSignature,
        coach: coachSignature,
      });
    } finally {
      setIsPreparingPdf(false);
    }
  }

  async function handleSaveSignatures() {
    const aptemId = learnerProfile.data?.aptem_id;
    if (!aptemId || !learner || !learnerSignature || !coachSignature) return;
    setIsSavingSignatures(true);
    setSignatureError("");
    try {
      const now = new Date().toISOString();
      const response = await saveAuditSignoff(aptemId, {
        monthKey: selectedPeriod,
        roles: {
          learner: { signerName: learner.name, signature: learnerSignature, confirmed: true, signedAt: now },
          coach: { signerName: learnerProfile.data?.coach.name ?? "", signature: coachSignature, confirmed: true, signedAt: now },
        },
      });
      queryClient.setQueryData(["journal-signoff", aptemId, selectedPeriod], response);
      setLearnerSignature(response.signoffs.learner?.signature_data ?? learnerSignature);
      setCoachSignature(response.signoffs.coach?.signature_data ?? coachSignature);
      setLearnerSignatureSaved(Boolean(response.signoffs.learner?.signature_data));
      setCoachSignatureSaved(Boolean(response.signoffs.coach?.signature_data));
    } catch (error) {
      setSignatureError(error instanceof Error ? error.message : "Could not save the signatures.");
      setSignaturesSaved(false);
    } finally {
      setIsSavingSignatures(false);
    }
  }

  async function handleRemoveSignature(role: "learner" | "coach") {
    const aptemId = learnerProfile.data?.aptem_id;
    if (!aptemId || !learner) return;
    const roleLabel = role === "learner" ? "learner" : "coach";
    const confirmation = await Swal.fire({
      icon: "warning",
      title: `Remove ${roleLabel} signature?`,
      text: `This removes the saved ${roleLabel} signature for ${monthLabel}.`,
      showCancelButton: true,
      confirmButtonText: "Yes, remove it",
      cancelButtonText: "Cancel",
      confirmButtonColor: "#b91c1c",
      reverseButtons: true,
    });
    if (!confirmation.isConfirmed) return;
    setIsSavingSignatures(true);
    setSignatureError("");
    try {
      const nextLearnerSignature = role === "learner" ? "" : learnerSignature;
      const nextCoachSignature = role === "coach" ? "" : coachSignature;
      const now = new Date().toISOString();
      const response = await saveAuditSignoff(aptemId, {
        monthKey: selectedPeriod,
        roles: {
          learner: { signerName: learner.name, signature: nextLearnerSignature, confirmed: Boolean(nextLearnerSignature), signedAt: nextLearnerSignature ? now : "" },
          coach: { signerName: learnerProfile.data?.coach.name ?? "", signature: nextCoachSignature, confirmed: Boolean(nextCoachSignature), signedAt: nextCoachSignature ? now : "" },
        },
      });
      queryClient.setQueryData(["journal-signoff", aptemId, selectedPeriod], response);
      setLearnerSignature(response.signoffs.learner?.signature_data ?? "");
      setCoachSignature(response.signoffs.coach?.signature_data ?? "");
      setLearnerSignatureSaved(Boolean(response.signoffs.learner?.signature_data));
      setCoachSignatureSaved(Boolean(response.signoffs.coach?.signature_data));
      await Swal.fire({ icon: "success", title: "Signature removed", text: `The ${roleLabel} signature was removed successfully.`, timer: 1800, showConfirmButton: false });
    } catch (error) {
      const message = error instanceof Error ? error.message : "Could not remove the signature.";
      setSignatureError(message);
      await Swal.fire({ icon: "error", title: "Could not remove signature", text: message });
    } finally {
      setIsSavingSignatures(false);
    }
  }
  const isLoading =
    metadata.isLoading ||
    (Boolean(selectedPeriod) && monthSummaries.isLoading) ||
    (Boolean(selectedLearner && selectedPeriod) && activities.isLoading) ||
    (Boolean(selectedLearner) && learnerProfile.isLoading) ||
    (Boolean(learnerProfile.data?.aptem_id && selectedPeriod) && savedSignoff.isLoading);
  const pageError = metadata.error || monthSummaries.error || activities.error || learnerProfile.error || savedSignoff.error;

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border bg-surface">
        <div className="flex w-full flex-wrap items-center justify-between gap-4 px-6 py-4">
          <div className="flex items-baseline gap-3">
            <span className="font-serif text-base text-foreground">OTJ&nbsp;Ledger</span>
            <span className="label-caps">Live learner journal</span>
          </div>
          <div className="flex items-center gap-4 text-xs text-muted-foreground">
            <button type="button" onClick={() => router.history.back()} className="font-medium text-foreground hover:underline">← Back</button>
            <Link to="/search" className="font-medium hover:underline">Search</Link>
            <Link to="/activity" search={{ learner: selectedLearner }} className="font-medium hover:underline">Activity log</Link>
          </div>
        </div>
      </header>

      <main className="w-full space-y-6 px-6 py-8">
        <section className="overflow-hidden rounded-xl border border-border bg-card shadow-panel">
          <div className="h-1 bg-[#182d48]" />
          <div className="flex flex-wrap items-center justify-between gap-6 px-7 py-6">
            <div className="flex items-center gap-5">
              <img src="/assets/kbc-logo.png" alt="Kent Business College" className="h-16 w-36 object-contain object-left" />
              <span className="h-14 w-px bg-border" />
              <div>
                <h1 className="text-2xl font-semibold tracking-tight text-[#182d48]">Learner Journal</h1>
                <p className="mt-1 text-sm text-muted-foreground">Monthly off-the-job learning record</p>
                <p className="mt-1 text-xs text-muted-foreground">Generated from <span className="font-mono">Audit.learner_match</span></p>
              </div>
            </div>
            <div className="flex items-center gap-3">
              <div className="rounded-xl bg-[#f6f8fb] px-6 py-3 text-center">
                <p className="text-[9px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">Reporting month</p>
                <p className="mt-1 text-sm font-semibold text-[#182d48]">{metadata.isLoading ? "Loading…" : monthLabel}</p>
              </div>
              <Button
                className="gap-2 bg-[#182d48] hover:bg-[#243f61]"
                disabled={!learner || !activities.data || !learnerProfile.data || !signaturesSaved || isPreparingPdf}
                onClick={handleDownloadPdf}
              >
                {isPreparingPdf ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}
                {isPreparingPdf ? "Preparing PDF..." : "Download PDF"}
              </Button>
            </div>
          </div>

          <div className="grid gap-4 border-y border-border bg-[#fafbfc] px-7 py-5 sm:grid-cols-2">
            <label><span className="label-caps">Learner</span><select className="mt-1.5 h-9 w-full rounded-md border border-border bg-card px-3 text-sm" value={selectedLearner} onChange={(event) => { setLearnerChoice(event.target.value); setActivityPage(0); setLearnerSignature(""); setCoachSignature(""); setLearnerSignatureSaved(false); setCoachSignatureSaved(false); }}>{metadata.data?.learners.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
            <label><span className="label-caps">Activity month</span><select className="mt-1.5 h-9 w-full rounded-md border border-border bg-card px-3 text-sm" value={selectedPeriod} onChange={(event) => { setPeriodChoice(event.target.value); setActivityPage(0); setLearnerSignature(""); setCoachSignature(""); setLearnerSignatureSaved(false); setCoachSignatureSaved(false); }}>{metadata.data?.periods.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>
          </div>

          {pageError ? (
            <p className="py-10 text-center text-sm text-destructive">
              {pageError instanceof Error ? pageError.message : "Could not load the journal."}
            </p>
          ) : isLoading || !selectedLearner || !selectedPeriod ? (
            <p className="py-10 text-center text-sm text-muted-foreground">Loading journal from Neon…</p>
          ) : learner ? (
            <div className="space-y-5 px-7 py-6">
              <div className="grid rounded-lg bg-[#f6f8fb] px-5 lg:grid-cols-3">
                <ProfileGroup label="Learner" value={learner.name} secondaryLabel="Start date" secondaryValue={learnerProfile.data?.learning_delivery.start_date ?? "—"} />
                <ProfileGroup label="Programme" value={learnerProfile.data?.programme ?? "—"} secondaryLabel="First evidence" secondaryValue={learnerProfile.data?.learning_delivery.first_evidence_date ?? "—"} />
                <ProfileGroup label="Coach" value={learnerProfile.data?.coach.name ?? "—"} secondaryLabel="Planned end" secondaryValue={learnerProfile.data?.learning_delivery.planned_end_date ?? "—"} />
              </div>
              <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                <Stat label="Monthly plan" value={`${learner.planned_hours.toFixed(2)} h`} />
                <Stat label="Claimed" value={`${learner.actual_hours.toFixed(2)} h`} tone="purple" />
                <Stat label="Accepted" value={`${learner.actual_hours.toFixed(2)} h`} tone="success" />
                <Stat label="Variance" value={`${learner.gap_hours > 0 ? "+" : ""}${learner.gap_hours.toFixed(2)} h`} tone={learner.gap_hours < 0 ? "warning" : "success"} />
              </div>
              <OtjhCard otjh={activities.data?.otjh} />
            </div>
          ) : null}
        </section>

        <section className="overflow-hidden rounded-xl border border-border bg-card shadow-panel">
          <header className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-7 py-5">
            <div>
              <h2 className="text-lg font-semibold text-[#182d48]">Activity log</h2>
              <p className="mt-1 text-sm text-muted-foreground">Claimed and accepted off-the-job learning time</p>
            </div>
            <span className="rounded-full bg-[#f6f8fb] px-3 py-1.5 font-mono text-xs font-medium text-[#182d48]">{activities.data?.total ?? 0} activities</span>
          </header>
          <div className="overflow-x-auto">
            <Table>
              <TableHeader><TableRow className="border-0 bg-[#182d48] hover:bg-[#182d48]"><TableHead className="label-caps pl-7 text-white">Plan ID</TableHead><TableHead className="label-caps text-white">Date</TableHead><TableHead className="label-caps text-white">Activity</TableHead><TableHead className="label-caps text-white">Category</TableHead><TableHead className="label-caps text-white">Timestamp</TableHead><TableHead className="label-caps text-right text-white">Planned</TableHead><TableHead className="label-caps pr-7 text-right text-white">Actual</TableHead></TableRow></TableHeader>
              <TableBody>
                {activities.data?.items.map((row) => (
                  <TableRow
                    key={row.id}
                    role="link"
                    tabIndex={0}
                    title="Open activity details"
                    onClick={() => router.navigate({ to: "/activity", search: { learner: row.learner.toLowerCase(), activity: row.plan_id } })}
                    onKeyDown={(event) => {
                      if (event.key === "Enter" || event.key === " ") {
                        event.preventDefault();
                        router.navigate({ to: "/activity", search: { learner: row.learner.toLowerCase(), activity: row.plan_id } });
                      }
                    }}
                    className="cursor-pointer odd:bg-[#f7f9fc] hover:bg-[#eaf1f8] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-[#673ab7]"
                  >
                    <TableCell className="max-w-64 truncate pl-7 font-mono text-xs">{row.plan_id}</TableCell>
                    <TableCell className="font-mono text-xs text-muted-foreground">{row.learner_activity_date ?? "—"}</TableCell>
                    <TableCell className="max-w-md"><p className="text-sm font-medium">{row.activity_unit}</p><p className="mt-1 text-xs text-muted-foreground">{row.activity_description}</p></TableCell>
                    <TableCell className="text-xs text-muted-foreground">{row.activity_category}</TableCell>
                    <TableCell className="font-mono text-xs text-muted-foreground">{row.time_from_to ?? "—"}</TableCell>
                    <TableCell className="text-right font-mono text-sm">{row.planned_hours?.toFixed(2) ?? "—"}</TableCell>
                    <TableCell className="pr-7 text-right font-mono text-sm font-medium text-success">{row.actual_lms_hours?.toFixed(2) ?? "—"}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
          <footer className="flex flex-wrap items-center justify-between gap-3 border-t border-border px-7 py-4">
            <p className="text-xs text-muted-foreground">
              Showing <span className="font-mono font-medium text-foreground">{activityFrom}–{activityTo}</span> of <span className="font-mono font-medium text-foreground">{activityTotal}</span> activities
            </p>
            <div className="flex items-center gap-2">
              <Button variant="outline" size="sm" disabled={activityPage === 0 || activities.isFetching} onClick={() => setActivityPage((page) => Math.max(0, page - 1))}>
                <ArrowLeft className="h-3.5 w-3.5" /> Previous
              </Button>
              <span className="min-w-24 text-center text-xs text-muted-foreground">
                Page <span className="font-mono font-medium text-foreground">{activityPage + 1}</span> of <span className="font-mono font-medium text-foreground">{activityTotalPages}</span>
              </span>
              <Button variant="outline" size="sm" disabled={activityPage + 1 >= activityTotalPages || activities.isFetching} onClick={() => setActivityPage((page) => Math.min(activityTotalPages - 1, page + 1))}>
                Next <ArrowRight className="h-3.5 w-3.5" />
              </Button>
            </div>
          </footer>
        </section>

        <section className="rounded-xl border border-border bg-card p-7 shadow-panel">
          <div className="mb-5 flex flex-wrap items-start justify-between gap-4">
            <div>
              <h2 className="text-lg font-semibold text-[#182d48]">Report sign-off</h2>
              <p className="mt-1 text-sm text-muted-foreground">Saved for this learner and month, then embedded in every downloaded PDF.</p>
              {signatureError && <p className="mt-2 text-xs text-destructive">{signatureError}</p>}
            </div>
            <div className="flex items-center gap-2">
              <Button
                type="button"
                disabled={!learnerSignature || !coachSignature || isSavingSignatures || signaturesSaved}
                onClick={handleSaveSignatures}
                className="min-w-36 bg-[#182d48] hover:bg-[#243f61]"
              >
                {isSavingSignatures ? <LoaderCircle className="h-4 w-4 animate-spin" /> : signaturesSaved ? <CheckCircle2 className="h-4 w-4" /> : <Save className="h-4 w-4" />}
                {isSavingSignatures ? "Saving..." : signaturesSaved ? "Saved" : "Save signatures"}
              </Button>
            </div>
          </div>
          <div className="grid gap-4 lg:grid-cols-2">
            <SignatureCapture label="Learner signature" signer={learner?.name ?? ""} value={learnerSignature} onChange={(value) => { setLearnerSignature(value); setLearnerSignatureSaved(false); }} onRemove={() => handleRemoveSignature("learner")} canRemove={learnerSignatureSaved} isRemoving={isSavingSignatures} />
            <SignatureCapture label="Coach signature" signer={learnerProfile.data?.coach.name ?? ""} value={coachSignature} onChange={(value) => { setCoachSignature(value); setCoachSignatureSaved(false); }} onRemove={() => handleRemoveSignature("coach")} canRemove={coachSignatureSaved} isRemoving={isSavingSignatures} />
          </div>
        </section>
      </main>
    </div>
  );
}
