// @ts-nocheck -- route search types are generated by the embedded app.
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import { ChevronLeft, ChevronRight, Database, FileText, Search } from "lucide-react";
import { Button } from "@/features/audit/learner-log-pro-copy/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/features/audit/learner-log-pro-copy/components/ui/table";
import { getActivityLearners, getAttendanceSession, getLearnerActivities } from "@/features/audit/learner-log-pro-copy/lib/api";

const pageSize = 20;

// Per-activity hours shown to 2 dp across the log tables.
function roundHours(value: number | null | undefined) {
  // Round to 2 dp (not whole hours — 2.5h must stay "2.5", not become "3"),
  // dropping any trailing zeros so 11.0 shows as "11".
  return value == null ? "—" : String(Math.round(value * 100) / 100);
}

export function MreTable({
  learner,
  component,
  attendanceKey,
}: {
  learner?: string;
  component?: string;
  attendanceKey?: string;
}) {
  const [search, setSearch] = useState("");
  const [page, setPage] = useState(0);
  // Three modes: a live session's attendees (attendanceKey), all learners on one
  // activity (component), or one learner's own records (default).
  const bySession = Boolean(attendanceKey);
  const byComponent = !bySession && Boolean(component);
  const singlePage = bySession || byComponent;
  const query = useQuery({
    queryKey: ["mre", learner, component, attendanceKey, search, page],
    queryFn: () =>
      bySession
        ? getAttendanceSession(attendanceKey as string)
        : byComponent
        ? getActivityLearners({ component: component as string, search })
        : getLearnerActivities({ learner, search, offset: page * pageSize, limit: pageSize }),
  });
  // The session endpoint returns every attendee at once (no server-side search),
  // so filter client-side to keep the search box working in that mode.
  const items = bySession && search.trim()
    ? (query.data?.items ?? []).filter((activity) =>
        activity.learner.toLowerCase().includes(search.trim().toLowerCase())
      )
    : query.data?.items ?? [];
  const totalPages = singlePage ? 1 : Math.max(1, Math.ceil((query.data?.total ?? 0) / pageSize));

  return (
    <section className="rounded-lg border border-border bg-card shadow-panel">
      <header className="flex flex-wrap items-end justify-between gap-4 border-b border-border px-7 py-5">
        <div>
          <div className="flex items-center gap-2">
            <Database className="h-4 w-4 text-success" aria-hidden />
            <h2 className="font-serif text-lg text-foreground">Learner activity records</h2>
          </div>
          <p className="mt-1 text-sm text-muted-foreground">
            {bySession
              ? "All learners who attended this live session, matched by session date + group."
              : byComponent
              ? "All learners who have this activity, with their own log entry on it."
              : learner
              ? `Live Neon activity records for ${learner}.`
              : "Student columns from Neon are converted into one real activity row per learner."}
          </p>
        </div>
        <label className="relative block w-full max-w-sm">
          <Search className="pointer-events-none absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" />
          <input
            value={search}
            onChange={(event) => {
              setSearch(event.target.value);
              setPage(0);
            }}
            placeholder="Search learner, plan or activity…"
            className="h-9 w-full rounded-md border border-border bg-background pl-9 pr-3 text-sm outline-none focus:border-primary"
          />
        </label>
      </header>

      {query.isError ? (
        <div className="px-7 py-10 text-center text-sm text-destructive">
          {query.error instanceof Error ? query.error.message : "The database API is unavailable."}
        </div>
      ) : (
        <div className="overflow-x-auto">
          <Table>
            <TableHeader>
              {/* A single "Time" column carrying the combined from–to value
                  (it'll later hold other kinds of value too). */}
              <TableRow className="hover:bg-transparent">
                <TableHead className="label-caps pl-7">Learner</TableHead>
                <TableHead className="label-caps">Plan ID</TableHead>
                <TableHead className="label-caps">Activity date</TableHead>
                <TableHead className="label-caps text-center">Time</TableHead>
                <TableHead className="label-caps">Category</TableHead>
                <TableHead className="label-caps">Activity</TableHead>
                <TableHead className="label-caps text-right">Planned</TableHead>
                <TableHead className="label-caps text-right">Actual</TableHead>
                <TableHead className="label-caps pr-7 text-right">Journal</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {query.isLoading && (
                <TableRow><TableCell colSpan={9} className="py-10 text-center text-sm text-muted-foreground">Loading learner data from Neon…</TableCell></TableRow>
              )}
              {items.map((activity) => (
                <TableRow key={activity.id}>
                  <TableCell className="pl-7 text-sm font-medium text-foreground">{activity.learner}</TableCell>
                  <TableCell className="font-mono text-xs text-foreground">{activity.plan_id}</TableCell>
                  <TableCell className="font-mono text-xs text-muted-foreground">{activity.learner_activity_date ?? "—"}</TableCell>
                  <TableCell className="whitespace-nowrap text-center font-mono text-xs text-muted-foreground">{activity.time_from_to ?? "—"}</TableCell>
                  <TableCell className="text-sm text-muted-foreground">{activity.activity_category}</TableCell>
                  <TableCell className="max-w-md text-sm text-foreground">
                    <Link
                      to="/activity"
                      search={{ learner: activity.learner.toLowerCase(), activity: activity.plan_id }}
                      className="font-medium hover:text-primary hover:underline"
                    >
                      {activity.activity_unit}
                    </Link>
                    {activity.activity_description && <span className="mt-0.5 block text-xs text-muted-foreground">{activity.activity_description}</span>}
                  </TableCell>
                  <TableCell className="text-right font-mono text-sm text-muted-foreground">{roundHours(activity.planned_hours)}</TableCell>
                  <TableCell className="text-right font-mono text-sm text-success">{roundHours(activity.actual_lms_hours)}</TableCell>
                  <TableCell className="pr-7 text-right">
                    <Button variant="outline" size="sm" asChild>
                      <Link
                        to="/journal"
                        search={{
                          learner: activity.learner.toLowerCase(),
                          period: activity.activity_period ?? "",
                        }}
                      >
                        <FileText className="mr-1.5 h-3.5 w-3.5" />
                        Open
                      </Link>
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
              {!query.isLoading && items.length === 0 && (
                <TableRow><TableCell colSpan={9} className="py-10 text-center text-sm text-muted-foreground">No learner activity records were returned by this database branch.</TableCell></TableRow>
              )}
            </TableBody>
          </Table>
        </div>
      )}

      <footer className="flex items-center justify-between border-t border-border px-7 py-4 text-xs text-muted-foreground">
        <span>{query.data ? `${bySession ? items.length : query.data.total} records` : "Connecting…"}</span>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="icon" disabled={page === 0} onClick={() => setPage((value) => value - 1)} aria-label="Previous page">
            <ChevronLeft className="h-4 w-4" />
          </Button>
          <span className="font-mono">{page + 1} / {totalPages}</span>
          <Button variant="outline" size="icon" disabled={page + 1 >= totalPages} onClick={() => setPage((value) => value + 1)} aria-label="Next page">
            <ChevronRight className="h-4 w-4" />
          </Button>
        </div>
      </footer>
    </section>
  );
}
