# Generated by Django 6.0.7 on 2026-08-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_column='Token_hash', max_length=64, unique=True)),
                ('email', models.TextField(db_column='Email')),
                ('expires_at', models.DateTimeField(db_column='Expires_at')),
                ('used_at', models.DateTimeField(blank=True, db_column='Used_at', null=True)),
                ('invited_by', models.TextField(blank=True, db_column='Invited_by', null=True)),
                ('sent_at', models.DateTimeField(blank=True, db_column='Sent_at', null=True)),
                ('send_error', models.TextField(blank=True, db_column='Send_error', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_at')),
                ('created_ip', models.TextField(blank=True, db_column='Created_ip', null=True)),
            ],
            options={
                'db_table': 'login"."Invitations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginAccount',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('subject_type', models.TextField(db_column='Subject_type')),
                ('subject_id', models.BigIntegerField(db_column='Subject_id')),
                ('email', models.TextField(db_column='Email')),
                ('display_name', models.TextField(blank=True, db_column='Display_name', null=True)),
                ('role', models.TextField(db_column='Role')),
                ('password_hash', models.TextField(blank=True, db_column='Password_hash', default='')),
                ('password_set_at', models.DateTimeField(blank=True, db_column='Password_set_at', null=True)),
                ('is_active', models.BooleanField(db_column='Is_active', default=True)),
                ('failed_attempts', models.IntegerField(db_column='Failed_attempts', default=0)),
                ('locked_until', models.DateTimeField(blank=True, db_column='Locked_until', null=True)),
                ('last_login_at', models.DateTimeField(blank=True, db_column='Last_login_at', null=True)),
                ('last_login_ip', models.TextField(blank=True, db_column='Last_login_ip', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Updated_at')),
            ],
            options={
                'db_table': 'login"."Login_accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginAudit',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('event', models.TextField(db_column='Event')),
                ('email', models.TextField(blank=True, db_column='Email', null=True)),
                ('account_id', models.BigIntegerField(blank=True, db_column='Account_id', null=True)),
                ('succeeded', models.BooleanField(db_column='Succeeded', default=False)),
                ('reason', models.TextField(blank=True, db_column='Reason', null=True)),
                ('ip_address', models.TextField(blank=True, db_column='Ip_address', null=True)),
                ('user_agent', models.TextField(blank=True, db_column='User_agent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_at')),
            ],
            options={
                'db_table': 'login"."Login_audit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_column='Token_hash', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_column='Expires_at')),
                ('revoked_at', models.DateTimeField(blank=True, db_column='Revoked_at', null=True)),
                ('ip_address', models.TextField(blank=True, db_column='Ip_address', null=True)),
                ('user_agent', models.TextField(blank=True, db_column='User_agent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_at')),
                ('last_seen_at', models.DateTimeField(blank=True, db_column='Last_seen_at', null=True)),
            ],
            options={
                'db_table': 'login"."Login_sessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_column='Token_hash', max_length=64, unique=True)),
                ('email', models.TextField(db_column='Email')),
                ('expires_at', models.DateTimeField(db_column='Expires_at')),
                ('used_at', models.DateTimeField(blank=True, db_column='Used_at', null=True)),
                ('sent_at', models.DateTimeField(blank=True, db_column='Sent_at', null=True)),
                ('send_error', models.TextField(blank=True, db_column='Send_error', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_at')),
                ('created_ip', models.TextField(blank=True, db_column='Created_ip', null=True)),
            ],
            options={
                'db_table': 'login"."Password_resets',
                'managed': False,
            },
        ),
    ]
