"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qsl, urlparse, unquote


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(path):
    if not path.exists():
        return

    # Real process-level environment variables keep priority. Microsoft calendar
    # credentials were historically appended more than once, so only for that
    # integration use the last file declaration. Other settings retain the
    # original first-declaration behaviour (several legacy DB aliases depend on it).
    process_environment_keys = set(os.environ)
    last_declaration_keys = {
        'MICROSOFT_CLIENT_ID', 'MICROSOFT_CLIENT_SECRET',
        'MICROSOFT_TENANT', 'MICROSOFT_TENANT_ID', 'MICROSOFT_CALLBACK_URI',
    }
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key not in process_environment_keys and key in last_declaration_keys:
            os.environ[key] = value
        else:
            os.environ.setdefault(key, value)


load_env_file(BASE_DIR / '.env')


DB_CONN_MAX_AGE = int(os.environ.get('DB_CONN_MAX_AGE', '300'))
DB_CONN_HEALTH_CHECKS = os.environ.get('DB_CONN_HEALTH_CHECKS', 'true').lower() != 'false'
# Seconds to wait for a database connection before giving up. Keeps a stalled DNS
# resolver or unreachable Neon endpoint from hanging a request indefinitely.
DB_CONNECT_TIMEOUT = int(os.environ.get('DB_CONNECT_TIMEOUT', '10'))


def database_from_url(database_url):
    parsed = urlparse(database_url)
    scheme = parsed.scheme.replace('postgresql', 'postgres')
    engine_by_scheme = {
        'postgres': 'django.db.backends.postgresql',
        'mysql': 'django.db.backends.mysql',
        'sqlite': 'django.db.backends.sqlite3',
    }

    if scheme not in engine_by_scheme:
        raise ValueError(f'Unsupported database scheme: {parsed.scheme}')

    if scheme == 'sqlite':
        return {
            'ENGINE': engine_by_scheme[scheme],
            'NAME': unquote(parsed.path.lstrip('/')) or BASE_DIR / 'db.sqlite3',
        }

    options = dict(parse_qsl(parsed.query))
    options.pop('channel_binding', None)
    # Bound how long a connection attempt can hang. Without it a stalled DNS
    # resolver leaves requests waiting on the OS default instead of failing fast.
    options.setdefault('connect_timeout', DB_CONNECT_TIMEOUT)
    return {
        'ENGINE': engine_by_scheme[scheme],
        'NAME': unquote(parsed.path.lstrip('/')),
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or '',
        'PORT': str(parsed.port or ''),
        'OPTIONS': options,
        'CONN_MAX_AGE': DB_CONN_MAX_AGE,
        'CONN_HEALTH_CHECKS': DB_CONN_HEALTH_CHECKS,
    }


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-suh%63q857hx@$cdjhxnj5t9@eh!$pemr!r0dc9*m5%2ey)1d_'

# SECURITY WARNING: don't run with debug turned on in production!
# Production-safe by default. Local development can opt back in with
# DJANGO_DEBUG=true in backend/.env.
DEBUG = os.environ.get("DJANGO_DEBUG", "false").lower() == "true"
USE_SQLITE_FOR_TESTS = os.environ.get("DJANGO_USE_SQLITE", "false").lower() == "true"
CHAT_DEMO_BOOTSTRAP_ENABLED = os.environ.get(
    "CHAT_DEMO_BOOTSTRAP_ENABLED",
    # The current frontend authentication is local/demo authentication and
    # therefore cannot create a Django session by itself. The deployed
    # frontend uses tightly scoped local demo identities and needs this
    # bridge until the main application login is replaced by real Django auth.
    "true",
).lower() == "true"

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
OPENAI_MODEL = os.environ.get("OPENAI_MODEL", "gpt-4.1-mini")
OPENAI_TRANSCRIPTION_MODEL = os.environ.get("OPENAI_TRANSCRIPTION_MODEL", "gpt-4o-mini-transcribe")
OPENAI_REFLECTION_MODEL = os.environ.get("OPENAI_REFLECTION_MODEL", "gpt-4o-mini")
OPENAI_MODERATION_MODEL = os.environ.get("OPENAI_MODERATION_MODEL", "omni-moderation-latest")
KBC_LMS_SCHEMA_URL = os.environ.get(
    "KBC_LMS_SCHEMA_URL",
    "https://kentbusinesscollege.org/wp-json/kbc-lms/v1/all-students-schema",
)
KBC_LMS_API_KEY = os.environ.get("KBC_LMS_API_KEY", "")

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,lms.kentbusinesscollege.net,api.kentbusinesscollege.net").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    # Daphne supplies Django's ASGI-aware runserver and the Channels WebSocket
    # test runtime. Keep it before django.contrib.staticfiles as recommended by
    # Channels so its runserver command takes precedence in development.
    'daphne',
    'quiz_api',
    'rest_framework',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'coach_api',
    'learner_api',
    'audit_api',
    'curriculum_api',
    'engagement_api',
    'enrolment_api',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Compress JSON/CSS/JS responses when the reverse proxy has not already done
    # so. Large curriculum payloads benefit substantially from this middleware.
    'django.middleware.gzip.GZipMiddleware',
    # Add ETag/Last-Modified handling so unchanged API/static responses can be
    # answered with a small 304 response instead of being downloaded again.
    'django.middleware.http.ConditionalGetMiddleware',
    'config.cors.ChatCorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'config.performance.PerformanceTimingMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

PERFORMANCE_DIAGNOSTICS = os.environ.get('PERFORMANCE_DIAGNOSTICS', 'false').lower() == 'true'
SLOW_REQUEST_THRESHOLD_MS = int(os.environ.get('SLOW_REQUEST_THRESHOLD_MS', '750'))

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# DRF is used by the chat API. Session authentication keeps it compatible with
# Django's existing browser login flow; projects using another auth mechanism
# can add it here without changing chat permissions.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
    ),
}

# Redis is used only as the Channels transport. Chat history and read state are
# always persisted in PostgreSQL (or the configured Django default database).
CHAT_REDIS_URL = (
    os.environ.get('CHAT_REDIS_URL')
    or os.environ.get('REDIS_URL')
    or 'redis://127.0.0.1:6379/1'
)
if USE_SQLITE_FOR_TESTS:
    # Unit tests must be isolated and deterministic: WebSocket tests should not
    # require a developer Redis process or spend seconds waiting for a refused
    # connection. Production and normal development continue to use Redis.
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [CHAT_REDIS_URL],
            },
        },
    }


# Share expensive curriculum payloads between Django workers in production.
# Django's built-in Redis backend uses the already-installed ``redis`` package,
# so no additional cache dependency is required. Development and tests retain a
# process-local cache when no Redis URL is configured.
CACHE_URL = os.environ.get('CACHE_URL') or os.environ.get('REDIS_URL')
if CACHE_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': CACHE_URL,
            'KEY_PREFIX': os.environ.get('CACHE_KEY_PREFIX', 'kbc-lms'),
            'TIMEOUT': int(os.environ.get('CACHE_DEFAULT_TIMEOUT', '300')),
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'kbc-lms-local-cache',
            'TIMEOUT': 300,
        }
    }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = (
    os.environ.get("DATABASE_URL")
    or os.environ.get("DATABASEURL")
    or os.environ.get("Database_url")
)
# The production migration histories for these apps intentionally manipulate
# PostgreSQL schemas and externally managed tables. SQLite cannot execute that
# DDL. In isolated tests, skip those historical migrations and let Django's test
# runner create the current managed models directly (``--run-syncdb`` is enabled
# automatically for apps without migrations). Production keeps the complete,
# already-applied migration graph unchanged.
CHAT_TEST_MODE = USE_SQLITE_FOR_TESTS
COACH_TEST_MODE = USE_SQLITE_FOR_TESTS
if USE_SQLITE_FOR_TESTS:
    MIGRATION_MODULES = {
        'chat': None,
        'coach_api': None,
    }
    # Password strength is not under test in these suites. A fast hasher keeps
    # tests that create many authenticated chat users from spending most of
    # their runtime in PBKDF2 while production retains the secure defaults.
    PASSWORD_HASHERS = [
        'django.contrib.auth.hashers.MD5PasswordHasher',
    ]

if DATABASE_URL and not USE_SQLITE_FOR_TESTS:
    parsed_db = urlparse(DATABASE_URL)
    db_options = dict(parse_qsl(parsed_db.query))
    db_options.setdefault("connect_timeout", DB_CONNECT_TIMEOUT)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": parsed_db.path.lstrip("/"),
            "USER": parsed_db.username,
            "PASSWORD": parsed_db.password,
            "HOST": parsed_db.hostname,
            "PORT": parsed_db.port or "5432",
            "OPTIONS": db_options,
            "CONN_MAX_AGE": DB_CONN_MAX_AGE,
            "CONN_HEALTH_CHECKS": DB_CONN_HEALTH_CHECKS,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Enrolment (Neon) database used by the learner_api app via EnrolmentRouter.
_enrolment_database_url = (
    os.environ.get('ENROLMENT_DATABASE_URL')
    or os.environ.get('Database_url')
    or os.environ.get('DATABASEURL')
    or os.environ.get('DATABASE_URL')
)
if _enrolment_database_url and not USE_SQLITE_FOR_TESTS:
    DATABASES['enrolment'] = database_from_url(_enrolment_database_url)

# Learner Log Pro reads Audit.mre from its own Neon branch. Keeping it on a
# separate alias prevents the imported audit workspace from changing the LMS's
# primary database connection.
_audit_database_url = os.environ.get('AUDIT_DATABASE_URL')
if _audit_database_url and not USE_SQLITE_FOR_TESTS:
    DATABASES['audit'] = database_from_url(_audit_database_url)

DATABASE_ROUTERS = ['learner_api.routers.EnrolmentRouter']

# CORS/CSRF: the Vite dev server (port 3000) proxies /learner_api to this server, so
# requests are same-origin in the browser. Allow the dev hosts explicitly.
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:3001',
    'http://127.0.0.1:3001',
    'https://lms.kentbusinesscollege.net',
    'https://api.kentbusinesscollege.net',
]


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Uploaded media (quiz packages, extracted SCORM runtime, etc.). FileField's
# upload_to is relative to MEDIA_ROOT; without this it defaults to '' and the
# SCORM runtime extraction path (MEDIA_ROOT / 'scorm_runtime') breaks.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Azure Blob Storage (learner evidence uploads — see learner_api/evidence_storage.py).
AZURE_STORAGE_ACCOUNT = os.environ.get("AZURE_STORAGE_ACCOUNT", "")
AZURE_STORAGE_KEY = os.environ.get("AZURE_STORAGE_KEY", "")
AZURE_QUARANTINE_CONTAINER = os.environ.get("AZURE_QUARANTINE_CONTAINER", "evidence-quarantine")
AZURE_APPROVED_CONTAINER = os.environ.get("AZURE_APPROVED_CONTAINER", "evidence-approved")
AZURE_REJECTED_CONTAINER = os.environ.get("AZURE_REJECTED_CONTAINER", "evidence-rejected")
AZURE_SAS_TTL_MINUTES = int(os.environ.get("AZURE_SAS_TTL_MINUTES", "15"))

# Generated/signed enrolment paperwork (ILR and the other compliance documents)
# — see enrolment_api/documents.py. Separate from the evidence containers: these
# are produced by the platform, not uploaded by learners, so they need no
# quarantine/scan step and are written straight to their own container.
AZURE_ENROLMENT_DOCS_CONTAINER = os.environ.get("AZURE_Enrolment_Docs_CONTAINER", "enrolment-docs")

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'curriculum_api': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}
