import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowRight, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, Clock3, GraduationCap, Headphones, Layers3, RefreshCw, TrendingUp, Users, Video } from 'lucide-react';
import { WorkspaceShell } from '@/components/feature/WorkspaceShell';
import { PageContainer } from '@/components/ui/PageContainer';
import { roleNavMap } from '@/mocks/navigation';
import { useResolvedLearner } from '@/hooks/useMyLearner';
import { useLearnerDetailParam } from '@/hooks/useLearnerDetailParam';
import { fetchTrainingPlanDashboard, type TrainingPlanDashboard, type PlanSession } from '@/api/trainingPlanDashboard';
import { fetchStudentActivity, type StudentActivityResponse } from '@/api/studentActivity';
import { subjectsFrom, useSubjectMetadata, type Subject } from '../my-learning/SubjectWorkspace';
import { barPosition, buildPlanModules, monthMetrics, nextSession, percent, reviewDate, reviewToBook, sessionDay, timelineYears, uniquePlanSessions, type TimelineModule } from './model';
import styles from './trainingPlan.module.css';

const nav = roleNavMap.learner;
const palette = ['violet', 'green', 'amber', 'blue', 'pink'];
const monthNames = Array.from({ length: 12 }, (_, i) => new Date(2024, i, 1).toLocaleDateString('en-GB', { month: 'short' }));
const hours = (value: number | null | undefined) => value == null ? '—' : `${Number(value.toFixed(2))}`;
const dateLabel = (value: string) => value ? new Date(`${value.slice(0, 10)}T12:00:00Z`).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', ...(Number(value.slice(0, 4)) !== new Date().getFullYear() ? { year: 'numeric' as const } : {}) }) : 'Dates coming soon';
const monthLabel = (value: string) => new Date(`${value}-01T12:00:00Z`).toLocaleDateString('en-GB', { month: 'long', year: 'numeric' });
const sessionTime = (value: string) => new Date(value).toLocaleString('en-GB', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit', timeZone: 'Europe/London' });
function Meter({ value, label }: { value: number | null; label: string }) {
  return <div role="progressbar" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={value ?? undefined} className={styles.meter}><span style={{ width: `${value ?? 0}%` }} /></div>;
}
function State({ value }: { value: string }) {
  return <span className={`${styles.state} ${['Completed', 'Attended'].includes(value) ? styles.positive : ['Not attended', 'Overdue'].includes(value) ? styles.warning : ''}`}>{value}</span>;
}
function moduleStatus(module: TimelineModule) { return module.activities.length && module.done === module.activities.length ? 'Completed' : module.done ? 'In progress' : 'Not started'; }

export function TrainingPlanBoard({ data, subjects, kind, learnerId, onRefresh }: {
  data: TrainingPlanDashboard; subjects: Subject[]; kind: string; learnerId: string; onRefresh: () => void;
}) {
  const modules = useMemo(() => buildPlanModules(subjects, data), [subjects, data]);
  const [now, setNow] = useState(Date.now);
  useEffect(() => {
    const timer = window.setInterval(() => setNow(Date.now()), 30_000);
    return () => window.clearInterval(timer);
  }, []);
  const today = new Date(now).toLocaleDateString('en-CA', { timeZone: 'Europe/London' });
  const thisMonth = today.slice(0, 7);
  const [selectedMonth, setSelectedMonth] = useState(thisMonth);
  const [selectedId, setSelectedId] = useState('');
  const [filter, setFilter] = useState('all');
  const year = Number(selectedMonth.slice(0, 4));
  const sourceDates = [...Object.keys(data.months), ...data.actual.map(row => row.month), ...data.reviews.map(reviewDate), ...modules.flatMap(m => [m.start, m.end])];
  const years = timelineYears(sourceDates.map(date => date.length === 7 ? `${date}-01` : date), Number(today.slice(0, 4)), year);
  const activeModules = modules.filter(module => !module.start || (module.start < `${year + 1}-01-01` && module.end >= `${year}-01-01`));
  const selected = modules.find(module => module.id === selectedId) || modules.find(module => module.start && module.start.slice(0, 7) <= selectedMonth && module.end.slice(0, 7) >= selectedMonth);
  const sessions = uniquePlanSessions(modules);
  const next = nextSession(sessions, now);
  const currentMetrics = monthMetrics(thisMonth, modules, data), metrics = monthMetrics(selectedMonth, modules, data);
  const month = data.months[selectedMonth];
  const total = modules.reduce((sum, module) => sum + module.activities.length, 0), done = modules.reduce((sum, module) => sum + module.done, 0), overall = percent(done, total);
  const monthSessions = sessions.filter(session => sessionDay(session.start).startsWith(selectedMonth));
  const reviews = data.reviews.filter(review => review.source !== 'student-support' && review.status !== 'cancelled').sort((a, b) => reviewDate(a).localeCompare(reviewDate(b)));
  const dueReview = reviewToBook(reviews);
  const periodReviews = selected?.start && selected.end ? reviews.filter(review => reviewDate(review) >= selected.start && reviewDate(review) <= selected.end) : reviews.filter(review => reviewDate(review).startsWith(selectedMonth));
  const selectedNext = selected ? nextSession(selected.sessions, now) : null;
  const reviewDays = [...new Set(reviews.map(reviewDate).filter(date => date.startsWith(String(year))))].map(date => ({ date, items: reviews.filter(review => reviewDate(review) === date) }));
  const subjectHref = (id: string) => `/learner/modules/${kind}/${learnerId}?subject=${encodeURIComponent(id)}`;
  const learnerQuery = `kind=${encodeURIComponent(kind)}&learner=${encodeURIComponent(learnerId)}`;
  const calendarHref = (event?: string) => `/learner/calendar?${learnerQuery}${event ? `&event=${encodeURIComponent(event)}` : ''}`;
  const selectMonth = (key: string) => { setSelectedMonth(key); setSelectedId(''); };
  const shiftMonth = (step: number) => { const date = new Date(`${selectedMonth}-01T12:00:00Z`); date.setUTCMonth(date.getUTCMonth() + step); selectMonth(date.toISOString().slice(0, 7)); };
  const sessionStatus = (session: PlanSession) => session.attended === true ? 'Attended' : session.attended === false ? 'Not attended' : Date.parse(session.start) > now ? 'Scheduled' : 'Attendance pending';
  const reviewStatus = (review: typeof reviews[number]) => ({ completed: 'Completed', scheduled: review.invited === false ? 'Booking pending' : 'Booked', 'not-scheduled': reviewDate(review) < today ? 'Overdue' : 'Not booked', 'awaiting-signature': 'Awaiting signatures', 'in-progress': 'In progress' }[review.status] || 'Not booked');
  const visibleSessions = monthSessions.filter(session => filter !== 'completed' || session.attended === true).filter(session => filter !== 'pending' || session.attended !== true);
  return <div className={styles.root}>
    <header className={styles.heading}><div><span className={styles.eyebrow}>Your learning journey</span><h1>My Training Plan</h1><p>Your modules, study hours and coaching, all in one place.</p></div><div className={styles.headerActions}>{data.coach.bookingUrl && <a href={data.coach.bookingUrl} target="_blank" rel="noopener noreferrer" className={styles.secondary}><Headphones size={16} />Support session<ArrowRight size={15} /></a>}<button className={styles.iconButton} onClick={onRefresh} aria-label="Refresh training plan"><RefreshCw size={17} /></button></div></header>
    <section className={styles.highlights} aria-label="Training plan summary">
      <article className={`${styles.highlight} ${styles.next}`}><span className={styles.tile}><CalendarDays size={21} /></span><div><p className={styles.kicker}>Next up</p><h2>{next?.title || 'Your next live session'}</h2><p className={styles.hint}>{next ? `${sessionTime(next.start)} · UK time · ${next.minutes} min` : 'Coming soon — your session will appear once scheduled.'}</p></div>{next?.joinUrl ? <a className={styles.primary} href={next.joinUrl} target="_blank" rel="noopener noreferrer">Join live session<ArrowRight size={16} /></a> : next ? <Link className={styles.primary} to={subjectHref(modules.find(m => m.moduleId === next.moduleId)?.id || '')}>View module<ArrowRight size={16} /></Link> : <span className={styles.soon}>Coming soon</span>}</article>
      <article className={`${styles.highlight} ${styles.reviewHighlight}`}><span className={styles.tile}><Users size={21} /></span><div><p className={styles.kicker}>Review to book</p><h2>{dueReview ? `${dueReview.title}${dueReview.sequence ? ` ${dueReview.sequence}` : ''}` : 'Your coaching reviews'}</h2><p className={styles.hint}>{dueReview ? `Due ${dateLabel(reviewDate(dueReview))}${(dueReview.coachName || data.coach.name) ? ` · ${dueReview.coachName || data.coach.name}` : ''}` : 'Your next review will appear when it is planned.'}</p></div>{dueReview ? <Link className={styles.primary} to={calendarHref(dueReview.eventKey)}>Book review<ArrowRight size={16} /></Link> : data.coach.bookingUrl ? <a className={styles.primary} href={data.coach.bookingUrl} target="_blank" rel="noopener noreferrer">Book a support session<ArrowRight size={16} /></a> : <span className={styles.soon}>Coming soon</span>}</article>
      <article className={`${styles.highlight} ${styles.hoursHighlight}`}><span className={styles.tile}><Clock3 size={21} /></span><div><p className={styles.kicker}>This month's study hours</p><h2>{hours(currentMetrics.actual)} <small>/ {hours(currentMetrics.planned)} hrs</small></h2><p className={styles.hint}>{monthLabel(thisMonth)}</p></div><div className={styles.highlightFooter}><Meter value={currentMetrics.progress} label="This month's study hours" /><p>{hours(currentMetrics.remaining)} hrs remaining · {hours(currentMetrics.weekly)} hrs / week</p></div></article>
      <article className={`${styles.highlight} ${styles.progressHighlight}`}><span className={styles.tile}><TrendingUp size={21} /></span><div><p className={styles.kicker}>Overall progress</p><h2>{overall}<small>%</small></h2><p className={styles.hint}>{done} of {total} activities completed</p></div><div className={styles.highlightFooter}><Meter value={overall} label="Overall activity progress" /><p>{modules.filter(m => moduleStatus(m) === 'Completed').length} of {modules.length} modules completed</p></div></article>
    </section>
    <section className={styles.timeline} aria-label="Module timeline"><div className={styles.toolbar}><div className={styles.controls}><label>Year<select aria-label="Timeline year" value={year} onChange={event => selectMonth(`${event.target.value}-${selectedMonth.slice(5)}`)}>{years.map(y => <option key={y}>{y}</option>)}</select></label><button className={styles.secondary} onClick={() => selectMonth(thisMonth)}>Today</button></div><div className={styles.legend}><span><i className={styles.durationKey} />Module duration</span><span><i className={styles.todayKey} />Today</span><span><CheckCircle2 size={13} />Completed</span></div><label className={styles.jump}>Jump to<select aria-label="Jump to month" value={selectedMonth} onChange={event => selectMonth(event.target.value)}>{monthNames.map((name, index) => { const key = `${year}-${String(index + 1).padStart(2, '0')}`; return <option key={key} value={key}>{name} {year}{data.months[key]?.topics[0] ? ` — ${data.months[key].topics[0]}` : ''}</option>; })}</select></label></div>
      <div className={styles.timelineScroll} tabIndex={0} aria-label="Scroll module timeline"><div className={styles.timelineGrid}><div className={styles.timelineHeader}><div className={styles.moduleHeading}>Modules <span>{activeModules.length}</span></div><div className={styles.months}>{monthNames.map((name, index) => { const key = `${year}-${String(index + 1).padStart(2, '0')}`; return <button key={key} className={key === selectedMonth ? styles.selectedMonth : ''} onClick={() => selectMonth(key)} aria-label={`${monthLabel(key)}${data.months[key]?.topics[0] ? ` — ${data.months[key].topics[0]}` : ''}`} aria-pressed={key === selectedMonth}><strong>{name}</strong><span title={data.months[key]?.topics.join(' · ')}>{data.months[key]?.topics[0] || ''}</span></button>; })}</div></div>
        {activeModules.length ? activeModules.map((module, index) => { const position = barPosition(module.start, module.end, year); return <div key={module.id} className={`${styles.timelineRow} ${module.id === selected?.id ? styles.selectedRow : ''}`}><div className={styles.moduleLabel}><i className={`${styles.dot} ${styles[palette[index % palette.length]]}`} /><div><Link to={subjectHref(module.id)}>{module.title}</Link><p>{module.weeks || '—'} weeks · {module.sessions.length} live sessions</p><div className={styles.rowProgress}><Meter value={module.progress} label={`${module.title} activity progress`} /><span>{module.progress}%</span></div></div></div><div className={styles.track}>{monthNames.map((_, i) => <div key={i} className={`${styles.monthCell} ${selectedMonth === `${year}-${String(i + 1).padStart(2, '0')}` ? styles.selectedCell : ''}`} />)}{position ? <button className={`${styles.moduleBar} ${styles[palette[index % palette.length]]}`} style={{ left: `${position.left}%`, width: `${position.width}%` }} onClick={() => { setSelectedId(module.id); if (selectedMonth < module.start.slice(0, 7) || selectedMonth > module.end.slice(0, 7)) setSelectedMonth(module.start.slice(0, 7)); }} aria-label={`Show ${module.title} overview`} aria-pressed={module.id === selected?.id}><span className={styles.barFill} style={{ width: `${module.progress}%` }} /><span className={styles.barText}>{dateLabel(module.start)} – {dateLabel(module.end)}<small>{module.weeks || '—'} weeks · {module.sessions.length} sessions</small></span>{moduleStatus(module) === 'Completed' && <CheckCircle2 size={16} />}</button> : <button type="button" className={styles.noDates} onClick={() => setSelectedId(module.id)} aria-label={`Show ${module.title} overview`} aria-pressed={module.id === selected?.id}>Schedule coming soon · View overview<ArrowRight size={12} /></button>}{Number(today.slice(0, 4)) === year && <span className={styles.todayLine} style={{ left: `${barPosition(today, today, year)?.left || 0}%` }} />}</div></div>; }) : <p className={styles.empty}>No modules are scheduled for this year.</p>}
        {!!reviewDays.length && <div className={`${styles.timelineRow} ${styles.reviewTimeline}`}><div className={styles.moduleLabel}><CalendarDays size={17} /><div><strong>Coaching reviews</strong><p>{reviewDays.reduce((sum, day) => sum + day.items.length, 0)} reviews this year</p></div></div><div className={styles.track}>{monthNames.map((_, i) => <div key={i} className={styles.monthCell} />)}{reviewDays.map(day => <Link key={day.date} className={`${styles.reviewMarker} ${day.items.every(review => review.status === 'completed') ? styles.positive : ''}`} to={calendarHref(day.items[0].eventKey)} style={{ left: `${barPosition(day.date, day.date, year)?.left || 0}%` }} aria-label={`${day.items.map(review => review.title).join(', ')} on ${dateLabel(day.date)}`} title={`${dateLabel(day.date)} · ${day.items.map(review => `${review.title}: ${reviewStatus(review)}`).join(' · ')}`}><CalendarDays size={14} />{day.items.length > 1 && <small>{day.items.length}</small>}</Link>)}</div></div>}
      </div></div>
    </section>
    <div className={styles.details}>
      <section className={styles.panel} aria-label="Monthly study plan"><div className={styles.panelHeading}><div><p className={styles.eyebrow}>Monthly focus</p><h2>{monthLabel(selectedMonth)}</h2></div><div className={styles.controls}><button className={styles.iconButton} onClick={() => shiftMonth(-1)} aria-label="Previous month"><ChevronLeft size={16} /></button><button className={styles.iconButton} onClick={() => shiftMonth(1)} aria-label="Next month"><ChevronRight size={16} /></button></div></div>{!!month?.topics.length && <p className={styles.focusTitle}>{month.topics.join(' · ')}</p>}
        <div className={styles.monthStats}>{[['Planned', metrics.planned], ['Completed', metrics.actual], ['Remaining', metrics.remaining], ['Weekly target', metrics.weekly]].map(([label, value]) => <div key={String(label)}><span>{label}</span><strong>{hours(value as number | null)} <small>hrs</small></strong></div>)}</div><div className={styles.listHeading}><span>{monthSessions.length} live sessions this month</span><select aria-label="Filter monthly sessions" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All sessions</option><option value="completed">Attended</option><option value="pending">Pending</option></select></div>
        <div className={styles.sessionList}>{visibleSessions.length ? visibleSessions.map(session => { const module = modules.find(m => m.moduleId === session.moduleId); return <article key={session.id} className={styles.session}><div className={styles.sessionTitle}><Video size={16} /><strong>{session.title}</strong><State value={sessionStatus(session)} /></div><p>{sessionTime(session.start)} · UK time · {session.minutes} min</p><div className={styles.sessionActions}>{module && <Link to={subjectHref(module.id)}>View session materials<ArrowRight size={14} /></Link>}{session.joinUrl && Date.parse(session.start) > now && <a href={session.joinUrl} target="_blank" rel="noopener noreferrer">Join Teams</a>}</div></article>; }) : <p className={styles.empty}>No {filter === 'all' ? '' : `${filter} `}live sessions to show this month.</p>}</div>
        {selected && <Link className={styles.textLink} to={subjectHref(selected.id)}>View activities in {selected.title}<ArrowRight size={14} /></Link>}
      </section>
      <section className={styles.panel} aria-label="Reviews this period"><div className={styles.panelHeading}><div><p className={styles.eyebrow}>Your coaching</p><h2>Reviews this period</h2></div><Users size={20} /></div><p className={styles.hint}>{periodReviews.filter(r => r.status === 'completed').length} of {periodReviews.length} completed{selected?.start ? ` · ${dateLabel(selected.start)} – ${dateLabel(selected.end)}` : ''}</p><div className={styles.reviewList}>{periodReviews.length ? periodReviews.map(review => <article className={styles.review} key={review.eventKey}><span className={styles.reviewIcon}>{review.status === 'completed' ? <CheckCircle2 size={18} /> : <CalendarDays size={18} />}</span><div><h3>{review.title}{review.sequence ? ` ${review.sequence}` : ''}</h3><p>{dateLabel(reviewDate(review))}{review.scheduledTime ? ` · ${review.scheduledTime.slice(0, 5)}` : ''}</p><State value={reviewStatus(review)} /></div><Link className={styles.reviewAction} to={calendarHref(review.eventKey)}>{review.status === 'completed' ? 'View' : review.status === 'not-scheduled' ? 'Book now' : 'View booking'}<ArrowRight size={13} /></Link></article>) : <p className={styles.empty}>Your reviews will appear here once planned.</p>}</div><Link className={styles.textLink} to={`/learner/progress-reviews?${learnerQuery}`}>View all your reviews<ArrowRight size={15} /></Link><div className={styles.support}><Headphones size={20} /><div><h3>Need a little support?</h3><p>{data.coach.name ? `Book a session with ${data.coach.name}.` : 'Your coach booking link will appear here once available.'}</p>{data.coach.bookingUrl && <a href={data.coach.bookingUrl} target="_blank" rel="noopener noreferrer">Book a support session<ArrowRight size={14} /></a>}</div></div></section>
      <section className={styles.panel} aria-label="Module overview"><div className={styles.panelHeading}><div><p className={styles.eyebrow}>In focus</p><h2>Module overview</h2></div>{selected && <Link className={styles.primary} to={subjectHref(selected.id)}>Go to module<ArrowRight size={15} /></Link>}</div>{selected ? <><h3 className={styles.overviewTitle}>{selected.title}</h3><State value={moduleStatus(selected)} />{selected.detail?.description && <p className={styles.description}>{selected.detail.description}</p>}<dl className={styles.overviewStats}><div><CalendarDays size={18} /><dt>Teaching weeks</dt><dd>{selected.weeks || '—'}<small>{selected.start ? `${dateLabel(selected.start)} – ${dateLabel(selected.end)}` : 'Schedule coming soon'}</small></dd></div><div><Layers3 size={18} /><dt>Live sessions</dt><dd>{selected.sessions.length}<small>{selected.sessions.filter(s => s.attended === true).length} attended</small></dd></div><div><Clock3 size={18} /><dt>Hours recorded</dt><dd>{hours(selected.actual)}<small>Accepted study hours</small></dd></div><div><Users size={18} /><dt>Coach</dt><dd>{data.coach.name || 'To be assigned'}</dd></div><div><GraduationCap size={18} /><dt>Tutor</dt><dd>{selected.detail?.tutor_name || 'To be assigned'}</dd></div><div><Video size={18} /><dt>Next session</dt><dd>{selectedNext ? sessionTime(selectedNext.start) : 'Coming soon'}</dd></div></dl><div className={styles.overviewProgress}><div><span>Activity progress</span><strong>{selected.progress}%</strong></div><Meter value={selected.progress} label="Selected module progress" /><p>{selected.done} of {selected.activities.length} activities completed</p></div></> : <p className={styles.empty}>{modules.length ? 'Choose a module on the timeline to see its details.' : 'Your modules will appear when they are assigned.'}</p>}</section>
    </div>
  </div>;
}

export default function TrainingPlanTimelinePage() {
  const params = useParams<{ kind?: string; id?: string }>();
  const { kind, id } = useResolvedLearner(params.kind, params.id);
  const { real, loading, loadError, refresh } = useLearnerDetailParam(kind, id, true);
  const identity = `${kind}:${id}`;
  const [attempt, setAttempt] = useState(0);
  const [state, setState] = useState<{ identity: string; data: TrainingPlanDashboard | null; activity: StudentActivityResponse | null; error: string } | null>(null);
  useEffect(() => {
    if (!kind || !id || !real) return;
    const controller = new AbortController();
    setState(null);
    void Promise.all([fetchTrainingPlanDashboard(kind, id, controller.signal), real.studentActivityAvailable ? fetchStudentActivity(kind, id, controller.signal) : Promise.resolve(null)])
      .then(([data, activity]) => { if (!controller.signal.aborted) setState({ identity, data, activity, error: '' }); })
      .catch(error => { if (!controller.signal.aborted) setState({ identity, data: null, activity: null, error: error instanceof Error ? error.message : 'Could not load your training plan.' }); });
    return () => controller.abort();
  }, [kind, id, identity, real, attempt]);
  const current = state?.identity === identity ? state : null;
  const { metadata, error: metadataError, retry } = useSubjectMetadata(current?.activity || null, real, kind, id, !!current?.data);
  const subjects = useMemo(() => subjectsFrom(current?.activity || null, real, metadata), [current?.activity, real, metadata]);
  const error = loadError || current?.error || metadataError;
  const reload = () => { setAttempt(a => a + 1); retry(); refresh(); };
  return <WorkspaceShell role="learner" roleLabel={nav.label} navItems={nav.items} workspaceLabel={nav.workspaceLabel} pageTitle="Training plan" pageSubtitle={real?.programme || ''} userName={real?.name || 'Learner'} userRole="Learner"><PageContainer>{error ? <div role="alert" className={styles.error}><h1>Could not load your training plan</h1><p>{error}</p><button onClick={reload} className={styles.primary}>Try again</button></div> : loading || !current?.data || !metadata ? <div role="status" className={styles.loading}><CalendarDays size={30} /><h1>Loading your training plan</h1><p>Getting your modules, schedule and study hours…</p></div> : <TrainingPlanBoard key={identity} data={current.data} subjects={subjects} kind={kind!} learnerId={id!} onRefresh={reload} />}</PageContainer></WorkspaceShell>;
}
