# Generated by Django 6.0.6 on 2026-07-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereceipt',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
