# Generated by Django 6.0.7 on 2026-08-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActualHoursReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'actual hours review',
                'permissions': [('propose_actual_hours', 'Can propose Learner Journal actual hours'), ('approve_actual_hours', 'Can approve or reject proposed actual hours')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MreActivity',
            fields=[
                ('plan_id', models.TextField(primary_key=True, serialize=False)),
                ('month_no', models.IntegerField()),
                ('month_unit', models.TextField()),
                ('unit_planned_date', models.DateField()),
                ('activity_date', models.DateField(null=True)),
                ('week_sequence', models.TextField()),
                ('activity_category', models.TextField()),
                ('activity_unit', models.TextField()),
                ('activity_description', models.TextField()),
                ('delivery_method', models.TextField()),
                ('planned_hours', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('key_ksbs', models.TextField(null=True)),
                ('expected_evidence', models.TextField(null=True)),
                ('source_course', models.TextField(null=True)),
                ('source_url', models.TextField(null=True)),
                ('source_basis', models.TextField(null=True)),
                ('ibrahim_actual_lms_hours', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('aya_actual_lms_hours', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('huda_actual_lms_hours', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('ibrahim_activity_date', models.DateField(null=True)),
                ('aya_activity_date', models.DateField(null=True)),
                ('huda_activity_date', models.DateField(null=True)),
                ('ibrahim_time_stamp_from_to', models.TextField(null=True)),
                ('aya_time_stamp_from_to', models.TextField(null=True)),
                ('huda_time_stamp_from_to', models.TextField(null=True)),
            ],
            options={
                'db_table': '"Audit"."mre"',
                'ordering': ['month_no', 'unit_planned_date', 'plan_id'],
                'managed': False,
            },
        ),
    ]
