-- Curriculum usage trail: who opened which page, when, and what they did there.
--
-- Why the table is needed
-- -----------------------
-- curriculum.record_revisions answers "what changed" -- it is written by the
-- save helpers, so it only ever sees a write. It cannot see somebody open the
-- module builder, read a cohort and leave, because nothing about that touches a
-- record. The Audit Trail's People view needs that reading half, so it has to
-- be recorded rather than derived, and this is where it lands.
--
-- Written by backend/curriculum_api/activity.py (curriculum_activity_record),
-- read by the same module's people/person endpoints.
--
-- Until this statement has run, the recorder answers `available: false`, drops
-- every event quietly, and the page says plainly that page opens are not being
-- recorded yet. Nothing else in the LMS depends on this table, and no existing
-- behaviour changes when it appears.
--
-- What it does NOT contain
-- ------------------------
-- No page content, no payloads, no tokens, no learner records. `detail` is an
-- allowlist of nine short descriptive fields (search term, filter name, export
-- format, file name, ...) enforced server-side in activity.clean_detail, each
-- truncated; anything else the browser sends is dropped before the insert.
--
-- Retention
-- ---------
-- Every read is windowed (default 30 days, 365 maximum), so rows older than a
-- year are never shown. They are not deleted automatically: pruning is the
-- owner's decision, and the prune statement is at the bottom of this file,
-- commented out, rather than run as a side effect of provisioning.

CREATE TABLE IF NOT EXISTS curriculum.activity_events (
    id              bigserial     PRIMARY KEY,

    -- When it happened, and when we were told. The browser's stamp is accepted
    -- only when it is recent and not in the future (activity.parse_client_stamp),
    -- so a queue flushed after a laptop woke up keeps its real order; anything
    -- else falls back to the server clock. recorded_at is always ours, so the
    -- two can be compared when a row looks wrong.
    occurred_at     timestamptz   NOT NULL DEFAULT now(),
    recorded_at     timestamptz   NOT NULL DEFAULT now(),

    -- Who, taken from the session on the server and never from the request
    -- body. Denormalised the way login."Login_audit" is: the name and role as
    -- they were at the time, so a later rename does not rewrite history, and a
    -- deleted account does not erase the record that it was here.
    actor_email     text          NOT NULL,
    actor_name      text          NOT NULL DEFAULT '',
    actor_role      text          NOT NULL DEFAULT '',
    account_id      bigint,

    -- One sitting in one browser tab. Generated by the browser and used only to
    -- group this person's own rows, so a guessed value can reorder nothing that
    -- is not already theirs.
    visit_id        text          NOT NULL DEFAULT '',

    -- 'page_view' or one of the read actions: search, filter, sort, export,
    -- download, record_view, tab, print. Writes are deliberately absent -- a
    -- save is recorded by the write helper with a before and an after, and
    -- taking the client's word for one would put an unverified edit in the
    -- audit trail. Constrained here as well as in Python so a future caller
    -- cannot quietly widen the vocabulary.
    kind            text          NOT NULL,
    CONSTRAINT activity_events_kind_check CHECK (kind IN (
        'page_view', 'search', 'filter', 'sort', 'export',
        'download', 'record_view', 'tab', 'print'
    )),

    -- The SPA route, and the page it resolves to. Both are the server's own
    -- reading of the URL (activity.resolve_page), not a client-supplied label.
    path            text          NOT NULL DEFAULT '',
    page_key        text          NOT NULL DEFAULT '',
    page_label      text          NOT NULL DEFAULT '',

    -- The record the page or action was about. The id comes from the URL where
    -- the route has one; the label is display text from the client and is
    -- treated as such -- it is never matched on.
    target_type     text          NOT NULL DEFAULT '',
    target_id       text          NOT NULL DEFAULT '',
    target_label    text          NOT NULL DEFAULT '',

    detail          jsonb         NOT NULL DEFAULT '{}'::jsonb,

    -- How long the page stayed open. Null on arrival, filled in by an UPDATE
    -- when the page is navigated away from -- there is one row per page opened,
    -- not one per arrival plus one per departure. Null that stays null means
    -- the tab was closed before a duration could be reported, and is left as
    -- null rather than guessed.
    duration_ms     integer,

    ip_address      text,
    user_agent      text
);

-- The People list: group by person over a window.
CREATE INDEX IF NOT EXISTS activity_events_actor_occurred_idx
    ON curriculum.activity_events (actor_email, occurred_at DESC);

-- The window scan itself, for the totals and the "who was here" sweep.
CREATE INDEX IF NOT EXISTS activity_events_occurred_idx
    ON curriculum.activity_events (occurred_at DESC);

-- "Who opened this record" and the per-page rollups.
CREATE INDEX IF NOT EXISTS activity_events_page_occurred_idx
    ON curriculum.activity_events (page_key, occurred_at DESC);

-- One person's visit, reassembled in order.
CREATE INDEX IF NOT EXISTS activity_events_visit_idx
    ON curriculum.activity_events (visit_id, occurred_at);


-- Verification (read-only). Run after the statements above.
--
--   SELECT to_regclass('curriculum.activity_events') AS table_exists;
--
--   SELECT count(*) AS rows_recorded,
--          count(DISTINCT actor_email) AS people,
--          min(occurred_at) AS first_event,
--          max(occurred_at) AS last_event
--     FROM curriculum.activity_events;
--
-- Expected immediately after provisioning: table_exists is not null, and
-- rows_recorded is 0 until somebody opens a curriculum page.


-- Optional pruning, NOT run as part of provisioning. Nothing older than a year
-- is ever displayed, so this only reclaims space:
--
--   DELETE FROM curriculum.activity_events
--    WHERE occurred_at < now() - interval '400 days';
