-- Run manually in the Neon SQL Editor against the intended database branch.
-- Stores learner absence/recovery state beside the live-session tables.
-- Teams participation evidence remains in curriculum.live_session_attendance.
BEGIN;

CREATE TABLE IF NOT EXISTS curriculum.live_session_absences (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurrence_id varchar(128) NOT NULL,
    learner_profile_id bigint NOT NULL,
    source_kind varchar(32) NOT NULL DEFAULT '',
    source_learner_id integer,
    learner_email varchar(320) NOT NULL DEFAULT '',
    learner_name varchar(500) NOT NULL DEFAULT '',
    recovery_status varchar(24) NOT NULL DEFAULT 'none',
    recovery_method varchar(16) NOT NULL DEFAULT '',
    recovery_reference varchar(255) NOT NULL DEFAULT '',
    reported_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT curriculum_live_absence_recovery_status_valid CHECK (
        recovery_status IN ('none', 'requested', 'catchup_booked', 'completed')
    ),
    CONSTRAINT curriculum_live_absence_recovery_valid CHECK (
           (recovery_status = 'none' AND recovery_method = '' AND recovery_reference = '')
        OR (recovery_status = 'requested' AND recovery_method IN ('recorded', 'alternative'))
        OR (recovery_status = 'catchup_booked'
            AND recovery_method = 'catch-up'
            AND recovery_reference <> '')
        OR (recovery_status = 'completed'
            AND recovery_method = 'catch-up'
            AND recovery_reference <> '')
    ),
    CONSTRAINT curriculum_live_absence_learner_occurrence_uniq
        UNIQUE (occurrence_id, learner_profile_id)
);

ALTER TABLE curriculum.live_session_absences
    DROP CONSTRAINT IF EXISTS curriculum_live_absence_recovery_valid,
    DROP CONSTRAINT IF EXISTS curriculum_live_absence_recovery_status_valid;

ALTER TABLE curriculum.live_session_absences
    ADD CONSTRAINT curriculum_live_absence_recovery_status_valid CHECK (
        recovery_status IN ('none', 'requested', 'catchup_booked', 'completed')
    ),
    ADD CONSTRAINT curriculum_live_absence_recovery_valid CHECK (
           (recovery_status = 'none' AND recovery_method = '' AND recovery_reference = '')
        OR (recovery_status = 'requested' AND recovery_method IN ('recorded', 'alternative'))
        OR (recovery_status IN ('catchup_booked', 'completed')
            AND recovery_method = 'catch-up'
            AND recovery_reference <> '')
    );

UPDATE curriculum.live_session_absences AS absence
SET recovery_status = 'completed',
    updated_at = CURRENT_TIMESTAMP
FROM "Coach".coach_calendar_event AS event
WHERE absence.recovery_method = 'catch-up'
  AND absence.recovery_reference = event.event_key
  AND event.status = 'completed'
  AND absence.recovery_status <> 'completed';

CREATE INDEX IF NOT EXISTS curriculum_live_absence_occurrence_idx
    ON curriculum.live_session_absences (occurrence_id);

CREATE INDEX IF NOT EXISTS curriculum_live_absence_learner_idx
    ON curriculum.live_session_absences (learner_profile_id, created_at DESC);

CREATE INDEX IF NOT EXISTS curriculum_live_absence_recovery_idx
    ON curriculum.live_session_absences (recovery_status, occurrence_id);

COMMIT;

-- Read-only verification after the owner executes this file:
-- SELECT table_schema, table_name
-- FROM information_schema.tables
-- WHERE table_schema = 'curriculum' AND table_name = 'live_session_absences';
--
-- SELECT conname, pg_get_constraintdef(oid)
-- FROM pg_constraint
-- WHERE conrelid = 'curriculum.live_session_absences'::regclass
-- ORDER BY conname;
