-- Run manually in Neon on the intended branch before linking unmatched Teams identities.
-- This table does not change raw Teams evidence. It records a staff-reviewed email alias
-- for a learner inside one delivery module.
BEGIN;

CREATE TABLE IF NOT EXISTS curriculum.live_session_attendance_aliases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_catalogue_id varchar(128) NOT NULL,
    alias_email varchar(320) NOT NULL,
    learner_profile_id bigint NOT NULL,
    canonical_email varchar(320) NOT NULL,
    created_by varchar(320) NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT curriculum_live_attendance_alias_uniq
        UNIQUE (module_catalogue_id, alias_email),
    CONSTRAINT curriculum_live_attendance_alias_normalized
        CHECK (alias_email = lower(btrim(alias_email)) AND alias_email <> ''),
    CONSTRAINT curriculum_live_attendance_alias_canonical_normalized
        CHECK (canonical_email = lower(btrim(canonical_email)) AND canonical_email <> ''),
    CONSTRAINT curriculum_live_attendance_alias_distinct
        CHECK (alias_email <> canonical_email)
);

CREATE INDEX IF NOT EXISTS curriculum_live_attendance_alias_learner_idx
    ON curriculum.live_session_attendance_aliases
       (learner_profile_id, module_catalogue_id);

COMMIT;

-- Read-only verification:
-- SELECT module_catalogue_id, alias_email, learner_profile_id, canonical_email
-- FROM curriculum.live_session_attendance_aliases
-- ORDER BY updated_at DESC;
