-- Run manually in Neon on the intended branch before using attendance sync.
-- This is the learner-only final register. Raw Teams evidence remains untouched
-- in curriculum.live_session_attendance and recovery choices remain in
-- curriculum.live_session_absences.
BEGIN;

CREATE TABLE IF NOT EXISTS curriculum.live_session_learner_attendance (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurrence_id varchar(128) NOT NULL,
    live_session_id varchar(128) NOT NULL,
    module_catalogue_id varchar(128) NOT NULL,
    learner_profile_id bigint NOT NULL,
    learner_email varchar(320) NOT NULL DEFAULT '',
    learner_name varchar(500) NOT NULL DEFAULT '',
    attendance_status varchar(16) NOT NULL,
    recovery_status varchar(24) NOT NULL DEFAULT 'none',
    attended_seconds integer NOT NULL DEFAULT 0,
    attendance_report_id text NOT NULL DEFAULT '',
    first_join_at timestamptz,
    last_leave_at timestamptz,
    calculated_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT curriculum_live_learner_attendance_status_valid
        CHECK (attendance_status IN ('present', 'absent')),
    CONSTRAINT curriculum_live_learner_recovery_status_valid
        CHECK (recovery_status IN ('none', 'requested', 'catchup_booked')),
    CONSTRAINT curriculum_live_learner_attendance_seconds_valid
        CHECK (attended_seconds >= 0),
    CONSTRAINT curriculum_live_learner_attendance_uniq
        UNIQUE (occurrence_id, learner_profile_id)
);

ALTER TABLE curriculum.live_session_learner_attendance
    ADD COLUMN IF NOT EXISTS recovery_status varchar(24) NOT NULL DEFAULT 'none';

ALTER TABLE curriculum.live_session_learner_attendance
    DROP CONSTRAINT IF EXISTS curriculum_live_learner_recovery_status_valid;

ALTER TABLE curriculum.live_session_learner_attendance
    ADD CONSTRAINT curriculum_live_learner_recovery_status_valid
    CHECK (recovery_status IN ('none', 'requested', 'catchup_booked'));

UPDATE curriculum.live_session_learner_attendance AS attendance
SET recovery_status = recovery.recovery_status,
    updated_at = CURRENT_TIMESTAMP
FROM curriculum.live_session_absences AS recovery
WHERE recovery.occurrence_id = attendance.occurrence_id
  AND recovery.learner_profile_id = attendance.learner_profile_id
  AND attendance.attendance_status = 'absent'
  AND attendance.recovery_status IS DISTINCT FROM recovery.recovery_status;

CREATE INDEX IF NOT EXISTS curriculum_live_learner_attendance_occurrence_idx
    ON curriculum.live_session_learner_attendance (occurrence_id, attendance_status);

CREATE INDEX IF NOT EXISTS curriculum_live_learner_attendance_module_idx
    ON curriculum.live_session_learner_attendance (module_catalogue_id, calculated_at DESC);

CREATE INDEX IF NOT EXISTS curriculum_live_learner_attendance_profile_idx
    ON curriculum.live_session_learner_attendance (learner_profile_id, calculated_at DESC);

COMMIT;

-- Read-only verification:
-- SELECT table_schema, table_name
-- FROM information_schema.tables
-- WHERE table_schema = 'curriculum'
--   AND table_name = 'live_session_learner_attendance';
