// @ts-nocheck -- route search types are generated by the embedded app.
import { useEffect, useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { createFileRoute, Link } from "@tanstack/react-router";
import { Download } from "lucide-react";
import { Button } from "@/features/audit/learner-log-pro/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/features/audit/learner-log-pro/components/ui/table";
import { getLearnerActivities, getLearners } from "@/features/audit/learner-log-pro/lib/api";
import { downloadLearnerJournalPdf } from "@/features/audit/learner-log-pro/lib/journal-pdf";

export const Route = createFileRoute("/journal/")({
  validateSearch: (search: Record<string, unknown>) => ({
    learner: typeof search.learner === "string" ? search.learner : "",
    period: typeof search.period === "string" ? search.period : "",
  }),
  component: JournalPage,
});

function Stat({ label, value, tone }: { label: string; value: string; tone?: "success" | "warning" }) {
  return (
    <div className="rounded-md border border-border bg-card px-4 py-3">
      <p className="label-caps">{label}</p>
      <p className={`mt-1 font-mono text-sm ${tone === "success" ? "text-success" : tone === "warning" ? "text-warning" : "text-foreground"}`}>{value}</p>
    </div>
  );
}

function JournalPage() {
  const routeSearch = Route.useSearch();
  const [learnerChoice, setLearnerChoice] = useState(routeSearch.learner);
  const [periodChoice, setPeriodChoice] = useState(routeSearch.period);

  const metadata = useQuery({ queryKey: ["journal-metadata"], queryFn: () => getLearners() });
  useEffect(() => {
    if (!metadata.data) return;
    if (!learnerChoice && metadata.data.learners[0]) {
      setLearnerChoice(metadata.data.learners[0].id);
    }
    if (!periodChoice && metadata.data.periods.length) {
      setPeriodChoice(metadata.data.periods[metadata.data.periods.length - 1]!.value);
    }
  }, [metadata.data, learnerChoice, periodChoice]);

  const selectedLearner = learnerChoice;
  const selectedPeriod = periodChoice;

  const monthSummaries = useQuery({
    queryKey: ["journal-summary", selectedPeriod],
    queryFn: () => getLearners({ period: selectedPeriod }),
    enabled: Boolean(selectedPeriod),
  });
  const activities = useQuery({
    queryKey: ["journal-activities", selectedLearner, selectedPeriod],
    queryFn: () => getLearnerActivities({ learner: selectedLearner, period: selectedPeriod, search: "", limit: 100, offset: 0 }),
    enabled: Boolean(selectedLearner && selectedPeriod),
  });

  const learner = monthSummaries.data?.learners.find((item) => item.id === selectedLearner);
  const cumulativeLearner = metadata.data?.learners.find((item) => item.id === selectedLearner);
  const monthLabel = metadata.data?.periods.find((item) => item.value === selectedPeriod)?.label ?? selectedPeriod;
  const ksbs = useMemo(
    () => Array.from(new Set((activities.data?.items ?? []).flatMap((row) => row.key_ksbs?.split(",").map((value) => value.trim()).filter(Boolean) ?? []))),
    [activities.data],
  );
  const isLoading =
    metadata.isLoading ||
    (Boolean(selectedPeriod) && monthSummaries.isLoading) ||
    (Boolean(selectedLearner && selectedPeriod) && activities.isLoading);
  const pageError = metadata.error || monthSummaries.error || activities.error;

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border bg-surface">
        <div className="mx-auto flex max-w-[88rem] flex-wrap items-center justify-between gap-4 px-6 py-4">
          <div className="flex items-baseline gap-3">
            <span className="font-serif text-base text-foreground">OTJ&nbsp;Ledger</span>
            <span className="label-caps">Live learner journal</span>
          </div>
          <Link to="/activity" search={{ learner: selectedLearner }} className="text-xs font-medium text-muted-foreground hover:underline">← Back to activity log</Link>
        </div>
      </header>

      <main className="mx-auto max-w-[88rem] space-y-6 px-6 py-8">
        <section className="rounded-lg border border-border bg-card p-7 shadow-panel">
          <div className="flex flex-wrap items-start justify-between gap-5 border-b border-border pb-6">
            <div>
              <h1 className="font-serif text-2xl text-foreground">Learner Journal — {metadata.isLoading ? "Loading…" : monthLabel}</h1>
              <p className="mt-2 text-sm text-muted-foreground">Generated live from <span className="font-mono">Audit.mre</span>.</p>
            </div>
            <Button
              className="gap-2"
              disabled={!learner || !activities.data}
              onClick={() => learner && activities.data && downloadLearnerJournalPdf(learner, monthLabel, activities.data.items, cumulativeLearner)}
            >
              <Download className="h-4 w-4" /> Download PDF
            </Button>
          </div>

          <div className="grid gap-4 border-b border-border py-5 sm:grid-cols-2">
            <label><span className="label-caps">Learner</span><select className="mt-1.5 h-9 w-full rounded-md border border-border bg-card px-3 text-sm" value={selectedLearner} onChange={(event) => setLearnerChoice(event.target.value)}>{metadata.data?.learners.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
            <label><span className="label-caps">Activity month</span><select className="mt-1.5 h-9 w-full rounded-md border border-border bg-card px-3 text-sm" value={selectedPeriod} onChange={(event) => setPeriodChoice(event.target.value)}>{metadata.data?.periods.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>
          </div>

          {pageError ? (
            <p className="py-10 text-center text-sm text-destructive">
              {pageError instanceof Error ? pageError.message : "Could not load the journal."}
            </p>
          ) : isLoading || !selectedLearner || !selectedPeriod ? (
            <p className="py-10 text-center text-sm text-muted-foreground">Loading journal from Neon…</p>
          ) : learner ? (
            <>
              <div className="py-5">
                <p className="label-caps">Learner</p>
                <p className="mt-1 font-serif text-lg">{learner.name}</p>
                <p className="mt-4 label-caps">Mapped KSBs in this month</p>
                <div className="mt-2 flex flex-wrap gap-2">{ksbs.map((ksb) => <span key={ksb} className="rounded border border-border bg-muted px-2.5 py-1 font-mono text-xs">{ksb}</span>)}</div>
              </div>
              <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
                <Stat label="Activities" value={String(learner.entries)} />
                <Stat label="Planned hours" value={`${learner.planned_hours.toFixed(2)} h`} />
                <Stat label="Actual hours" value={`${learner.actual_hours.toFixed(2)} h`} tone="success" />
                <Stat label="Actual vs plan" value={`${learner.gap_hours > 0 ? "+" : ""}${learner.gap_hours.toFixed(2)} h`} tone={learner.gap_hours < 0 ? "warning" : "success"} />
                <Stat label="Last activity" value={learner.last_activity_date ?? "—"} />
              </div>
            </>
          ) : null}
        </section>

        <section className="rounded-lg border border-border bg-card shadow-panel">
          <header className="border-b border-border px-7 py-5">
            <h2 className="font-serif text-lg text-foreground">Activity log</h2>
            <p className="mt-1 text-sm text-muted-foreground">{activities.data?.total ?? 0} real activities recorded for this learner and month.</p>
          </header>
          <div className="overflow-x-auto">
            <Table>
              <TableHeader><TableRow className="hover:bg-transparent"><TableHead className="label-caps pl-7">Plan ID</TableHead><TableHead className="label-caps">Date</TableHead><TableHead className="label-caps">Activity</TableHead><TableHead className="label-caps">Category</TableHead><TableHead className="label-caps">KSBs</TableHead><TableHead className="label-caps">Timestamp</TableHead><TableHead className="label-caps text-right">Planned</TableHead><TableHead className="label-caps pr-7 text-right">Actual</TableHead></TableRow></TableHeader>
              <TableBody>
                {activities.data?.items.map((row) => (
                  <TableRow key={row.id}>
                    <TableCell className="pl-7 font-mono text-xs">{row.plan_id}</TableCell>
                    <TableCell className="font-mono text-xs text-muted-foreground">{row.learner_activity_date ?? "—"}</TableCell>
                    <TableCell className="max-w-md"><p className="text-sm font-medium">{row.activity_unit}</p><p className="mt-1 text-xs text-muted-foreground">{row.activity_description}</p></TableCell>
                    <TableCell className="text-xs text-muted-foreground">{row.activity_category}</TableCell>
                    <TableCell className="font-mono text-xs">{row.key_ksbs ?? "—"}</TableCell>
                    <TableCell className="font-mono text-xs text-muted-foreground">{row.time_from_to ?? "—"}</TableCell>
                    <TableCell className="text-right font-mono text-sm">{row.planned_hours?.toFixed(2) ?? "—"}</TableCell>
                    <TableCell className="pr-7 text-right font-mono text-sm text-success">{row.actual_lms_hours?.toFixed(2) ?? "—"}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </section>
      </main>
    </div>
  );
}
