// @ts-nocheck -- route search types are generated by the embedded app.
import { useEffect, useState } from "react";
import { keepPreviousData, useQuery } from "@tanstack/react-query";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, FileText, Search } from "lucide-react";
import { Button } from "@/features/audit/learner-log-pro/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/features/audit/learner-log-pro/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/features/audit/learner-log-pro/components/ui/table";
import { getLearnerActivities, getLearners } from "@/features/audit/learner-log-pro/lib/api";

export const Route = createFileRoute("/search")({
  component: SearchPage,
});

const field =
  "h-9 w-full rounded-md border border-border bg-card px-2.5 text-sm text-foreground outline-none focus:border-primary";
const pageSize = 30;

function Filter({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label className="block">
      <span className="label-caps">{label}</span>
      <span className="mt-1.5 block">{children}</span>
    </label>
  );
}

function StyledFilterSelect({
  value,
  options,
  allLabel,
  includeAllOption = true,
  onChange,
}: {
  value: string;
  options: Array<{ value: string; label: string }>;
  allLabel: string;
  includeAllOption?: boolean;
  onChange: (value: string) => void;
}) {
  return (
    <Select
      value={value || (includeAllOption ? "all" : undefined)}
      onValueChange={(nextValue) => onChange(includeAllOption && nextValue === "all" ? "" : nextValue)}
    >
      <SelectTrigger className="bg-card shadow-none">
        <SelectValue placeholder={allLabel} />
      </SelectTrigger>
      <SelectContent position="popper" className="max-h-72">
        {includeAllOption && <SelectItem value="all">{allLabel}</SelectItem>}
        {options.filter((option) => option.value !== "all").map((option) => (
          <SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}

function formatHours(value: number) {
  return `${value.toFixed(2)} h`;
}

function SearchPage() {
  const [learnerSearch, setLearnerSearch] = useState("");
  const [sharedPeriod, setSharedPeriod] = useState("");
  const [gapBand, setGapBand] = useState("all");

  const [activitySearch, setActivitySearch] = useState("");
  const [activityLearner, setActivityLearner] = useState("");
  const [activityCategory, setActivityCategory] = useState("");
  const [page, setPage] = useState(0);

  const filterOptions = useQuery({
    queryKey: ["search-filter-options"],
    queryFn: () => getLearners(),
  });

  useEffect(() => {
    const periods = filterOptions.data?.periods ?? [];
    if (sharedPeriod || periods.length === 0) return;
    const latestPeriod = [...periods].sort((left, right) => left.value.localeCompare(right.value)).at(-1);
    if (latestPeriod) setSharedPeriod(latestPeriod.value);
  }, [filterOptions.data?.periods, sharedPeriod]);

  const summaries = useQuery({
    queryKey: ["learner-summaries", sharedPeriod, learnerSearch, gapBand],
    queryFn: () =>
      getLearners({
        period: sharedPeriod || undefined,
        search: learnerSearch || undefined,
        position: gapBand === "all" ? undefined : gapBand,
      }),
    enabled: Boolean(sharedPeriod),
  });

  const activities = useQuery({
    queryKey: [
      "learner-activities-search",
      activitySearch,
      activityLearner,
      learnerSearch,
      sharedPeriod,
      activityCategory,
      page,
    ],
    queryFn: () =>
      getLearnerActivities({
        search: activitySearch,
        learner: activityLearner || undefined,
        learnerSearch: learnerSearch || undefined,
        period: sharedPeriod || undefined,
        category: activityCategory || undefined,
        limit: pageSize,
        offset: page * pageSize,
      }),
    placeholderData: keepPreviousData,
    enabled: Boolean(sharedPeriod),
  });

  const totalPages = Math.max(1, Math.ceil((activities.data?.total ?? 0) / pageSize));
  const resetPage = () => setPage(0);

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border bg-surface">
        <div className="mx-auto flex max-w-[88rem] flex-wrap items-center justify-between gap-4 px-6 py-4">
          <div className="flex items-baseline gap-3">
            <span className="font-serif text-base text-foreground">OTJ&nbsp;Ledger</span>
            <span className="label-caps">Live learner search</span>
          </div>
          <div className="flex items-center gap-4 text-xs text-muted-foreground">
            <Link to="/journal" search={{ learner: "", period: "" }} className="font-medium hover:underline">
              Monthly journal
            </Link>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-[88rem] space-y-6 px-6 py-8">
        <section className="rounded-lg border border-border bg-card shadow-panel">
          <header className="border-b border-border px-7 py-5">
            <h1 className="font-serif text-lg text-foreground">Learner search</h1>
            <p className="mt-1 text-sm text-muted-foreground">
              Live learner totals calculated from the Neon <span className="font-mono">Audit.mre</span> table.
            </p>
          </header>

          <div className="grid gap-4 border-b border-border px-7 py-5 sm:grid-cols-3">
            <Filter label="Learner name">
              <span className="relative block">
                <Search className="pointer-events-none absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                <input
                  className={`${field} pl-8`}
                  placeholder="Search learner…"
                  value={learnerSearch}
                  onChange={(event) => {
                    const value = event.target.value;
                    const exactLearner = filterOptions.data?.learners.find(
                      (learner) => learner.name.toLowerCase() === value.trim().toLowerCase(),
                    );
                    setLearnerSearch(value);
                    setActivityLearner(exactLearner?.id ?? "");
                    resetPage();
                  }}
                />
              </span>
            </Filter>
            <Filter label="Activity month">
              <StyledFilterSelect
                value={sharedPeriod}
                options={filterOptions.data?.periods ?? []}
                allLabel="Loading latest month…"
                includeAllOption={false}
                onChange={(value) => { setSharedPeriod(value); resetPage(); }}
              />
            </Filter>
            <Filter label="Hours position">
              <StyledFilterSelect
                value={gapBand}
                allLabel="All learners"
                options={[
                  { value: "behind", label: "Behind plan" },
                  { value: "ahead", label: "On or ahead of plan" },
                ]}
                onChange={(value) => setGapBand(value || "all")}
              />
            </Filter>
          </div>

          {summaries.isError ? (
            <p className="px-7 py-10 text-center text-sm text-destructive">
              {summaries.error instanceof Error ? summaries.error.message : "Could not load learner data."}
            </p>
          ) : (
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow className="hover:bg-transparent">
                    <TableHead className="label-caps pl-7">Learner</TableHead>
                    <TableHead className="label-caps text-right">Activities</TableHead>
                    <TableHead className="label-caps text-right">Planned hours</TableHead>
                    <TableHead className="label-caps text-right">Actual hours</TableHead>
                    <TableHead className="label-caps text-right">Actual vs plan</TableHead>
                    <TableHead className="label-caps">Last activity</TableHead>
                    <TableHead className="label-caps pr-7 text-right">Report</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {summaries.isLoading && (
                    <TableRow><TableCell colSpan={7} className="py-10 text-center text-sm text-muted-foreground">Loading learners from Neon…</TableCell></TableRow>
                  )}
                  {summaries.data?.learners.map((learner) => (
                    <TableRow key={learner.id}>
                      <TableCell className="pl-7 text-sm font-semibold text-foreground">{learner.name}</TableCell>
                      <TableCell className="text-right font-mono text-sm">{learner.entries}</TableCell>
                      <TableCell className="text-right font-mono text-sm">{formatHours(learner.planned_hours)}</TableCell>
                      <TableCell className="text-right font-mono text-sm text-success">{formatHours(learner.actual_hours)}</TableCell>
                      <TableCell className={`text-right font-mono text-sm ${learner.gap_hours < 0 ? "text-warning" : "text-success"}`}>
                        {learner.gap_hours > 0 ? "+" : ""}{formatHours(learner.gap_hours)}
                      </TableCell>
                      <TableCell className="font-mono text-xs text-muted-foreground">{learner.last_activity_date ?? "—"}</TableCell>
                      <TableCell className="pr-7 text-right">
                        <Link
                          to="/journal"
                          search={{ learner: learner.id, period: sharedPeriod }}
                          className="inline-flex items-center gap-1.5 text-xs font-semibold text-foreground hover:text-primary hover:underline"
                        >
                          <FileText className="h-3.5 w-3.5" /> Monthly report
                        </Link>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </section>

        <section className="rounded-lg border border-border bg-card shadow-panel">
          <header className="flex flex-wrap items-end justify-between gap-4 border-b border-border px-7 py-5">
            <div>
              <h2 className="font-serif text-lg text-foreground">Activity log search</h2>
              <p className="mt-1 text-sm text-muted-foreground">Real learner activity dates, timestamps and hours from MRE.</p>
            </div>
            <dl className="flex gap-6">
              <div><dt className="label-caps">Matches</dt><dd className="font-mono text-sm">{activities.data?.total ?? 0}</dd></div>
              <div><dt className="label-caps">Planned total</dt><dd className="font-mono text-sm">{formatHours(activities.data?.planned_total ?? 0)}</dd></div>
              <div><dt className="label-caps">Actual total</dt><dd className="font-mono text-sm text-success">{formatHours(activities.data?.actual_total ?? 0)}</dd></div>
            </dl>
          </header>

          <div className="grid gap-4 border-b border-border px-7 py-5 sm:grid-cols-2 lg:grid-cols-4">
            <Filter label="Search">
              <input className={field} placeholder="Plan or activity…" value={activitySearch} onChange={(event) => { setActivitySearch(event.target.value); resetPage(); }} />
            </Filter>
            <Filter label="Learner">
              <StyledFilterSelect
                value={activityLearner}
                allLabel="All learners"
                options={filterOptions.data?.learners.map((learner) => ({ value: learner.id, label: learner.name })) ?? []}
                onChange={(value) => {
                  const learnerName = filterOptions.data?.learners.find((learner) => learner.id === value)?.name ?? "";
                  setActivityLearner(value);
                  setLearnerSearch(learnerName);
                  resetPage();
                }}
              />
            </Filter>
            <Filter label="Activity month">
              <StyledFilterSelect
                value={sharedPeriod}
                options={filterOptions.data?.periods ?? []}
                allLabel="Loading latest month…"
                includeAllOption={false}
                onChange={(value) => { setSharedPeriod(value); resetPage(); }}
              />
            </Filter>
            <Filter label="Category">
              <StyledFilterSelect
                value={activityCategory}
                allLabel="All categories"
                options={filterOptions.data?.categories.map((category) => ({ value: category, label: category })) ?? []}
                onChange={(value) => { setActivityCategory(value); resetPage(); }}
              />
            </Filter>
          </div>

          {activities.isError ? (
            <p className="px-7 py-10 text-center text-sm text-destructive">
              {activities.error instanceof Error ? activities.error.message : "Could not load activities."}
            </p>
          ) : (
            <div className="max-h-[36rem] overflow-auto">
              <Table>
                <TableHeader>
                  <TableRow className="hover:bg-transparent">
                    <TableHead className="label-caps pl-7">Plan ID</TableHead>
                    <TableHead className="label-caps">Date</TableHead>
                    <TableHead className="label-caps">Learner</TableHead>
                    <TableHead className="label-caps">Month</TableHead>
                    <TableHead className="label-caps">Category</TableHead>
                    <TableHead className="label-caps">Activity</TableHead>
                    <TableHead className="label-caps">Timestamp</TableHead>
                    <TableHead className="label-caps text-right">Planned</TableHead>
                    <TableHead className="label-caps pr-7 text-right">Actual</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {activities.isLoading && (
                    <TableRow><TableCell colSpan={9} className="py-10 text-center text-sm text-muted-foreground">Loading activity records…</TableCell></TableRow>
                  )}
                  {activities.data?.items.map((row) => (
                    <TableRow key={row.id}>
                      <TableCell className="pl-7 font-mono text-xs">{row.plan_id}</TableCell>
                      <TableCell className="font-mono text-xs text-muted-foreground">{row.learner_activity_date ?? "—"}</TableCell>
                      <TableCell className="text-sm font-medium">{row.learner}</TableCell>
                      <TableCell className="text-xs text-muted-foreground">{row.month_no}</TableCell>
                      <TableCell className="text-xs text-muted-foreground">{row.activity_category}</TableCell>
                      <TableCell className="max-w-sm text-sm">
                        <Link
                          to="/activity"
                          search={{ learner: "", plan: row.plan_id }}
                          className="font-semibold text-primary hover:underline"
                        >
                          {row.activity_unit}
                        </Link>
                      </TableCell>
                      <TableCell className="font-mono text-xs text-muted-foreground">{row.time_from_to ?? "—"}</TableCell>
                      <TableCell className="text-right font-mono text-sm">{row.planned_hours ?? "—"}</TableCell>
                      <TableCell className="pr-7 text-right font-mono text-sm text-success">{row.actual_lms_hours ?? "—"}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}

          <footer className="flex items-center justify-between border-t border-border px-7 py-4 text-xs text-muted-foreground">
            <span>Page {page + 1} of {totalPages}</span>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" disabled={page === 0} onClick={() => setPage((value) => value - 1)}><ArrowLeft className="mr-1 h-3.5 w-3.5" /> Previous</Button>
              <Button variant="outline" size="sm" disabled={page + 1 >= totalPages} onClick={() => setPage((value) => value + 1)}>Next <ArrowRight className="ml-1 h-3.5 w-3.5" /></Button>
            </div>
          </footer>
        </section>
      </main>
    </div>
  );
}
