// ============================================================================
// Learning plan API client
// The modules a learner will actually be taught. Seeded from their group's
// preset (curriculum.groups.module_ids), then editable from the whole module
// catalogue — the picker offers every programme, not only the learner's own, so
// each module carries the programme it came from.
// Persisted on enrolment."Created_users"."Learning_plan" (jsonb).
// ============================================================================
import { formatHoursMinutes } from '@/lib/format';
import { invalidateLearnerDetailCache } from './learnerDetail';
import type { FreeCourseAssignment } from './trainingPlan';
const BASE = '/learner_api/learning-plan';
const MODULE_BASE = '/learner_api/module-learners';

export interface LearningPlanModule {
  moduleId: string;
  moduleTitle: string;
  groupName: string;
  /** The programme this module belongs to — not necessarily the learner's. */
  programmeId: string;
  programmeName: string;
  /** Off-the-job hours for this module (curriculum.modules.total_otjh). */
  hours: number;
  /**
   * The module's delivery window (curriculum.modules start_date/end_date), as
   * YYYY-MM-DD — '' when the module has not been scheduled. Read-only: it is
   * set where the module is scheduled, not on the plan.
   */
  startDate?: string;
  endDate?: string;
  /**
   * Saved on the plan but no longer in the catalogue — either the module was
   * retired, or the row predates this shape. Kept rather than silently
   * dropped, since the plan is a record of what was agreed.
   */
  orphaned?: boolean;
  /**
   * Added to the learner's group after this plan was agreed, so it is shown on
   * the plan but not yet stored against the learner. Saving the plan adopts it.
   */
  inherited?: boolean;
  /** Taught via the learner's Aptem import but never written to their plan
   *  column. Shown like `inherited`: visible, flagged, saved only on Save. */
  fromAptem?: boolean;
}

/** A programme the picker can switch to, with how many modules it offers. */
export interface LearningPlanProgramme {
  programmeId: string;
  programmeName: string;
  moduleCount: number;
}

/**
 * A recurring Review the learner attends, and the off-the-job hours it is
 * worth across the whole plan. Generated by the Review Engine from the
 * programme's Review templates and the learner's start date — read-only here,
 * unlike a module: nothing on the plan screen can add or remove one. Only
 * templates Curriculum flagged `countsTowardsOtjh` appear.
 */
export interface LearningPlanMeeting {
  reviewTemplateId: string;
  /** The Review's live name — a rename in Curriculum shows here immediately. */
  name: string;
  /** Off-the-job hours ONE occurrence is worth. */
  hoursEach: number;
  /** How many occurrences fall inside the learner's programme window. */
  occurrences: number;
  /** hoursEach × occurrences. */
  hours: number;
  /** e.g. "Every month" — how often it recurs. */
  recurrenceLabel: string;
  /** First and last projected occurrence, as YYYY-MM-DD. */
  startDate: string;
  endDate: string;
}

export interface LearningPlanTotals {
  moduleCount: number;
  /** Module hours alone — the modules table's own subtotal. */
  moduleHours: number;
  meetingCount: number;
  /** Meeting hours alone — the meetings table's own subtotal. */
  meetingHours: number;
  /** moduleHours + meetingHours: the whole commitment. */
  totalHours: number;
}

export interface LearningPlanResponse {
  learner: {
    id: string;
    name: string;
    programme: string;
    /** The learner's own programme, which the picker opens on. */
    programmeId: string;
    cohort: string;
    group: string;
    programmeStatus: string;
  };
  /** The current plan — the saved one, or the group preset if never saved. */
  plan: LearningPlanModule[];
  /**
   * Free courses assigned to this learner — a pure assignment record with no
   * hours or KSBs, stored separately from the plan above (see
   * EnrolmentUser.free_courses). Independent of programme/group.
   */
  freeCourses: FreeCourseAssignment[];
  /** The learner's group's modules, for "reset to group default". */
  preset: LearningPlanModule[];
  /** Every catalogue module not already on the plan, for the add picker. */
  available: LearningPlanModule[];
  /** The programmes to choose between in the picker. */
  programmes: LearningPlanProgramme[];
  /** False when the plan shown is still just the group preset. */
  saved: boolean;
  /**
   * How many rows in `plan` arrived from the group since it was last agreed.
   * Non-zero means what is on screen is ahead of what is stored.
   */
  inheritedCount?: number;
  /**
   * The learner's recurring Reviews, shown as their own table beside the
   * modules. Empty when the programme has no OTJH-bearing Review, or the
   * learner has no start/end date to project a schedule from.
   */
  meetings?: LearningPlanMeeting[];
  /**
   * Why `meetings` is empty — '' when it is not. The table renders either way
   * and shows this as its empty state, so "nothing is configured yet" never
   * looks like a broken feature.
   */
  meetingsReason?: '' | 'no-programme' | 'no-dates' | 'no-otjh-reviews' | 'not-eligible' | 'unavailable';
  totals: LearningPlanTotals;
}

async function parse(res: Response) {
  if (!res.ok) {
    let message = `Request failed (${res.status})`;
    try {
      const body = await res.json();
      if (body?.error) message = body.error;
    } catch {
      // Non-JSON error body (proxy/HTML error page) — keep the status message.
    }
    throw new Error(message);
  }
  return res.json();
}

export async function fetchLearningPlan(learnerId: string | number): Promise<LearningPlanResponse> {
  return parse(await fetch(`${BASE}/${learnerId}/`));
}

/**
 * Save the plan. Order is preserved; hours/titles/dates are re-derived
 * server-side. `freeCourses`, when passed, replaces the learner's free-course
 * assignments (a separate column — no hours/KSBs). Omit it to leave them as they
 * are.
 */
export async function saveLearningPlan(
  learnerId: string | number,
  moduleIds: string[],
  freeCourses?: FreeCourseAssignment[],
): Promise<LearningPlanResponse> {
  const body: { modules: { moduleId: string }[]; freeCourses?: FreeCourseAssignment[] } = {
    modules: moduleIds.map((moduleId) => ({ moduleId })),
  };
  if (freeCourses !== undefined) body.freeCourses = freeCourses;
  const result = await parse(
    await fetch(`${BASE}/${learnerId}/`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    }),
  );
  invalidateLearnerDetailCache();
  return result;
}

/** A module's window date for reading. '' stays an em dash, not "Invalid Date". */
export function formatPlanDate(value?: string): string {
  if (!value) return '—';
  const parsed = new Date(`${value}T00:00:00`);
  if (Number.isNaN(parsed.getTime())) return value;
  return parsed.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
}

export function formatHours(hours: number): string {
  return formatHoursMinutes(Number(hours || 0));
}

// ---------------------------------------------------------------------------
// The same assignment from the module's side
// ---------------------------------------------------------------------------
// The Module builder's "Assign learners" picker: one module, every learner in
// enrolment."Created_users", ticked on or off. A tick is a plan save — it
// appends this module to that learner's plan and an untick removes it — so
// there is no second roster to disagree with the plans above.
// ---------------------------------------------------------------------------

/** One learner in the picker, with whether this module is already theirs. */
export interface ModuleLearnerRow {
  id: string;
  name: string;
  email: string;
  /** 'apprenticeship' | 'commercial'. */
  learnerType: string;
  programme: string;
  cohort: string;
  group: string;
  programmeStatus: string;
  assigned: boolean;
  /**
   * Assigned because their group teaches this module, not because anyone
   * agreed their plan. Saving the picker unchanged leaves it that way.
   */
  fromPreset: boolean;
  /** How many modules their plan holds in total, this one included. */
  moduleCount: number;
}

export interface ModuleLearnersResponse {
  module: {
    moduleId: string;
    moduleTitle: string;
    programmeId: string;
    programmeName: string;
    groupName: string;
    hours: number;
    startDate: string;
    endDate: string;
  };
  learners: ModuleLearnerRow[];
  totals: { learnerCount: number; assignedCount: number };
  /** Only on a save: how many learners' plans actually changed. */
  changedCount?: number;
}

export async function fetchModuleLearners(moduleId: string): Promise<ModuleLearnersResponse> {
  return parse(await fetch(`${MODULE_BASE}/${encodeURIComponent(moduleId)}/`));
}

/**
 * Set who is assigned to this module. The list is the whole assignment, not a
 * delta: a learner left out of it has the module removed from their plan.
 *
 */
export async function saveModuleLearners(
  moduleId: string,
  learnerIds: Array<string | number>,
): Promise<ModuleLearnersResponse> {
  const result = await parse(
    await fetch(`${MODULE_BASE}/${encodeURIComponent(moduleId)}/`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ learnerIds: learnerIds.map(String) }),
    }),
  );
  // This roster also removes assignments for learners omitted from the list.
  invalidateLearnerDetailCache();
  return result;
}
