// @ts-nocheck -- route types are generated by the embedded app.
// Plan-builder home: the cohort groups list + the create-group step.
// Creating a group persists a DRAFT immediately (name/programme/months) and
// jumps into the group workspace where members and the plan are built.
import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ArrowLeft, CalendarRange, Plus, UsersRound } from "lucide-react";
import Swal from "sweetalert2";
import { Button } from "@/features/audit/learner-log-pro-manual/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/features/audit/learner-log-pro-manual/components/ui/table";
import { getLearners } from "@/features/audit/learner-log-pro-manual/lib/api";
import {
  createPlanGroup,
  listPlanGroups,
  pickLmsGroupMembers,
  pickLmsGroups,
  updatePlanMembers,
} from "@/features/audit/learner-log-pro-manual/lib/plan-api";

export const Route = createFileRoute("/groups")({
  component: GroupsPage,
});

const field =
  "h-9 w-full rounded-md border border-border bg-card px-2.5 text-sm text-foreground outline-none focus:border-primary";

function statusChip(status: string) {
  if (status === "active") return "bg-success/10 text-success";
  if (status === "draft") return "bg-warning/20 text-foreground ring-1 ring-warning/40";
  return "bg-muted text-muted-foreground";
}

function GroupsPage() {
  const queryClient = useQueryClient();
  const navigate = useNavigate();
  const [creating, setCreating] = useState(false);
  const [saving, setSaving] = useState(false);
  const [name, setName] = useState("");
  const [programme, setProgramme] = useState("");
  const [startMonth, setStartMonth] = useState("");
  const [monthsCount, setMonthsCount] = useState(12);
  const [lmsGroupId, setLmsGroupId] = useState("");

  const groups = useQuery({ queryKey: ["plan-groups"], queryFn: listPlanGroups });
  const lmsGroups = useQuery({ queryKey: ["plan-lms-groups"], queryFn: pickLmsGroups });
  // Programme options come from the cohort itself (select-or-type rule).
  const cohort = useQuery({ queryKey: ["search-filter-options"], queryFn: () => getLearners() });
  const programmeOptions = [
    ...new Set(
      cohort.data?.learners
        .flatMap((learner) => (learner.programmes?.length ? learner.programmes : [learner.programme]))
        .filter(Boolean) ?? [],
    ),
  ].sort();

  async function create() {
    if (!name.trim() && !lmsGroupId) {
      return void Swal.fire({ icon: "error", title: "Name the group", text: "Pick an LMS group or type a name (e.g. October Group)." });
    }
    setSaving(true);
    try {
      const lmsGroupName = lmsGroups.data?.items.find((item) => String(item.group_id) === lmsGroupId)?.name;
      const created = await createPlanGroup({
        name: name.trim() || lmsGroupName || "New group",
        kind: "cohort",
        programme_name: programme.trim() || null,
        start_month: startMonth || null,
        months_count: startMonth ? monthsCount : 0,
      });
      // Picking an LMS group assigns ALL its learners immediately — everything
      // added to the plan then applies to every one of them.
      let assigned = 0;
      if (lmsGroupId) {
        const seed = await pickLmsGroupMembers(Number(lmsGroupId));
        if (seed.items.length) {
          const result = await updatePlanMembers(created.id, { add: seed.items.map((item) => item.aptem_id) });
          assigned = result.added.length;
        }
      }
      await queryClient.invalidateQueries({ queryKey: ["plan-groups"] });
      void Swal.fire({
        toast: true, position: "top-end", icon: "success",
        title: assigned ? `Group created — ${assigned} learners assigned` : "Draft group created",
        showConfirmButton: false, timer: 2200,
      });
      navigate({ to: "/groups/$groupId", params: { groupId: String(created.id) } });
    } catch (cause) {
      await Swal.fire({ icon: "error", title: "Could not create the group", text: cause instanceof Error ? cause.message : "Unexpected error." });
    } finally {
      setSaving(false);
    }
  }

  // Individual plans (groups of one) live on the learner pages — the cohort
  // list stays clean, exactly as the design review required.
  const visibleGroups = (groups.data?.items ?? []).filter((group) => group.kind === "cohort");

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border bg-surface">
        <div className="mx-auto flex max-w-[1700px] flex-wrap items-center justify-between gap-4 px-6 py-4">
          <div className="flex items-baseline gap-3">
            <span className="font-serif text-base text-foreground">OTJ&nbsp;Ledger</span>
            <span className="label-caps">Plan builder — groups</span>
          </div>
          <div className="flex items-center gap-4 text-xs text-muted-foreground">
            <Link to="/search" className="font-medium hover:underline">Learner search</Link>
            <Link to="/activity" search={{ learner: "" }} className="font-medium hover:underline">Activity log</Link>
            <Link to="/journal" search={{ learner: "", period: "" }} className="font-medium hover:underline">Monthly journal</Link>
          </div>
        </div>
      </header>

      <main className="mx-auto w-full max-w-[1300px] space-y-6 px-6 py-8">
        <section className="rounded-lg border border-border bg-card shadow-panel">
          <header className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-7 py-5">
            <div>
              <h1 className="font-serif text-lg text-foreground">Groups</h1>
              <p className="mt-1 text-sm text-muted-foreground">
                One plan per group — every member shares it; only per-learner progress differs.
              </p>
            </div>
            <Button size="sm" onClick={() => setCreating((value) => !value)}>
              <Plus className="mr-1.5 h-3.5 w-3.5" /> New group
            </Button>
          </header>

          {creating && (
            <div className="grid gap-4 border-b border-border bg-secondary/40 px-7 py-5 sm:grid-cols-2 lg:grid-cols-5">
              <label className="block">
                <span className="label-caps">LMS group (auto-assigns its learners)</span>
                <select
                  className={`${field} mt-1.5`}
                  value={lmsGroupId}
                  onChange={(e) => {
                    setLmsGroupId(e.target.value);
                    const picked = lmsGroups.data?.items.find((item) => String(item.group_id) === e.target.value);
                    if (picked && !name.trim()) setName(picked.name);
                  }}
                >
                  <option value="">— none, pick members later —</option>
                  {(lmsGroups.data?.items ?? []).map((option) => (
                    <option key={option.group_id} value={option.group_id}>{option.name} ({option.learner_count})</option>
                  ))}
                </select>
              </label>
              <label className="block">
                <span className="label-caps">Group name</span>
                <input className={`${field} mt-1.5`} placeholder="October Group" value={name} onChange={(e) => setName(e.target.value)} />
              </label>
              <label className="block">
                <span className="label-caps">Programme</span>
                <input className={`${field} mt-1.5`} list="plan-programme-options" placeholder="Select or type…" value={programme} onChange={(e) => setProgramme(e.target.value)} />
                <datalist id="plan-programme-options">
                  {programmeOptions.map((option) => <option key={option} value={option} />)}
                </datalist>
              </label>
              <label className="block">
                <span className="label-caps">Start month</span>
                <input type="month" className={`${field} mt-1.5`} value={startMonth} onChange={(e) => setStartMonth(e.target.value)} />
              </label>
              <label className="block">
                <span className="label-caps">Months</span>
                <div className="mt-1.5 flex gap-2">
                  <input type="number" min={1} max={48} className={`${field} w-24`} value={monthsCount} onChange={(e) => setMonthsCount(Number(e.target.value) || 1)} />
                  <Button size="sm" disabled={saving} onClick={() => void create()}>Create draft</Button>
                </div>
              </label>
            </div>
          )}

          {groups.isError ? (
            <p className="px-7 py-10 text-center text-sm text-destructive">
              {groups.error instanceof Error ? groups.error.message : "Could not load groups."}
            </p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow className="hover:bg-transparent">
                  <TableHead className="label-caps pl-7">Group</TableHead>
                  <TableHead className="label-caps">Programme</TableHead>
                  <TableHead className="label-caps">Status</TableHead>
                  <TableHead className="label-caps text-right">Members</TableHead>
                  <TableHead className="label-caps text-right">Activities</TableHead>
                  <TableHead className="label-caps">Start</TableHead>
                  <TableHead className="label-caps pr-7 text-right">Open</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {groups.isLoading && (
                  <TableRow><TableCell colSpan={7} className="py-10 text-center text-sm text-muted-foreground">Loading groups…</TableCell></TableRow>
                )}
                {!groups.isLoading && visibleGroups.length === 0 && (
                  <TableRow><TableCell colSpan={7} className="py-10 text-center text-sm text-muted-foreground">No groups yet — create the first one to start planning.</TableCell></TableRow>
                )}
                {visibleGroups.map((group) => (
                  <TableRow key={group.id}>
                    <TableCell className="pl-7">
                      <p className="text-sm font-semibold text-foreground">{group.name}</p>
                      <p className="mt-0.5 text-xs text-muted-foreground">Created {group.created_at ? group.created_at.slice(0, 10) : "—"}</p>
                    </TableCell>
                    <TableCell className="text-sm">{group.programme_name ?? "—"}</TableCell>
                    <TableCell>
                      <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${statusChip(group.status)}`}>{group.status}</span>
                    </TableCell>
                    <TableCell className="text-right font-mono text-sm">
                      <span className="inline-flex items-center gap-1"><UsersRound className="h-3.5 w-3.5 text-muted-foreground" />{group.member_count ?? 0}</span>
                    </TableCell>
                    <TableCell className="text-right font-mono text-sm">{group.activity_count ?? 0}</TableCell>
                    <TableCell className="font-mono text-xs text-muted-foreground">
                      <span className="inline-flex items-center gap-1"><CalendarRange className="h-3.5 w-3.5" />{group.start_month ?? "—"}</span>
                    </TableCell>
                    <TableCell className="pr-7 text-right">
                      <Link
                        to="/groups/$groupId"
                        params={{ groupId: String(group.id) }}
                        className="inline-flex items-center gap-1.5 rounded-md border border-border bg-card px-2.5 py-1.5 text-xs font-semibold text-foreground transition-colors hover:bg-secondary"
                      >
                        Open plan <ArrowLeft className="h-3.5 w-3.5 rotate-180" />
                      </Link>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </section>
      </main>
    </div>
  );
}
