// @ts-nocheck -- route types are generated by the embedded app.
// Learner-first plan builder (the group system was retired): the auditor adds
// ONE learner at a time, picked from Aptem. The learner arrives with their own
// Aptem training-plan months — labels and dates exactly as Aptem shows them —
// and four fixed weeks inside each month to fill with activities.
import { useEffect, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { BookOpenText, CalendarDays, ClipboardList, Trash2, UserRound, UserRoundPlus } from "lucide-react";
import Swal from "sweetalert2";
import { Button } from "@/features/audit/learner-log-pro-manual/components/ui/button";
import {
  addLearnerPlan, archivePlanGroup, listLearnerPlans, searchAptemLearners,
  type AptemLearnerHit, type LearnerPlan,
} from "@/features/audit/learner-log-pro-manual/lib/plan-api";

export const Route = createFileRoute("/learners")({
  component: LearnersPage,
});

const field =
  "h-9 w-full rounded-md border border-border bg-card px-2.5 text-sm text-foreground outline-none focus:border-primary";

function toast(title: string) {
  void Swal.fire({ toast: true, position: "top-end", icon: "success", title, showConfirmButton: false, timer: 1600 });
}

function fail(title: string, cause: unknown) {
  void Swal.fire({ icon: "error", title, text: cause instanceof Error ? cause.message : "Unexpected error." });
}

function LearnersPage() {
  const queryClient = useQueryClient();
  const navigate = useNavigate();
  const [search, setSearch] = useState("");
  const [needle, setNeedle] = useState("");
  const [addingId, setAddingId] = useState<number | null>(null);

  // Debounce: the Aptem search hits the API per settled input, not keystroke.
  useEffect(() => {
    const handle = setTimeout(() => setNeedle(search.trim()), 300);
    return () => clearTimeout(handle);
  }, [search]);

  const plans = useQuery({ queryKey: ["learner-plans"], queryFn: listLearnerPlans });
  const hits = useQuery({
    queryKey: ["aptem-learner-search", needle],
    queryFn: () => searchAptemLearners(needle),
    enabled: needle.length >= 2,
  });

  async function add(hit: AptemLearnerHit) {
    setAddingId(hit.aptem_id);
    try {
      const created = await addLearnerPlan(hit.aptem_id, "ayman");
      await queryClient.invalidateQueries({ queryKey: ["learner-plans"] });
      await queryClient.invalidateQueries({ queryKey: ["aptem-learner-search"] });
      toast(
        created.month_count > 0
          ? `${created.learner_name ?? "Learner"} added — ${created.month_count} months from their training plan`
          : `${created.learner_name ?? "Learner"} added — no training plan found, add months manually`,
      );
      void navigate({ to: "/learners/$planId", params: { planId: String(created.id) } });
    } catch (cause) {
      fail("Could not add the learner", cause);
    } finally {
      setAddingId(null);
    }
  }

  async function remove(plan: LearnerPlan) {
    const confirmation = await Swal.fire({
      icon: "warning",
      title: `Remove ${plan.learner_name ?? "this learner"}?`,
      text: "Their plan stops appearing in the journal. Recorded progress is kept.",
      showCancelButton: true, confirmButtonText: "Remove", confirmButtonColor: "#dc2626",
    });
    if (!confirmation.isConfirmed) return;
    try {
      await archivePlanGroup(plan.id);
      await queryClient.invalidateQueries({ queryKey: ["learner-plans"] });
      await queryClient.invalidateQueries({ queryKey: ["aptem-learner-search"] });
      toast("Learner removed");
    } catch (cause) {
      fail("Could not remove the learner", cause);
    }
  }

  const items = plans.data?.items ?? [];
  const results = hits.data?.items ?? [];

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border bg-surface">
        <div className="mx-auto flex max-w-[1700px] flex-wrap items-center justify-between gap-4 px-6 py-4">
          <div className="flex items-baseline gap-3">
            <span className="font-serif text-base text-foreground">OTJ&nbsp;Ledger</span>
            <span className="label-caps">Plan builder — learners</span>
          </div>
          <div className="flex items-center gap-4 text-xs text-muted-foreground">
            <Link to="/search" className="font-medium hover:underline">Learner search</Link>
            <Link to="/activity" className="font-medium hover:underline">Activity log</Link>
            <Link to="/journal" search={{ learner: "", period: "" }} className="font-medium hover:underline">Monthly journal</Link>
          </div>
        </div>
      </header>

      <main className="mx-auto w-full max-w-[1100px] space-y-6 px-6 py-8">
        <section className="rounded-lg border border-border bg-card shadow-panel">
          <header className="border-b border-border px-7 py-5">
            <h1 className="flex items-center gap-2 font-serif text-lg text-foreground">
              <UserRoundPlus className="h-5 w-5 text-muted-foreground" /> Add a learner
            </h1>
            <p className="mt-1 text-sm text-muted-foreground">
              Pick the learner — their training-plan months arrive ready, four weeks inside each.
            </p>
          </header>
          <div className="space-y-3 px-7 py-5">
            <input
              className={field}
              placeholder="Search learners: name, email or ID… (2+ characters)"
              value={search}
              onChange={(event) => setSearch(event.target.value)}
            />
            {hits.isLoading && needle.length >= 2 && (
              <p className="py-4 text-center text-xs text-muted-foreground">Searching…</p>
            )}
            {hits.isError && (
              <p className="py-4 text-center text-xs text-destructive">
                {hits.error instanceof Error ? hits.error.message : "Search failed."}
              </p>
            )}
            {!hits.isLoading && needle.length >= 2 && results.length === 0 && !hits.isError && (
              <p className="py-4 text-center text-xs text-muted-foreground">No learners match “{needle}”.</p>
            )}
            {results.length > 0 && (
              <ul className="divide-y divide-border rounded-lg border border-border">
                {results.map((hit) => (
                  <li key={hit.aptem_id} className="flex flex-wrap items-center gap-3 px-4 py-2.5">
                    <div className="min-w-0 flex-1">
                      <p className="truncate text-sm font-medium text-foreground">{hit.name ?? hit.aptem_id}</p>
                      <p className="truncate text-xs text-muted-foreground">
                        ID {hit.aptem_id}
                        {hit.programme_name ? ` · ${hit.programme_name}` : ""}
                        {hit.aptem_group ? ` · ${hit.aptem_group}` : ""}
                      </p>
                    </div>
                    {!hit.has_training_plan && (
                      <span className="rounded bg-warning/20 px-1.5 py-0.5 text-[10px] font-semibold text-foreground" title="No training plan found — months can be added manually">
                        no training plan
                      </span>
                    )}
                    {hit.plan_id ? (
                      <Button size="sm" variant="outline" onClick={() => void navigate({ to: "/learners/$planId", params: { planId: String(hit.plan_id) } })}>
                        Open plan
                      </Button>
                    ) : (
                      <Button size="sm" disabled={addingId === hit.aptem_id} onClick={() => void add(hit)}>
                        <UserRoundPlus className="mr-1 h-3.5 w-3.5" /> Add
                      </Button>
                    )}
                  </li>
                ))}
              </ul>
            )}
          </div>
        </section>

        <section className="rounded-lg border border-border bg-card shadow-panel">
          <header className="border-b border-border px-7 py-5">
            <h2 className="font-serif text-lg text-foreground">Learners</h2>
            <p className="mt-1 text-sm text-muted-foreground">
              One plan per learner — the months are their own training plan; you add what happens inside.
            </p>
          </header>
          {plans.isLoading && <p className="py-10 text-center text-sm text-muted-foreground">Loading learners…</p>}
          {plans.isError && (
            <p className="py-10 text-center text-sm text-destructive">
              {plans.error instanceof Error ? plans.error.message : "Could not list the learners."}
            </p>
          )}
          {!plans.isLoading && !plans.isError && items.length === 0 && (
            <p className="py-10 text-center text-sm text-muted-foreground">No learners yet — search above and add the first one.</p>
          )}
          {items.length > 0 && (
            <ul className="divide-y divide-border">
              {items.map((plan) => (
                <li key={plan.id} className="flex flex-wrap items-center gap-3 px-7 py-3">
                  <div className="min-w-0 flex-1">
                    <p className="truncate text-sm font-medium text-foreground">{plan.learner_name ?? plan.name}</p>
                    <p className="truncate text-xs text-muted-foreground">
                      ID {plan.aptem_id}
                      {plan.programme_name ? ` · ${plan.programme_name}` : ""}
                      {plan.aptem_group ? ` · ${plan.aptem_group}` : ""}
                    </p>
                  </div>
                  <span className="flex items-center gap-1 text-xs text-muted-foreground" title="Months from their training plan">
                    <CalendarDays className="h-3.5 w-3.5" /> {plan.month_count}
                  </span>
                  <span className="flex items-center gap-1 text-xs text-muted-foreground" title="Planned activities">
                    <ClipboardList className="h-3.5 w-3.5" /> {plan.activity_count}
                  </span>
                  {/* The two doors Ayman asked for: the full learner profile
                      (same one the search table opens) and the activity plan. */}
                  <Button size="sm" variant="outline" onClick={() => void navigate({ to: "/learner/$learnerId", params: { learnerId: String(plan.aptem_id) } })}>
                    <UserRound className="mr-1 h-3.5 w-3.5" /> Learner profile
                  </Button>
                  <Button size="sm" onClick={() => void navigate({ to: "/learners/$planId", params: { planId: String(plan.id) } })}>
                    <BookOpenText className="mr-1 h-3.5 w-3.5" /> Activity plan
                  </Button>
                  <button
                    type="button"
                    title="Remove learner"
                    onClick={() => void remove(plan)}
                    className="rounded p-1.5 text-destructive transition-colors hover:bg-destructive/10"
                  >
                    <Trash2 className="h-4 w-4" />
                  </button>
                </li>
              ))}
            </ul>
          )}
        </section>
      </main>
    </div>
  );
}
