// @ts-nocheck -- route types are generated by the embedded app.
// One learner's plan (the learner-first replacement of the group workspace):
// months come straight from THEIR Aptem training plan (labels untouched),
// each month holds 4 fixed weeks, and the auditor fills the weeks with
// activities via pickers. Everything authored here is projected into the
// Learner Journal / Activity Log through the ledger feed — this page is the
// ONLY place structural plan edits happen.
import { useEffect, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { createFileRoute, Link } from "@tanstack/react-router";
import {
  ArrowLeft, BookOpenText, CalendarDays, Check, ClipboardList, FileText,
  Headphones, ListChecks, LoaderCircle, Pencil, Plus, Tags, Trash2, UserRound, Video, X,
} from "lucide-react";
import Swal from "sweetalert2";
import { Button } from "@/features/audit/learner-log-pro-manual/components/ui/button";
import {
  Table, TableBody, TableCell, TableHeader, TableRow,
} from "@/features/audit/learner-log-pro-manual/components/ui/table";
import {
  addPlanActivities, archivePlanGroup, excludePlanActivity,
  getPlanGroup, getPlanMatrix, patchPlanActivity, pickAssignmentEvidence,
  pickAssignments, pickAttendanceGrid, pickKsbs, pickLmsCourseMaterials,
  pickLmsCourses, savePlanProgress, updatePlanMonths,
  type AssignmentOption, type CourseMaterial, type LmsCourse,
  type PlanActivity, type PlanGroupDetail, type PlanKsbs,
} from "@/features/audit/learner-log-pro-manual/lib/plan-api";

export const Route = createFileRoute("/learners/$planId")({
  component: LearnerPlanPage,
});

const field =
  "h-9 w-full rounded-md border border-border bg-card px-2.5 text-sm text-foreground outline-none focus:border-primary";

// Ayman's fixed order lives in the add menu + default sort — never gates.
const ADD_MENU: Array<{ category: PlanActivity["category"] | "manual"; label: string; icon: typeof Video }> = [
  { category: "attendance", label: "Attendance day", icon: CalendarDays },
  { category: "video", label: "Videos / recordings", icon: Video },
  { category: "reading+quiz", label: "Reading + Quiz", icon: BookOpenText },
  { category: "audio", label: "Audio", icon: Headphones },
  { category: "assignment", label: "Assignment", icon: ClipboardList },
  { category: "manual", label: "Manual activity", icon: Plus },
];

const CATEGORY_ORDER = { attendance: 0, video: 1, "reading+quiz": 2, audio: 3, assignment: 5 };

function categoryChip(category: string) {
  const map: Record<string, string> = {
    attendance: "bg-[#e8eef0] text-[#31505d]",
    video: "bg-[#e5f3ef] text-[#16856b]",
    "reading+quiz": "bg-[#fbf0df] text-[#8a5a10]",
    audio: "bg-secondary text-muted-foreground",
    assignment: "bg-destructive/10 text-destructive",
  };
  return map[category] ?? "bg-muted text-muted-foreground";
}

function toast(title: string) {
  void Swal.fire({ toast: true, position: "top-end", icon: "success", title, showConfirmButton: false, timer: 1600 });
}

// Data-derived strings (activity titles, suggestion text) are interpolated
// into SweetAlert2 html — always escape them first.
function esc(value: unknown) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function fail(title: string, cause: unknown) {
  void Swal.fire({ icon: "error", title, text: cause instanceof Error ? cause.message : "Unexpected error." });
}

function warnSigned(warnings: Array<{ aptem_id: string; month: string }> | undefined) {
  if (warnings?.length) {
    void Swal.fire({
      icon: "warning",
      title: "Signed month affected",
      text: `${warnings.length} signed learner-month(s) are touched by this change — review their sign-off.`,
    });
  }
}

function LearnerPlanPage() {
  const { planId } = Route.useParams();
  const id = Number(planId);
  const queryClient = useQueryClient();
  const plan = useQuery({ queryKey: ["plan-group", id], queryFn: () => getPlanGroup(id) });
  const [monthIndex, setMonthIndex] = useState<number | null>(null);
  const refresh = () => queryClient.invalidateQueries({ queryKey: ["plan-group", id] });

  if (plan.isLoading) return <Shell><p className="py-16 text-center text-sm text-muted-foreground">Loading the learner's plan…</p></Shell>;
  if (plan.isError || !plan.data) {
    return <Shell><p className="py-16 text-center text-sm text-destructive">{plan.error instanceof Error ? plan.error.message : "Could not load the plan."}</p></Shell>;
  }
  const data = plan.data;
  const member = data.members[0] ?? null;
  // Defensive: the selected month may have been deleted in the months editor.
  const activeMonth = data.months.some((item) => item.month_index === monthIndex)
    ? monthIndex
    : data.months[0]?.month_index ?? null;

  async function removeLearner() {
    const confirmation = await Swal.fire({
      icon: "warning", title: `Remove ${member?.name ?? "this learner"}?`,
      text: "Their plan stops appearing in the journal. Recorded progress is kept.",
      showCancelButton: true, confirmButtonText: "Remove", confirmButtonColor: "#dc2626",
    });
    if (!confirmation.isConfirmed) return;
    try {
      await archivePlanGroup(id);
      await queryClient.invalidateQueries({ queryKey: ["learner-plans"] });
      toast("Learner removed");
      window.location.hash = "#/learners";
    } catch (cause) {
      fail("Could not remove the learner", cause);
    }
  }

  return (
    <Shell>
      <section className="rounded-lg border border-border bg-card shadow-panel">
        <header className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-7 py-5">
          <div>
            <h1 className="font-serif text-lg text-foreground">{member?.name ?? data.name}</h1>
            <p className="mt-1 text-sm text-muted-foreground">
              ID {member?.aptem_id ?? "—"}
              {data.programme_name ? ` · ${data.programme_name}` : ""}
              {data.aptem_group ? ` · ${data.aptem_group}` : ""}
              {` · ${data.activities.filter((a) => a.included).length} activities`}
            </p>
          </div>
          <div className="flex items-center gap-2">
            {member && (
              <Link to="/learner/$learnerId" params={{ learnerId: String(member.aptem_id) }}>
                <Button size="sm" variant="outline">
                  <UserRound className="mr-1 h-3.5 w-3.5" /> Learner profile
                </Button>
              </Link>
            )}
            <Button size="sm" variant="outline" onClick={() => void removeLearner()}>
              <Trash2 className="mr-1 h-3.5 w-3.5" /> Remove learner
            </Button>
          </div>
        </header>
        {member ? (
          <PlanBody data={data} member={member} activeMonth={activeMonth} onMonth={setMonthIndex} refresh={refresh} />
        ) : (
          <p className="py-16 text-center text-sm text-destructive">This plan has no learner attached — remove it and add the learner again.</p>
        )}
      </section>
    </Shell>
  );
}

function Shell({ children }: { children: React.ReactNode }) {
  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border bg-surface">
        <div className="mx-auto flex max-w-[1700px] flex-wrap items-center justify-between gap-4 px-6 py-4">
          <div className="flex items-baseline gap-3">
            <span className="font-serif text-base text-foreground">OTJ&nbsp;Ledger</span>
            <span className="label-caps">Plan builder — learner</span>
          </div>
          <div className="flex items-center gap-4 text-xs text-muted-foreground">
            <Link to="/learners" className="inline-flex items-center gap-1 font-medium hover:underline"><ArrowLeft className="h-3.5 w-3.5" /> Learners</Link>
            <Link to="/search" className="font-medium hover:underline">Learner search</Link>
            <Link to="/journal" search={{ learner: "", period: "" }} className="font-medium hover:underline">Monthly journal</Link>
          </div>
        </div>
      </header>
      <main className="mx-auto w-full max-w-[1700px] space-y-6 px-6 py-8">{children}</main>
    </div>
  );
}

// --- Plan body ------------------------------------------------------------------

function PlanBody({ data, member, activeMonth, onMonth, refresh }: {
  data: PlanGroupDetail; member: { aptem_id: number; name: string | null };
  activeMonth: number | null; onMonth: (index: number) => void;
  refresh: () => Promise<unknown> | unknown;
}) {
  const queryClient = useQueryClient();
  const [picker, setPicker] = useState<null | { kind: string; weekSlot: number }>(null);
  const [editingMonths, setEditingMonths] = useState(false);
  const [ksbFor, setKsbFor] = useState<PlanActivity | null>(null);
  const [evidenceFor, setEvidenceFor] = useState<null | { title: string; material_ref: string | null }>(null);
  // The month's matrix carries the learner's confirmed progress + read-time
  // suggestions — this is where "حلّها ولا لأ" is answered, in place.
  const matrix = useQuery({
    queryKey: ["plan-matrix", data.id, activeMonth],
    queryFn: () => getPlanMatrix(data.id, activeMonth as number),
    enabled: activeMonth != null,
  });
  const matrixCells = matrix.data?.cells ?? {};
  const refreshMatrix = () => queryClient.invalidateQueries({ queryKey: ["plan-matrix", data.id, activeMonth] });

  async function quickSet(activity: PlanActivity, done: boolean) {
    const cell = matrixCells[`${member.aptem_id}:${activity.activity_key}`];
    const suggestion = cell?.suggestion;
    try {
      const result = await savePlanProgress({
        aptem_id: member.aptem_id,
        activity_key: activity.activity_key,
        patch: done
          ? {
              status: "completed",
              actual_hours: suggestion?.actual_hours ?? activity.planned_hours,
              completion_date: suggestion?.date ?? activity.planned_date,
              ...(activity.category === "attendance" ? { attendance_status: "attended" as const } : {}),
              reading_viewed: suggestion?.reading_viewed ?? null,
              quiz_attempted: suggestion?.quiz_attempted ?? null,
              quiz_passed: suggestion?.quiz_passed ?? null,
              suggestion_accepted: Boolean(suggestion),
            }
          : {
              status: "not_started",
              actual_hours: 0,
              ...(activity.category === "attendance" ? { attendance_status: "absent" as const } : {}),
            },
      });
      warnSigned(result.signed_warnings);
      // The write is durable at this point — paint the cell instantly and
      // let the full matrix refetch true things up in the background, so a
      // run of quick done-clicks never queues behind Neon round trips.
      const optimistic = done
        ? {
            status: "completed",
            actual_hours: suggestion?.actual_hours ?? activity.planned_hours,
            attendance_status: activity.category === "attendance" ? "attended" : null,
            completion_date: suggestion?.date ?? activity.planned_date,
            rejected: false,
            suggestion_accepted: Boolean(suggestion),
          }
        : {
            status: "not_started",
            actual_hours: 0,
            attendance_status: activity.category === "attendance" ? "absent" : null,
            completion_date: null,
            rejected: false,
            suggestion_accepted: false,
          };
      queryClient.setQueryData(["plan-matrix", data.id, activeMonth], (current) => {
        if (!current) return current;
        const key = `${member.aptem_id}:${activity.activity_key}`;
        return {
          ...current,
          cells: { ...current.cells, [key]: { ...(current.cells?.[key] ?? {}), progress: optimistic } },
        };
      });
      void refreshMatrix();
    } catch (cause) {
      fail("Could not save", cause);
    }
  }

  // Full status editor (attendance nuances, not accepted, back to suggested).
  async function editStatus(activity: PlanActivity) {
    const cell = matrixCells[`${member.aptem_id}:${activity.activity_key}`];
    const progress = cell?.progress;
    const suggestion = cell?.suggestion;
    const isAttendance = activity.category === "attendance";
    const { value: action } = await Swal.fire({
      titleText: String(member.name ?? member.aptem_id),
      html: `<p style="font-size:13px;color:#64748b">${esc(activity.title)}</p>` + (suggestion && !progress
        ? `<p style="font-size:12px;color:#b45309;margin-top:6px">Suggested from data: ${esc(suggestion.kind === "attendance" ? (suggestion.attended ? "attended" : "absent") : suggestion.completed ? "completed" : suggestion.status ?? "seen")}${suggestion.actual_hours != null ? ` · ${esc(suggestion.actual_hours)} h` : ""}</p>`
        : ""),
      input: "select",
      inputOptions: isAttendance
        ? { attended: "Attended", makeup: "Makeup", absent: "Absent", clear: "Clear (back to suggested)" }
        : { completed: "Completed (actual = planned)", not_accepted: "Not accepted", not_started: "Not started", clear: "Clear (back to suggested)" },
      inputValue: progress ? (isAttendance ? progress.attendance_status ?? "attended" : progress.status) : (suggestion?.attended || suggestion?.completed ? (isAttendance ? "attended" : "completed") : ""),
      showCancelButton: true,
      confirmButtonText: "Save",
    });
    if (!action) return;
    try {
      if (action === "clear") {
        const { clearPlanProgress } = await import("@/features/audit/learner-log-pro-manual/lib/plan-api");
        await clearPlanProgress(member.aptem_id, activity.activity_key);
      } else if (isAttendance) {
        const result = await savePlanProgress({
          aptem_id: member.aptem_id, activity_key: activity.activity_key,
          patch: {
            status: action === "absent" ? "not_started" : "completed",
            attendance_status: action,
            actual_hours: action === "absent" ? 0 : (suggestion?.actual_hours ?? activity.planned_hours),
            completion_date: activity.planned_date,
            suggestion_accepted: !!suggestion,
          },
        });
        warnSigned(result.signed_warnings);
      } else {
        const result = await savePlanProgress({
          aptem_id: member.aptem_id, activity_key: activity.activity_key,
          patch: {
            status: action,
            actual_hours: action === "completed" ? (suggestion?.actual_hours ?? activity.planned_hours) : 0,
            completion_date: action === "completed" ? (suggestion?.date ?? activity.planned_date) : null,
            reading_viewed: suggestion?.reading_viewed ?? null,
            quiz_attempted: suggestion?.quiz_attempted ?? null,
            quiz_passed: suggestion?.quiz_passed ?? null,
            suggestion_accepted: !!suggestion,
          },
        });
        warnSigned(result.signed_warnings);
      }
      await refreshMatrix();
    } catch (cause) {
      fail("Could not save the status", cause);
    }
  }

  const month = data.months.find((item) => item.month_index === activeMonth) ?? null;
  const monthActivities = data.activities
    .filter((item) => item.month_index === activeMonth && item.included)
    .sort((a, b) => a.week_slot - b.week_slot || (CATEGORY_ORDER[a.category] ?? 4) - (CATEGORY_ORDER[b.category] ?? 4) || a.position - b.position);
  // Ayman's rule: a plan month is exactly 4 weeks.
  const weeks = [1, 2, 3, 4];

  async function exclude(activity: PlanActivity) {
    const confirmation = await Swal.fire({
      icon: "warning", title: "Remove from the plan?",
      text: "Recorded progress is kept (soft removal) and the row disappears from the journal.",
      showCancelButton: true, confirmButtonText: "Remove", confirmButtonColor: "#dc2626",
    });
    if (!confirmation.isConfirmed) return;
    try {
      const result = await excludePlanActivity(activity.activity_key);
      warnSigned(result.signed_warnings);
      await refresh();
      toast(result.progress_rows_kept > 0 ? `Removed — ${result.progress_rows_kept} progress records kept` : "Removed from the plan");
    } catch (cause) {
      fail("Could not remove the activity", cause);
    }
  }

  return (
    <div className="space-y-5 px-7 py-6">
      <div className="flex flex-wrap items-center gap-2">
        {data.months.map((item) => (
          <button
            key={item.month_index}
            type="button"
            onClick={() => onMonth(item.month_index)}
            className={`rounded-full px-3 py-1.5 text-xs font-semibold transition-colors ${item.month_index === activeMonth ? "bg-[#182d48] text-white" : "bg-secondary text-muted-foreground hover:text-foreground"}`}
          >
            M{item.month_index} · {item.label}
          </button>
        ))}
        <Button size="sm" variant="outline" onClick={() => setEditingMonths(true)}>
          <CalendarDays className="mr-1 h-3.5 w-3.5" /> Edit months
        </Button>
      </div>

      {!month && <p className="py-10 text-center text-sm text-muted-foreground">No months yet — this learner has no training plan, add months manually (Edit months).</p>}

      {month && weeks.map((week) => {
        const weekActivities = monthActivities.filter((item) => item.week_slot === week);
        return (
          <div key={week} className="rounded-lg border border-border">
            <header className="flex items-center justify-between border-b border-border bg-[#eef3f8] px-5 py-2.5">
              <span className="text-xs font-semibold uppercase tracking-wider text-[#182d48]">Week {week} — {month.label}</span>
              <AddMenu onPick={(kind) => setPicker({ kind, weekSlot: week })} />
            </header>
            {weekActivities.length === 0 ? (
              <p className="px-5 py-4 text-xs text-muted-foreground">Nothing planned this week yet.</p>
            ) : (
              <div className="overflow-x-auto">
                <Table>
                  <TableHeader>
                    <PlanTableHeader />
                  </TableHeader>
                  <TableBody>
                    {weekActivities.map((activity) => (
                      <PlanActivityRow
                        key={activity.activity_key}
                        activity={activity}
                        member={member}
                        monthLabel={month.label}
                        planId={data.id}
                        cell={matrixCells[`${member.aptem_id}:${activity.activity_key}`]}
                        onQuickDone={() => quickSet(activity, true)}
                        onEditStatus={() => editStatus(activity)}
                        onKsb={() => setKsbFor(activity)}
                        onDocs={() => setEvidenceFor(activity)}
                        onRemove={() => exclude(activity)}
                        refreshAll={async () => { await Promise.all([refresh(), refreshMatrix()]); }}
                      />
                    ))}
                  </TableBody>
                </Table>
              </div>
            )}
          </div>
        );
      })}

      {picker && month && (
        <PickerModal
          data={data}
          month={month}
          weekSlot={picker.weekSlot}
          kind={picker.kind}
          onClose={() => setPicker(null)}
          onDone={async () => { setPicker(null); await refresh(); await refreshMatrix(); }}
          refresh={async () => { await refresh(); await refreshMatrix(); }}
        />
      )}
      {editingMonths && (
        <MonthsEditor data={data} onClose={() => setEditingMonths(false)} onDone={async () => { setEditingMonths(false); await refresh(); }} />
      )}
      {ksbFor && (
        <KsbEditor activity={ksbFor} onClose={() => setKsbFor(null)} onDone={async () => { setKsbFor(null); await refresh(); }} />
      )}
      {evidenceFor && <AssignmentEvidenceModal data={data} activity={evidenceFor} onClose={() => setEvidenceFor(null)} />}
    </div>
  );
}

// The classic activity-table header plus a dedicated Status column — the
// chips live there so they never stretch the Activity cell's height.
function PlanTableHeader() {
  const th = "h-12 px-4 text-left align-middle label-caps text-white";
  return (
    <TableRow className="border-0 bg-[#182d48] hover:bg-[#182d48]">
      <th className={`${th} pl-7`}>Activity ID</th>
      <th className={th}>Date</th>
      <th className={th}>Learner</th>
      <th className={th}>Month</th>
      <th className={th}>Category</th>
      <th className={th}>Activity</th>
      <th className={th}>Status</th>
      <th className="h-12 px-4 text-center align-middle label-caps text-white">Timestamp</th>
      <th className="h-12 px-4 text-right align-middle label-caps text-white">Planned</th>
      <th className="h-12 px-4 text-right align-middle label-caps text-white">Actual</th>
      <th className="h-12 px-4 pr-7 text-right align-middle label-caps text-white">Actions</th>
    </TableRow>
  );
}

// The learner's quiz attempt, rendered inline (score + every question with
// their answer marked right/wrong).
function QuizAttemptView({ attempt, state, loading }) {
  if (loading) return <p className="py-3 text-center text-xs text-muted-foreground">Loading the quiz…</p>;
  if (!attempt) {
    return <p className="py-3 text-center text-xs text-muted-foreground">{state === "not_attempted" ? "Not attempted yet — the learner has not taken this quiz." : "No quiz data."}</p>;
  }
  const questions = attempt.quiz_body?.questions ?? [];
  return (
    <>
      <p className="mb-2 text-sm font-semibold text-foreground">
        Score {attempt.score != null ? Math.round(attempt.score) : "—"}{attempt.maximum_score ? ` / ${Math.round(attempt.maximum_score)}` : ""}
        <span className={`ml-2 rounded-full px-2 py-0.5 text-[11px] font-semibold ${attempt.status === "passed" ? "bg-success/10 text-success" : "bg-destructive/10 text-destructive"}`}>{attempt.status}</span>
        {attempt.attempt_number ? <span className="ml-2 text-xs font-normal text-muted-foreground">attempt {attempt.attempt_number}</span> : null}
      </p>
      <ol className="space-y-2">
        {questions.map((question) => (
          <li key={question.question_id ?? question.question_order} className="border-t border-border pt-2 text-sm">
            <p className="font-medium text-foreground">
              <span className={`mr-1 font-bold ${question.is_correct ? "text-success" : "text-destructive"}`}>{question.is_correct ? "✓" : "✗"}</span>
              {question.question_order}. {question.question_text}
            </p>
            <p className="mt-1 text-xs text-muted-foreground">
              Answer: {(question.learner_selected_answers ?? []).join(", ") || "—"}
            </p>
            {!question.is_correct && (question.correct_answers ?? []).length > 0 && (
              <p className="mt-0.5 text-xs text-success">Correct: {question.correct_answers.join(", ")}</p>
            )}
          </li>
        ))}
      </ol>
    </>
  );
}

// One bundled material: its own header (title + the learner's state), and on
// open its reading iframe / quiz attempt — each piece shows ITS content.
function BundlePiece({ planId, member, item }: {
  planId: number; member: { aptem_id: number }; item: { ref: string; title: string };
}) {
  const [open, setOpen] = useState(false);
  const [piece, setPiece] = useState<"content" | "quiz" | null | undefined>(undefined);
  const activityId = Number(item.ref.slice(4));
  const content = useQuery({
    queryKey: ["plan-material-content", planId, activityId],
    queryFn: async () => {
      const response = await fetch(`/manual_audit_api/plan/pickers/material-content?group_id=${planId}&activity_id=${activityId}`);
      if (!response.ok) throw new Error("Could not load the material.");
      return response.json();
    },
    enabled: open,
  });
  const quiz = useQuery({
    queryKey: ["plan-material-quiz", member.aptem_id, activityId],
    queryFn: async () => {
      const response = await fetch(`/manual_audit_api/ledger/quiz-attempt/?aptem_id=${member.aptem_id}&component_id=lms:${activityId}`);
      if (!response.ok) throw new Error("Could not load the quiz.");
      return response.json();
    },
    enabled: open && Boolean(content.data?.has_quiz),
  });
  useEffect(() => {
    if (open && piece === undefined && content.data) {
      setPiece(content.data.iframe_url ? "content" : content.data.has_quiz ? "quiz" : null);
    }
  }, [open, content.data, piece]);
  const state = content.data;
  return (
    <div className="rounded-md border border-border bg-card">
      <button
        type="button"
        onClick={() => setOpen((value) => !value)}
        className="flex w-full items-center gap-2 px-3 py-2 text-left text-sm font-medium text-foreground hover:bg-secondary/60"
        aria-expanded={open}
      >
        <BookOpenText className="h-4 w-4 shrink-0 text-muted-foreground" />
        <span className="min-w-0 flex-1 truncate" title={item.title}>{item.title}</span>
        {state?.status === "completed" ? <span className="rounded-full bg-success/10 px-2 py-0.5 text-[10px] font-semibold text-success">Completed</span>
          : state?.reading_viewed || state?.status === "reading_viewed" ? <span className="rounded-full bg-amber-100 px-2 py-0.5 text-[10px] font-semibold text-amber-700">Viewed</span>
          : null}
        {state?.has_quiz && (
          <span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${state.quiz_passed ? "bg-success/10 text-success" : state.quiz_attempted ? "bg-amber-100 text-amber-700" : "bg-[#fbf0df] text-[#8a5a10]"}`}>
            quiz{state.quiz_score != null ? ` ${Math.round(state.quiz_score)}%` : ""}{state.quiz_passed ? " ✓" : ""}
          </span>
        )}
        <span className="text-xs text-muted-foreground">{open ? "▲" : "▼"}</span>
      </button>
      {open && (
        <div className="space-y-2 border-t border-border p-3">
          {content.isLoading && <p className="py-2 text-center text-xs text-muted-foreground">Loading…</p>}
          {content.data?.iframe_url && (
            <button
              type="button"
              onClick={() => setPiece(piece === "content" ? null : "content")}
              className={`flex w-full items-center gap-2 rounded-md border px-3 py-1.5 text-left text-xs font-semibold transition-colors ${piece === "content" ? "border-[#182d48] bg-[#eef3f8] text-[#182d48]" : "border-border bg-card text-foreground hover:bg-secondary"}`}
            >
              Reading <span className="ml-auto font-normal text-muted-foreground">{piece === "content" ? "▲" : "▼"}</span>
            </button>
          )}
          {piece === "content" && content.data?.iframe_url && (
            <iframe src={content.data.iframe_url} title={item.title} className="h-[70vh] w-full rounded-md border border-border bg-card" allowFullScreen />
          )}
          {content.data?.has_quiz && (
            <button
              type="button"
              onClick={() => setPiece(piece === "quiz" ? null : "quiz")}
              className={`flex w-full items-center gap-2 rounded-md border px-3 py-1.5 text-left text-xs font-semibold transition-colors ${piece === "quiz" ? "border-[#8a5a10] bg-[#fbf0df] text-[#8a5a10]" : "border-border bg-card text-foreground hover:bg-secondary"}`}
            >
              Quiz <span className="ml-auto font-normal text-muted-foreground">{piece === "quiz" ? "▲" : "▼"}</span>
            </button>
          )}
          {piece === "quiz" && content.data?.has_quiz && (
            <div className="rounded-md border border-border bg-card px-4 py-3">
              <QuizAttemptView attempt={quiz.data?.attempt ?? null} state={quiz.data?.state} loading={quiz.isLoading} />
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// The row's inline detail. Bundles unfold to their grouped materials stacked
// in one cell; single LMS rows unfold to Reading + Quiz directly.
function PlanRowExpansion({ activity, member, planId }: {
  activity: PlanActivity; member: { aptem_id: number }; planId: number;
}) {
  const isBundle = (activity.bundle_refs?.length ?? 0) > 0;
  // undefined = not initialised yet (auto-open runs once); null = the user
  // closed everything on purpose — the auto-open must NOT fight that.
  const [piece, setPiece] = useState<"content" | "quiz" | null | undefined>(undefined);
  const detail = useQuery({
    queryKey: ["plan-activity-detail", activity.activity_key, member.aptem_id],
    queryFn: async () => {
      const response = await fetch(`/manual_audit_api/ledger/activity/?activity_id=plan:${activity.activity_key}&aptem_id=${member.aptem_id}`);
      if (!response.ok) throw new Error("Could not load the activity content.");
      return response.json();
    },
    enabled: !isBundle,
  });
  const quiz = useQuery({
    queryKey: ["plan-activity-quiz", activity.activity_key, member.aptem_id],
    queryFn: async () => {
      const response = await fetch(`/manual_audit_api/ledger/quiz-attempt/?aptem_id=${member.aptem_id}&component_id=plan:${activity.activity_key}`);
      if (!response.ok) throw new Error("Could not load the quiz.");
      return response.json();
    },
    enabled: !isBundle && Boolean(detail.data?.has_quiz),
  });
  // Open the first available piece once, when the detail first arrives.
  useEffect(() => {
    if (!isBundle && piece === undefined && detail.data) {
      setPiece(detail.data.iframe_url ? "content" : detail.data.has_quiz ? "quiz" : null);
    }
  }, [detail.data, piece, isBundle]);

  if (isBundle) {
    return (
      <div className="space-y-2 rounded-lg border border-border bg-[#f7f9fc] p-4">
        {(activity.bundle_refs ?? []).map((item) => (
          <BundlePiece key={item.ref} planId={planId} member={member} item={item} />
        ))}
      </div>
    );
  }

  const contentLabel = activity.category === "video" ? "Video" : activity.category === "audio" ? "Audio" : "Reading";
  const attempt = quiz.data?.attempt ?? null;

  return (
    <div className="rounded-lg border border-border bg-[#f7f9fc] p-4">
      {detail.isLoading && <p className="py-4 text-center text-xs text-muted-foreground">Loading the content…</p>}
      {detail.isError && <p className="py-4 text-center text-xs text-destructive">{detail.error instanceof Error ? detail.error.message : "Could not load."}</p>}
      {detail.data && (
        <div className="space-y-2">
          {detail.data.iframe_url && (
            <button
              type="button"
              onClick={() => setPiece(piece === "content" ? null : "content")}
              className={`flex w-full items-center gap-2 rounded-md border px-3 py-2 text-left text-sm font-semibold transition-colors ${piece === "content" ? "border-[#182d48] bg-[#eef3f8] text-[#182d48]" : "border-border bg-card text-foreground hover:bg-secondary"}`}
            >
              <BookOpenText className="h-4 w-4" /> {contentLabel}
              <span className="ml-auto text-xs font-normal text-muted-foreground">{piece === "content" ? "▲" : "▼"}</span>
            </button>
          )}
          {piece === "content" && detail.data.iframe_url && (
            <iframe src={detail.data.iframe_url} title={activity.title} className="h-[70vh] w-full rounded-md border border-border bg-card" allowFullScreen />
          )}

          {detail.data.has_quiz && (
            <button
              type="button"
              onClick={() => setPiece(piece === "quiz" ? null : "quiz")}
              className={`flex w-full items-center gap-2 rounded-md border px-3 py-2 text-left text-sm font-semibold transition-colors ${piece === "quiz" ? "border-[#8a5a10] bg-[#fbf0df] text-[#8a5a10]" : "border-border bg-card text-foreground hover:bg-secondary"}`}
            >
              <ListChecks className="h-4 w-4" /> Quiz
              {attempt ? (
                <span className={`rounded-full px-2 py-0.5 text-[11px] font-semibold ${attempt.status === "passed" ? "bg-success/10 text-success" : "bg-amber-100 text-amber-700"}`}>
                  {attempt.score != null ? `${Math.round(attempt.score)}%` : attempt.status}{attempt.status === "passed" ? " ✓" : ""}
                </span>
              ) : quiz.data?.state === "not_attempted" ? (
                <span className="rounded-full bg-muted px-2 py-0.5 text-[11px] font-semibold text-muted-foreground">not attempted</span>
              ) : null}
              <span className="ml-auto text-xs font-normal text-muted-foreground">{piece === "quiz" ? "▲" : "▼"}</span>
            </button>
          )}
          {piece === "quiz" && detail.data.has_quiz && (
            <div className="rounded-md border border-border bg-card px-4 py-3">
              <QuizAttemptView attempt={attempt} state={quiz.data?.state} loading={quiz.isLoading} />
            </div>
          )}

          {!detail.data.iframe_url && !detail.data.has_quiz && (
            <p className="py-3 text-center text-xs text-muted-foreground">No embeddable content on this row.</p>
          )}
        </div>
      )}
    </div>
  );
}

// One plan activity as a classic activity-log table row. The pencil flips
// the WHOLE row into inputs (date / title / subtitle / planned / actual) —
// the single edit surface. Once a row is done there is no quick undo action;
// status changes go through the Timestamp menu or the actual-hours field.
function PlanActivityRow({ activity, member, monthLabel, cell, planId, onQuickDone, onEditStatus, onKsb, onDocs, onRemove, refreshAll }: {
  activity: PlanActivity;
  member: { aptem_id: number; name: string | null };
  monthLabel: string;
  planId: number;
  cell: { progress?: Record<string, unknown>; suggestion?: Record<string, unknown> } | undefined;
  onQuickDone: () => void;
  onEditStatus: () => void;
  onKsb: () => void;
  onDocs: () => void;
  onRemove: () => void;
  refreshAll: () => Promise<void>;
}) {
  const progress = cell?.progress && !cell.progress.rejected ? cell.progress : null;
  const suggestion = cell?.suggestion;
  const done = progress?.status === "completed";
  const notAccepted = progress?.status === "not_accepted";
  const absent = activity.category === "attendance" && progress?.attendance_status === "absent";
  const suggestedDone = !progress && suggestion && (suggestion.completed || suggestion.attended);
  // Same display contract as the classic activity table.
  const actual = progress?.actual_hours != null
    ? Number(progress.actual_hours)
    : suggestedDone && suggestion?.actual_hours != null ? Number(suggestion.actual_hours) : 0;
  const timestampDisplay = activity.category === "attendance"
    ? (progress
      ? (progress.attendance_status === "absent" ? "not attended" : "attended")
      : suggestedDone ? "attended" : "—")
    : actual > 0 ? "input" : "—";
  const ghost = !progress && Boolean(suggestedDone);
  const currentActual = progress?.actual_hours != null ? String(Number(progress.actual_hours)) : "";
  const ksbCount = (activity.ksbs?.K?.length ?? 0) + (activity.ksbs?.S?.length ?? 0) + (activity.ksbs?.B?.length ?? 0);

  const [editing, setEditing] = useState(false);
  const [busy, setBusy] = useState(false);
  // Clicking the title unfolds the row: reading + quiz stacked in one cell.
  const [expanded, setExpanded] = useState(false);
  // Saving feedback for the one-click confirm: the button spins until the
  // progress write lands, so the auditor SEES it saving.
  const [confirming, setConfirming] = useState(false);
  const [draft, setDraft] = useState(() => ({
    title: activity.title,
    subtitle: activity.subtitle ?? "",
    date: activity.planned_date ?? "",
    planned: String(activity.planned_hours),
    actual: currentActual,
  }));

  async function handleQuickDone() {
    setConfirming(true);
    try {
      await onQuickDone();
    } finally {
      setConfirming(false);
    }
  }
  const rowInput = "h-8 rounded-md border border-border bg-card px-2 text-xs outline-none focus:border-primary";

  function startEditing() {
    setDraft({
      title: activity.title,
      subtitle: activity.subtitle ?? "",
      date: activity.planned_date ?? "",
      planned: String(activity.planned_hours),
      actual: currentActual,
    });
    setEditing(true);
  }

  async function save() {
    if (!draft.title.trim()) {
      return void Swal.fire({ icon: "error", title: "Check the row", text: "Enter an activity name." });
    }
    const plannedNumber = Number(draft.planned);
    if (!Number.isFinite(plannedNumber) || plannedNumber < 0 || plannedNumber > 50) {
      return void Swal.fire({ icon: "error", title: "Check the row", text: "Planned hours must be between 0 and 50." });
    }
    const actualRaw = draft.actual.trim();
    const actualNumber = Number(actualRaw);
    if (actualRaw !== "" && (!Number.isFinite(actualNumber) || actualNumber < 0 || actualNumber > 50)) {
      return void Swal.fire({ icon: "error", title: "Check the row", text: "Actual hours must be between 0 and 50." });
    }
    setBusy(true);
    try {
      const result = await patchPlanActivity(activity.activity_key, {
        title: draft.title.trim(),
        subtitle: draft.subtitle.trim() || null,
        planned_hours: plannedNumber,
        planned_date: draft.date || null,
      });
      warnSigned(result.signed_warnings);
      // The learner's OWN hours: empty leaves the progress untouched, a
      // number confirms completion with those hours (0 = deliberately not done).
      if (actualRaw !== "" && actualRaw !== currentActual) {
        const progressResult = await savePlanProgress({
          aptem_id: member.aptem_id,
          activity_key: activity.activity_key,
          patch: actualNumber > 0
            ? {
                status: "completed",
                actual_hours: actualNumber,
                completion_date: progress?.completion_date ?? draft.date ?? activity.planned_date,
                ...(activity.category === "attendance" ? { attendance_status: "attended" as const } : {}),
              }
            : {
                status: "not_started",
                actual_hours: 0,
                ...(activity.category === "attendance" ? { attendance_status: "absent" as const } : {}),
              },
        });
        warnSigned(progressResult.signed_warnings);
      }
      await refreshAll();
      setEditing(false);
      toast("Activity updated");
    } catch (cause) {
      fail("Could not update the activity", cause);
    } finally {
      setBusy(false);
    }
  }

  if (editing) {
    return (
      <TableRow className="bg-primary/5 hover:bg-primary/5">
        <TableCell className="max-w-44 truncate pl-7 font-mono text-xs" title={`plan:${activity.activity_key}`}>
          plan:{activity.activity_key.slice(0, 8)}
        </TableCell>
        <TableCell><input type="date" value={draft.date} onChange={(e) => setDraft((d) => ({ ...d, date: e.target.value }))} className={`${rowInput} w-36`} /></TableCell>
        <TableCell className="whitespace-nowrap text-sm font-medium">{member.name ?? member.aptem_id}</TableCell>
        <TableCell className="whitespace-nowrap text-xs text-muted-foreground">{monthLabel}</TableCell>
        <TableCell className="whitespace-nowrap text-xs text-muted-foreground">{activity.category}</TableCell>
        <TableCell className="min-w-64 space-y-1">
          <input value={draft.title} onChange={(e) => setDraft((d) => ({ ...d, title: e.target.value }))} placeholder="Title (the lecture)" maxLength={500} className={`${rowInput} w-full min-w-56`} />
          <input value={draft.subtitle} onChange={(e) => setDraft((d) => ({ ...d, subtitle: e.target.value }))} placeholder="Subtitle (the module)" maxLength={500} className={`${rowInput} w-full min-w-56`} />
        </TableCell>
        <TableCell className="whitespace-nowrap text-xs text-muted-foreground">—</TableCell>
        <TableCell className="whitespace-nowrap text-center font-mono text-xs text-muted-foreground">{timestampDisplay}</TableCell>
        <TableCell><input type="number" min="0" max="50" step="0.25" value={draft.planned} onChange={(e) => setDraft((d) => ({ ...d, planned: e.target.value }))} className={`${rowInput} w-20 text-right`} title="Planned hours" /></TableCell>
        <TableCell><input type="number" min="0" max="50" step="0.25" value={draft.actual} onChange={(e) => setDraft((d) => ({ ...d, actual: e.target.value }))} placeholder="—" className={`${rowInput} w-20 text-right`} title="Actual hours (yours) — empty leaves the status untouched" /></TableCell>
        <TableCell className="pr-7 text-right">
          <div className="flex justify-end gap-1">
            <button type="button" onClick={() => void save()} disabled={busy} className="rounded-md bg-primary p-1.5 text-primary-foreground disabled:opacity-50" title="Save row" aria-label="Save activity"><Check className="h-3.5 w-3.5" /></button>
            <button type="button" onClick={() => setEditing(false)} disabled={busy} className="rounded-md border border-border p-1.5 hover:bg-secondary disabled:opacity-50" title="Cancel" aria-label="Cancel editing"><X className="h-3.5 w-3.5" /></button>
          </div>
        </TableCell>
      </TableRow>
    );
  }

  return (
    <>
    <TableRow>
      <TableCell className="max-w-44 truncate pl-7 font-mono text-xs" title={`plan:${activity.activity_key}`}>
        plan:{activity.activity_key.slice(0, 8)}
      </TableCell>
      <TableCell className="whitespace-nowrap font-mono text-xs text-muted-foreground">
        {(done || notAccepted ? progress?.completion_date : null) ?? activity.planned_date ?? "—"}
      </TableCell>
      <TableCell className="whitespace-nowrap text-sm font-medium">{member.name ?? member.aptem_id}</TableCell>
      <TableCell className="whitespace-nowrap text-xs text-muted-foreground">{monthLabel}</TableCell>
      <TableCell className="whitespace-nowrap text-xs text-muted-foreground">{activity.category}</TableCell>
      <TableCell className="min-w-64 max-w-[38rem] text-sm">
        {/* The title unfolds the row in place: reading + quiz grouped in one
            cell beneath it, each piece rendering its own iframe/content. */}
        {((activity.material_ref ?? "").startsWith("lms:") || (activity.bundle_refs?.length ?? 0) > 0) ? (
          <button
            type="button"
            onClick={() => setExpanded((value) => !value)}
            className="text-left font-medium text-foreground hover:text-primary hover:underline"
            aria-expanded={expanded}
          >
            {activity.title} <span className="text-xs text-muted-foreground">{expanded ? "▲" : "▼"}</span>
          </button>
        ) : (
          <p className="font-medium text-foreground">{activity.title}</p>
        )}
        {activity.subtitle ? <p className="mt-1 text-xs text-muted-foreground">{activity.subtitle}</p> : null}
      </TableCell>
      <TableCell className="whitespace-nowrap">
        {done ? <span className="rounded-full bg-success/15 px-2 py-0.5 text-[10px] font-semibold text-success">Complete</span>
        : suggestedDone ? <span className="rounded-full bg-amber-100 px-2 py-0.5 text-[10px] font-semibold text-amber-700" title="Suggested from data — confirm it">Suggested ✓?</span>
        : notAccepted ? <span className="rounded-full bg-destructive/10 px-2 py-0.5 text-[10px] font-semibold text-destructive">Not accepted</span>
        : absent ? <span className="rounded-full bg-destructive/10 px-2 py-0.5 text-[10px] font-semibold text-destructive">Absent</span>
        : <span className="text-xs text-muted-foreground">—</span>}
      </TableCell>
      <TableCell className="whitespace-nowrap text-center font-mono text-xs">
        <button
          type="button"
          onClick={onEditStatus}
          title="Change the status (attended / makeup / not accepted / clear)"
          className={`rounded px-1.5 py-0.5 transition-colors hover:bg-secondary ${ghost ? "text-amber-600" : "text-muted-foreground"}`}
        >
          {timestampDisplay}
        </button>
      </TableCell>
      <TableCell className="text-right font-mono text-sm">{activity.planned_hours}</TableCell>
      <TableCell className={`text-right font-mono text-sm ${actual > 0 ? (ghost ? "text-amber-600" : "text-success") : "text-muted-foreground"}`}>
        {actual > 0 ? actual : "—"}
      </TableCell>
      <TableCell className="pr-7 text-right">
        <div className="flex justify-end gap-1">
          {!progress && (
            <button
              type="button"
              onClick={() => void handleQuickDone()}
              disabled={confirming}
              className="inline-flex items-center gap-1 rounded-md border border-success/40 bg-success/10 px-2 py-1 text-[11px] font-semibold text-success hover:bg-success/20 disabled:opacity-70"
              title={suggestedDone ? "Confirm the suggested completion" : "Mark as done"}
            >
              {confirming && <LoaderCircle className="h-3 w-3 animate-spin" />}
              {confirming ? "saving…" : suggestedDone ? "confirm" : "done"}
            </button>
          )}
          {(activity.material_ref ?? "").startsWith("asg:") && (
            <button type="button" title="Submitted documents" onClick={onDocs} className="rounded-md border border-border p-1.5 hover:bg-secondary"><FileText className="h-3.5 w-3.5" /></button>
          )}
          <button type="button" title="KSBs" onClick={onKsb} className="rounded-md border border-border p-1.5 hover:bg-secondary">
            <Tags className="h-3.5 w-3.5" />
            {ksbCount > 0 && <span className="ml-0.5 align-middle text-[10px] font-semibold">{ksbCount}</span>}
          </button>
          <button type="button" title="Edit the whole row" onClick={startEditing} className="rounded-md border border-border p-1.5 hover:bg-secondary" aria-label="Edit activity"><Pencil className="h-3.5 w-3.5" /></button>
          <button type="button" title="Remove" onClick={onRemove} className="rounded-md border border-destructive/30 p-1.5 text-destructive hover:bg-destructive/10" aria-label="Remove activity"><Trash2 className="h-3.5 w-3.5" /></button>
        </div>
      </TableCell>
    </TableRow>
    {expanded && (
      <TableRow className="hover:bg-transparent">
        <TableCell colSpan={11} className="bg-[#fbfcfe] px-7 py-3">
          <PlanRowExpansion activity={activity} member={member} planId={planId} />
        </TableCell>
      </TableRow>
    )}
    </>
  );
}

function AddMenu({ onPick }: { onPick: (kind: string) => void }) {
  const [open, setOpen] = useState(false);
  return (
    <span className="relative">
      <Button size="sm" variant="outline" onClick={() => setOpen((value) => !value)}>
        <Plus className="mr-1 h-3.5 w-3.5" /> Add
      </Button>
      {open && (
        <span className="absolute right-0 top-9 z-20 block w-56 rounded-md border border-border bg-card py-1 shadow-panel">
          {ADD_MENU.map((item) => (
            <button
              key={item.category}
              type="button"
              onClick={() => { setOpen(false); onPick(item.category); }}
              className="flex w-full items-center gap-2 px-3 py-2 text-left text-sm text-foreground hover:bg-secondary"
            >
              <item.icon className="h-4 w-4 text-muted-foreground" /> {item.label}
            </button>
          ))}
        </span>
      )}
    </span>
  );
}

// --- Picker modal ---------------------------------------------------------------

function Modal({ title, onClose, children, wide = false }: {
  title: string; onClose: () => void; children: React.ReactNode; wide?: boolean;
}) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onClick={onClose}>
      <div
        className={`max-h-[85vh] w-full ${wide ? "max-w-4xl" : "max-w-2xl"} overflow-auto rounded-lg border border-border bg-card shadow-panel`}
        onClick={(event) => event.stopPropagation()}
      >
        <header className="sticky top-0 flex items-center justify-between border-b border-border bg-card px-6 py-4">
          <h2 className="font-serif text-base text-foreground">{title}</h2>
          <button type="button" onClick={onClose} className="rounded p-1.5 text-muted-foreground hover:bg-secondary"><X className="h-4 w-4" /></button>
        </header>
        <div className="px-6 py-4">{children}</div>
      </div>
    </div>
  );
}

function PickerModal({ data, month, weekSlot, kind, onClose, onDone, refresh }: {
  data: PlanGroupDetail; month: { month_index: number; calendar_month: string; label: string };
  weekSlot: number; kind: string; onClose: () => void; onDone: () => Promise<void>;
  refresh: () => Promise<void>;
}) {
  const [saving, setSaving] = useState(false);

  async function submit(activities: Parameters<typeof addPlanActivities>[0]["activities"], assignmentRefs?: Parameters<typeof addPlanActivities>[0]["assignment_refs"], keepOpen = false) {
    setSaving(true);
    try {
      const result = await addPlanActivities({ group_id: data.id, activities, assignment_refs: assignmentRefs });
      if (result.duplicate_refs.length) {
        void Swal.fire({ icon: "info", title: "Already in the plan", text: `${result.duplicate_refs.length} of the selected items were already planned — they were added again on purpose only if you selected them twice.` });
      }
      warnSigned(result.signed_warnings);
      toast(`${result.activity_keys.length} added to Week ${weekSlot}`);
      // The attendance picker stays open (add/remove workflow); others close.
      if (keepOpen) await refresh(); else await onDone();
    } catch (cause) {
      fail("Could not add to the plan", cause);
    } finally {
      setSaving(false);
    }
  }

  const add = (activities, assignmentRefs?) => submit(activities, assignmentRefs);

  if (kind === "attendance") {
    return (
      <AttendancePicker
        data={data} month={month} weekSlot={weekSlot} saving={saving}
        onAdd={(activities) => submit(activities, undefined, true)}
        refresh={refresh} onClose={onClose}
      />
    );
  }
  if (kind === "video" || kind === "reading+quiz" || kind === "audio") {
    return <CourseMaterialsPicker data={data} month={month} weekSlot={weekSlot} type={kind} saving={saving} onAdd={add} onClose={onClose} />;
  }
  if (kind === "assignment") {
    return <AssignmentPicker data={data} month={month} weekSlot={weekSlot} saving={saving} onAdd={add} onClose={onClose} />;
  }
  return <ManualPicker month={month} weekSlot={weekSlot} saving={saving} onAdd={add} onClose={onClose} />;
}

// The plan's week slots are 7-day bands from the month anchor (week 1 starts
// at the 1st, week 4 runs to the end of the month) — the picker opens scoped
// to the week being edited.
function weekDateRange(month: { calendar_month: string; anchor_date?: string | null }, weekSlot: number) {
  const base = month.anchor_date
    ? new Date(`${month.anchor_date}T00:00:00`)
    : new Date(`${month.calendar_month}-01T00:00:00`);
  const iso = (d: Date) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
  const from = new Date(base);
  from.setDate(from.getDate() + (weekSlot - 1) * 7);
  const fromIso = weekSlot === 1 ? `${month.calendar_month}-01` : iso(from);
  if (weekSlot >= 4) return { from: fromIso, to: `${month.calendar_month}-31` };
  const to = new Date(from);
  to.setDate(to.getDate() + 6);
  return { from: fromIso, to: iso(to) };
}

// England & Wales bank holidays (GOV.UK list, 2024–2027). Planning a session
// on one of these dates raises an alarm before it is added.
const ENGLAND_BANK_HOLIDAYS: Record<string, string> = {
  "2024-01-01": "New Year's Day", "2024-03-29": "Good Friday", "2024-04-01": "Easter Monday",
  "2024-05-06": "Early May bank holiday", "2024-05-27": "Spring bank holiday",
  "2024-08-26": "Summer bank holiday", "2024-12-25": "Christmas Day", "2024-12-26": "Boxing Day",
  "2025-01-01": "New Year's Day", "2025-04-18": "Good Friday", "2025-04-21": "Easter Monday",
  "2025-05-05": "Early May bank holiday", "2025-05-26": "Spring bank holiday",
  "2025-08-25": "Summer bank holiday", "2025-12-25": "Christmas Day", "2025-12-26": "Boxing Day",
  "2026-01-01": "New Year's Day", "2026-04-03": "Good Friday", "2026-04-06": "Easter Monday",
  "2026-05-04": "Early May bank holiday", "2026-05-25": "Spring bank holiday",
  "2026-08-31": "Summer bank holiday", "2026-12-25": "Christmas Day", "2026-12-28": "Boxing Day (substitute)",
  "2027-01-01": "New Year's Day", "2027-03-26": "Good Friday", "2027-03-29": "Easter Monday",
  "2027-05-03": "Early May bank holiday", "2027-05-31": "Spring bank holiday",
  "2027-08-30": "Summer bank holiday", "2027-12-27": "Christmas Day (substitute)", "2027-12-28": "Boxing Day (substitute)",
};

function AttendancePicker({ data, month, weekSlot, saving, onAdd, refresh, onClose }) {
  // THIS learner's own attendance, like the student portal's page
  // (Day / Module / Lecture / Status). Month view by default; one click for
  // the week being edited or the learner's whole history. Each row adds to
  // (or removes from) the week the picker was opened from.
  const [scope, setScope] = useState<"week" | "month" | "all">("month");
  const [search, setSearch] = useState("");
  const [selected, setSelected] = useState<Record<string, boolean>>({});
  const [removing, setRemoving] = useState<string | null>(null);
  const member = data.members[0];
  const gridMonth = scope === "all" ? "all" : month.calendar_month;
  const grid = useQuery({
    queryKey: ["plan-att-grid", data.id, gridMonth],
    queryFn: () => pickAttendanceGrid(data.id, gridMonth, false),
  });

  const learnerName = member?.name ?? data.name;
  const range = weekDateRange(month, weekSlot);
  const needle = search.trim().toLowerCase();
  const cells = grid.data?.cells ?? {};
  // Attendance rows already planned, keyed by their session ref — these
  // show "In plan" with a Remove button instead of Add.
  const planned = new Map(
    data.activities
      .filter((a) => a.included && a.category === "attendance" && a.material_ref)
      .map((a) => [a.material_ref, a]),
  );
  const rows = (grid.data?.days ?? [])
    .filter((day) =>
      (scope !== "week" || (day.date >= range.from && day.date <= range.to))
      && (!needle
        || day.module.toLowerCase().includes(needle)
        || String(day.lecture ?? "").toLowerCase().includes(needle)
        || day.date.includes(needle)))
    .map((day) => ({
      ...day,
      cell: member ? cells[`${member.aptem_id}:${day.session_ref}`] ?? null : null,
      holiday: ENGLAND_BANK_HOLIDAYS[day.date] ?? null,
      plannedActivity: planned.get(day.session_ref) ?? null,
    }));
  const chosen = rows.filter((day) => selected[day.session_ref] && !day.plannedActivity);
  const selectable = rows.filter((day) => !day.plannedActivity);
  const allVisibleSelected = selectable.length > 0 && selectable.every((day) => selected[day.session_ref]);

  async function confirmHolidays(days) {
    // England bank holiday alarm — planning a session on one needs a nod.
    const holidays = days.filter((day) => day.holiday);
    if (!holidays.length) return true;
    const confirmation = await Swal.fire({
      icon: "warning",
      title: "England bank holiday",
      html:
        holidays.map((day) => `<p style="font-size:13px;font-weight:600">${esc(day.date)} — ${esc(day.holiday)}</p>`).join("")
        + `<p style="font-size:13px;margin-top:8px">The selected day(s) fall on an England bank holiday. Add anyway?</p>`,
      showCancelButton: true,
      confirmButtonText: "Add anyway",
    });
    return confirmation.isConfirmed;
  }

  async function addDays(days) {
    if (!days.length || !(await confirmHolidays(days))) return;
    // The lecture is the headline; the module sits underneath it.
    await onAdd(days.map((day) => ({
      category: "attendance",
      title: day.lecture ?? day.module,
      subtitle: day.lecture ? day.module : null,
      month_index: month.month_index,
      week_slot: weekSlot,
      material_ref: day.session_ref,
      planned_hours: day.default_hours,
      planned_date: day.date,
    })));
    setSelected({});
  }

  async function removeDay(activity) {
    setRemoving(activity.activity_key);
    try {
      const result = await excludePlanActivity(activity.activity_key);
      warnSigned(result.signed_warnings);
      toast("Removed from the plan");
      await refresh();
    } catch (cause) {
      fail("Could not remove the day", cause);
    } finally {
      setRemoving(null);
    }
  }

  return (
    <Modal title={`Attendance — ${learnerName} — Week ${weekSlot} · ${month.label}`} onClose={onClose} wide>
      <div className="mb-3 flex flex-wrap items-center gap-3">
        <div className="flex rounded-md border border-border">
          {([["week", `Week ${weekSlot}`], ["month", month.label], ["all", "All records"]] as const).map(([value, label]) => (
            <button
              key={value}
              type="button"
              onClick={() => setScope(value)}
              title={value === "week" ? `${range.from} → ${range.to}` : undefined}
              className={`px-3 py-1.5 text-xs font-semibold transition-colors ${scope === value ? "bg-[#182d48] text-white" : "text-muted-foreground hover:text-foreground"}`}
            >
              {label}
            </button>
          ))}
        </div>
        <input className={`${field} max-w-56`} placeholder="Search module / lecture / date…" value={search} onChange={(e) => setSearch(e.target.value)} />
        <label className="flex items-center gap-2 text-xs text-muted-foreground">
          <input
            type="checkbox"
            checked={allVisibleSelected}
            onChange={(e) => setSelected((current) => {
              const next = { ...current };
              for (const day of selectable) next[day.session_ref] = e.target.checked;
              return next;
            })}
          />
          Select all
        </label>
        <span className="flex-1" />
        <Button size="sm" disabled={saving || chosen.length === 0} onClick={() => void addDays(chosen)}>
          Add {chosen.length || ""} selected to Week {weekSlot}
        </Button>
      </div>
      {grid.isLoading && <p className="py-8 text-center text-sm text-muted-foreground">Loading the attendance…</p>}
      {!grid.isLoading && rows.length === 0 && (
        <p className="py-8 text-center text-sm text-muted-foreground">
          No attendance records for {learnerName}
          {scope === "week" ? ` in Week ${weekSlot} (${range.from} → ${range.to})` : scope === "month" ? ` in ${month.label}` : ""}
          {needle ? " matching the search" : ""}
          {scope !== "all" && (
            <>
              {" — "}
              <button type="button" className="font-semibold underline" onClick={() => setScope("all")}>
                show all their records
              </button>
            </>
          )}
        </p>
      )}
      {rows.length > 0 && (
        <div className="max-h-[60vh] overflow-auto rounded-lg border border-border">
          <table className="w-full border-collapse text-sm">
            <thead className="sticky top-0 z-10">
              <tr className="bg-[#182d48] text-left text-xs uppercase tracking-wider text-white">
                <th className="w-10 px-3 py-2"></th>
                <th className="px-3 py-2 font-semibold">Day</th>
                <th className="px-3 py-2 font-semibold">Module</th>
                <th className="px-3 py-2 font-semibold">Lecture</th>
                <th className="px-3 py-2 font-semibold">Status</th>
                <th className="px-3 py-2 text-right font-semibold">Plan</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((day) => {
                const attended = day.cell ? Boolean(day.cell.attended) : null;
                const inPlan = day.plannedActivity;
                return (
                  <tr
                    key={day.session_ref}
                    className={`border-t border-border transition-colors ${selected[day.session_ref] && !inPlan ? "bg-[#eef3f8]" : "odd:bg-[#f7f9fc]"}`}
                  >
                    <td className="px-3 py-2.5">
                      {!inPlan && (
                        <input
                          type="checkbox"
                          checked={!!selected[day.session_ref]}
                          onChange={(e) => setSelected((s) => ({ ...s, [day.session_ref]: e.target.checked }))}
                        />
                      )}
                    </td>
                    <td className="whitespace-nowrap px-3 py-2.5 font-mono text-xs font-semibold text-foreground">
                      {day.date}
                      {day.holiday && (
                        <span className="ml-2 rounded bg-warning/20 px-1.5 py-0.5 font-sans text-[10px] font-semibold text-foreground ring-1 ring-warning/40" title={day.holiday}>
                          ⚠ {day.holiday}
                        </span>
                      )}
                    </td>
                    <td className="max-w-64 truncate px-3 py-2.5 text-foreground" title={day.module}>{day.module}</td>
                    <td className="max-w-64 truncate px-3 py-2.5 text-muted-foreground" title={day.lecture ?? ""}>{day.lecture ?? "—"}</td>
                    <td className="px-3 py-2.5">
                      {attended == null ? (
                        <span className="rounded-full bg-muted px-2.5 py-1 text-xs font-semibold text-muted-foreground">No record</span>
                      ) : attended ? (
                        <span className="rounded-full bg-success/10 px-2.5 py-1 text-xs font-semibold text-success">Present</span>
                      ) : (
                        <span className="rounded-full bg-destructive/10 px-2.5 py-1 text-xs font-semibold text-destructive">Absent</span>
                      )}
                    </td>
                    <td className="whitespace-nowrap px-3 py-2.5 text-right">
                      {inPlan ? (
                        <span className="inline-flex items-center gap-2">
                          <span className="rounded-full bg-success/10 px-2 py-0.5 text-[11px] font-semibold text-success">In plan · W{inPlan.week_slot}</span>
                          <button
                            type="button"
                            disabled={removing === inPlan.activity_key}
                            onClick={() => void removeDay(inPlan)}
                            className="rounded border border-destructive/40 bg-destructive/10 px-2 py-1 text-[11px] font-semibold text-destructive hover:bg-destructive/20 disabled:opacity-50"
                          >
                            Remove
                          </button>
                        </span>
                      ) : (
                        <button
                          type="button"
                          disabled={saving}
                          onClick={() => void addDays([day])}
                          className="rounded border border-success/40 bg-success/10 px-2 py-1 text-[11px] font-semibold text-success hover:bg-success/20 disabled:opacity-50"
                        >
                          + Add to W{weekSlot}
                        </button>
                      )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
      <p className="mt-2 text-xs text-muted-foreground">
        {learnerName}&apos;s own records. Add puts the day into Week {weekSlot} with the module and lecture name; Remove takes it back out (progress is kept).
      </p>
    </Modal>
  );
}

// Enrolled courses -> pick a course -> its lectures laid out week by week
// (the mirror has no section names, so weeks come from each material's date).
// Selecting lectures adds them to the plan week the picker was opened from.
function weekLabelOf(dateIso: string | null) {
  if (!dateIso) return "Undated";
  const d = new Date(`${dateIso}T00:00:00`);
  d.setDate(d.getDate() - ((d.getDay() + 6) % 7)); // back to Monday
  return `Week of ${d.toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })}`;
}

function materialStatusChip(item: CourseMaterial) {
  if (item.status === "completed") return { label: "Completed", cls: "bg-success/10 text-success" };
  if (item.quiz_passed) return { label: "Quiz passed", cls: "bg-success/10 text-success" };
  if (item.quiz_attempted) return { label: "Quiz attempted", cls: "bg-amber-100 text-amber-700" };
  if (item.reading_viewed || item.status === "reading_viewed") return { label: "Viewed", cls: "bg-amber-100 text-amber-700" };
  if (item.video_completed) return { label: "Video completed", cls: "bg-success/10 text-success" };
  return { label: "Not started", cls: "bg-muted text-muted-foreground" };
}

function CourseMaterialsPicker({ data, month, weekSlot, type, saving, onAdd, onClose }) {
  const [course, setCourse] = useState<LmsCourse | null>(null);
  const [typeFilter, setTypeFilter] = useState<string>(type);
  const [search, setSearch] = useState("");
  const [selected, setSelected] = useState<Record<string, CourseMaterial>>({});
  const courses = useQuery({
    queryKey: ["plan-lms-courses", data.id],
    queryFn: () => pickLmsCourses(data.id),
  });
  const materials = useQuery({
    queryKey: ["plan-course-materials", data.id, course?.course_id],
    queryFn: () => pickLmsCourseMaterials(data.id, course!.course_id),
    enabled: course != null,
  });

  const needle = search.trim().toLowerCase();
  const items = (materials.data?.items ?? []).filter(
    (item) =>
      (typeFilter === "all" || item.category === typeFilter)
      && (!needle || item.title.toLowerCase().includes(needle) || (item.date ?? "").includes(needle)),
  );
  // Week sections in date order, exactly how the course page reads.
  const weeks: Array<{ label: string; items: CourseMaterial[] }> = [];
  for (const item of items) {
    const label = weekLabelOf(item.date);
    const last = weeks[weeks.length - 1];
    if (last && last.label === label) last.items.push(item);
    else weeks.push({ label, items: [item] });
  }
  const chosen = Object.values(selected);

  return (
    <Modal title={course ? `${course.name} — pick for Week ${weekSlot}` : `Enrolled courses — Week ${weekSlot}, ${month.label}`} onClose={onClose} wide>
      {!course && (
        <>
          {courses.isLoading && <p className="py-8 text-center text-sm text-muted-foreground">Loading the courses…</p>}
          {!courses.isLoading && (courses.data?.items ?? []).length === 0 && (
            <p className="py-8 text-center text-sm text-muted-foreground">This learner is not enrolled in any course.</p>
          )}
          <ul className="divide-y divide-border">
            {(courses.data?.items ?? []).map((item) => (
              <li key={item.course_id}>
                <button
                  type="button"
                  onClick={() => { setCourse(item); setSelected({}); }}
                  className="flex w-full items-center gap-3 px-2 py-3 text-left transition-colors hover:bg-secondary/60"
                >
                  <BookOpenText className="h-5 w-5 shrink-0 text-muted-foreground" />
                  <span className="min-w-0 flex-1">
                    <span className="block truncate text-sm font-medium text-foreground">{item.name}</span>
                    <span className="text-xs text-muted-foreground">{item.materials} lectures</span>
                  </span>
                  <span className="text-xs font-semibold text-muted-foreground">Open →</span>
                </button>
              </li>
            ))}
          </ul>
        </>
      )}

      {course && (
        <>
          <div className="mb-3 flex flex-wrap items-center gap-2">
            <Button size="sm" variant="outline" onClick={() => { setCourse(null); setSelected({}); }}>
              <ArrowLeft className="mr-1 h-3.5 w-3.5" /> Courses
            </Button>
            <div className="flex rounded-md border border-border">
              {([["video", "Videos"], ["reading+quiz", "Reading+Quiz"], ["audio", "Audio"], ["all", "All"]] as const).map(([value, label]) => (
                <button key={value} type="button" onClick={() => setTypeFilter(value)}
                  className={`px-3 py-1.5 text-xs font-semibold transition-colors ${typeFilter === value ? "bg-[#182d48] text-white" : "text-muted-foreground hover:text-foreground"}`}>
                  {label}
                </button>
              ))}
            </div>
            <input className={`${field} max-w-56`} placeholder="Search lecture / date…" value={search} onChange={(e) => setSearch(e.target.value)} />
            <span className="flex-1" />
            <Button size="sm" disabled={saving || chosen.length === 0} onClick={() => {
              // Reading+Quiz picks bundle into ONE row with ONE shared hours
              // figure; videos/audio stay one row each.
              const readingQuiz = chosen.filter((item) => item.category === "reading+quiz");
              const rest = chosen.filter((item) => item.category !== "reading+quiz");
              const activities = rest.map((item) => ({
                category: item.category,
                title: item.title,
                month_index: month.month_index,
                week_slot: weekSlot,
                material_ref: item.material_ref,
                planned_hours: item.suggested_hours ?? 0,
              }));
              if (readingQuiz.length === 1) {
                const item = readingQuiz[0];
                activities.push({
                  category: "reading+quiz",
                  title: item.title,
                  month_index: month.month_index,
                  week_slot: weekSlot,
                  material_ref: item.material_ref,
                  planned_hours: item.suggested_hours ?? 0,
                });
              } else if (readingQuiz.length > 1) {
                activities.push({
                  category: "reading+quiz",
                  title: `Reading + Quiz (${readingQuiz.length})`,
                  subtitle: course?.name ?? null,
                  month_index: month.month_index,
                  week_slot: weekSlot,
                  material_ref: null,
                  planned_hours: Math.round(readingQuiz.reduce((sum, item) => sum + (item.suggested_hours ?? 0), 0) * 100) / 100,
                  bundle_refs: readingQuiz.map((item) => ({ ref: item.material_ref, title: item.title })),
                });
              }
              void onAdd(activities);
            }}>Add {chosen.length || ""} selected to Week {weekSlot}</Button>
          </div>
          {materials.isLoading && <p className="py-8 text-center text-sm text-muted-foreground">Loading the course…</p>}
          {!materials.isLoading && items.length === 0 && (
            <p className="py-8 text-center text-sm text-muted-foreground">Nothing here{typeFilter !== "all" ? " of this type — try the All filter" : ""}{needle ? " matching the search" : ""}.</p>
          )}
          <div className="max-h-[60vh] space-y-4 overflow-auto">
            {weeks.map((week) => {
              const weekAllSelected = week.items.every((item) => selected[item.material_ref]);
              return (
              <div key={week.label} className="rounded-lg border border-border">
                <label className="flex cursor-pointer items-center gap-2 border-b border-border bg-[#eef3f8] px-4 py-2 text-xs font-semibold uppercase tracking-wider text-[#182d48]">
                  {/* One tick takes the whole week's lectures. */}
                  <input
                    type="checkbox"
                    checked={weekAllSelected}
                    onChange={(e) => setSelected((current) => {
                      const next = { ...current };
                      for (const item of week.items) {
                        if (e.target.checked) next[item.material_ref] = item;
                        else delete next[item.material_ref];
                      }
                      return next;
                    })}
                  />
                  {week.label}
                  <span className="font-normal normal-case text-muted-foreground">({week.items.length})</span>
                </label>
                <ul className="divide-y divide-border">
                  {week.items.map((item) => {
                    const chip = materialStatusChip(item);
                    return (
                      <li key={item.material_ref} className="flex items-center gap-3 px-4 py-2.5">
                        <input type="checkbox" checked={!!selected[item.material_ref]} onChange={(e) => setSelected((current) => {
                          const next = { ...current };
                          if (e.target.checked) next[item.material_ref] = item; else delete next[item.material_ref];
                          return next;
                        })} />
                        <div className="min-w-0 flex-1">
                          <p className="truncate text-sm font-medium text-foreground" title={item.title}>{item.title}</p>
                          <p className="font-mono text-xs text-muted-foreground">
                            {item.date ?? ""}{item.suggested_hours ? ` · ~${item.suggested_hours} h` : ""}
                          </p>
                        </div>
                        <span className={`rounded-full px-2 py-0.5 text-[11px] font-semibold ${categoryChip(item.category)}`}>{item.category}</span>
                        <span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${chip.cls}`}>{chip.label}</span>
                        <span className="flex gap-1">
                          {item.has_iframe && <span className="rounded bg-[#e5f3ef] px-1.5 py-0.5 text-[10px] font-semibold text-[#16856b]">iframe</span>}
                          {item.has_text && <span className="rounded bg-secondary px-1.5 py-0.5 text-[10px] font-semibold text-muted-foreground">text</span>}
                          {/* The LMS quiz is merged into its reading row — the
                              badge carries the learner's own result. */}
                          {item.has_quiz && (
                            <span className={`rounded px-1.5 py-0.5 text-[10px] font-semibold ${
                              item.quiz_passed ? "bg-success/10 text-success"
                              : item.quiz_attempted ? "bg-amber-100 text-amber-700"
                              : "bg-[#fbf0df] text-[#8a5a10]"
                            }`}>
                              quiz{item.quiz_score != null ? ` ${Math.round(item.quiz_score)}%` : ""}{item.quiz_passed ? " ✓" : item.quiz_attempted ? "" : " —"}
                            </span>
                          )}
                        </span>
                      </li>
                    );
                  })}
                </ul>
              </div>
              );
            })}
          </div>
          <p className="mt-2 text-xs text-muted-foreground">
            Tick the lectures (or a whole week), then Add — each becomes one row in Week {weekSlot}; clicking a row's name afterwards opens its iframe page like the automatic system.
          </p>
        </>
      )}
    </Modal>
  );
}

// The learner's Azure files for one assignment, previewable inline (same
// document endpoint the automatic system previews through).
function AssignmentFiles({ data, nameKey }: { data: PlanGroupDetail; nameKey: string }) {
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const evidence = useQuery({
    queryKey: ["plan-asg-evidence", data.id, nameKey],
    queryFn: () => pickAssignmentEvidence(data.id, nameKey),
    enabled: Boolean(nameKey),
  });
  const docs = (evidence.data?.items ?? []).flatMap((learner) => learner.documents);
  return (
    <div className="mt-2 rounded-lg border border-border bg-[#f7f9fc] p-3">
      {evidence.isLoading && <p className="py-2 text-center text-xs text-muted-foreground">Loading the files…</p>}
      {!evidence.isLoading && docs.length === 0 && <p className="py-2 text-center text-xs text-muted-foreground">No submitted document fetched yet.</p>}
      <ul className="space-y-1">
        {docs.map((doc) => (
          <li key={doc.evidence_id} className="flex flex-wrap items-center gap-2 text-xs">
            <FileText className="h-3.5 w-3.5 text-muted-foreground" />
            <span className="min-w-0 flex-1 truncate text-foreground">{doc.name ?? `Evidence ${doc.evidence_id}`}</span>
            <span className="text-muted-foreground">{doc.status ?? ""} {doc.submission_date ? `· ${doc.submission_date}` : ""}</span>
            {doc.open_url ? (
              <button
                type="button"
                onClick={() => setPreviewUrl(previewUrl === doc.open_url ? null : doc.open_url)}
                className={`rounded-md border px-2 py-0.5 font-semibold ${previewUrl === doc.open_url ? "border-[#182d48] bg-[#182d48] text-white" : "border-border text-foreground hover:bg-secondary"}`}
              >
                {previewUrl === doc.open_url ? "Hide preview" : "Preview"}
              </button>
            ) : doc.aptem_url ? (
              <a href={doc.aptem_url} target="_blank" rel="noreferrer" className="rounded-md border border-border px-2 py-0.5 text-muted-foreground hover:bg-secondary">Open externally</a>
            ) : null}
          </li>
        ))}
      </ul>
      {previewUrl && (
        <iframe src={previewUrl} title="Assignment document preview" className="mt-3 h-96 w-full rounded-md border border-border bg-card" />
      )}
    </div>
  );
}

function AssignmentPicker({ data, month, weekSlot, saving, onAdd, onClose }) {
  const [filesFor, setFilesFor] = useState<string | null>(null);
  const assignments = useQuery({ queryKey: ["plan-assignments", data.id], queryFn: () => pickAssignments(data.id) });
  const items = assignments.data?.items ?? [];
  const monthAssignments = data.activities.filter((a) => a.included && a.category === "assignment" && a.month_index === month.month_index);

  async function pick(option: AssignmentOption) {
    if (monthAssignments.length > 0) {
      const confirmation = await Swal.fire({
        icon: "warning",
        title: `This would be assignment ${monthAssignments.length + 1} this month`,
        text: "Usually one assignment per month (last week). Add anyway?",
        showCancelButton: true, confirmButtonText: "Add anyway",
      });
      if (!confirmation.isConfirmed) return;
    }
    await onAdd(
      [{
        category: "assignment",
        title: option.name,
        month_index: month.month_index,
        week_slot: weekSlot,
        material_ref: option.material_ref,
        planned_hours: option.suggested_hours ?? 0,
      }],
      option.learners.map((learner) => ({
        aptem_id: learner.aptem_id,
        component_id: learner.component_id,
        component_name: learner.component_name,
        assignment_month: learner.assignment_month,
      })),
    );
  }

  return (
    <Modal title={`Assignments — ${month.label}`} onClose={onClose} wide>
      {assignments.isLoading && <p className="py-8 text-center text-sm text-muted-foreground">Loading assignments…</p>}
      {!assignments.isLoading && items.length === 0 && <p className="py-8 text-center text-sm text-muted-foreground">No assignments found for this learner.</p>}
      <ul className="divide-y divide-border">
        {items.map((item) => (
          <li key={item.name_key} className="py-2.5">
            <div className="flex items-center gap-3">
              <div className="min-w-0 flex-1">
                <p className="truncate text-sm font-medium text-foreground">{item.name}</p>
                <p className="text-xs text-muted-foreground">
                  {Object.entries(item.month_counts).slice(0, 4).map(([m, c]) => `due ${m}`).join(" · ") || "no due month"}
                </p>
                <p className="text-xs text-muted-foreground">
                  {Object.entries(item.status_counts).map(([status, count]) => `${status}${count > 1 ? `: ${count}` : ""}`).join(" · ")}
                </p>
              </div>
              <Button size="sm" variant="outline" onClick={() => setFilesFor(filesFor === item.name_key ? null : item.name_key)}>
                <FileText className="mr-1 h-3.5 w-3.5" /> {filesFor === item.name_key ? "Hide files" : "Files"}
              </Button>
              <Button size="sm" variant="outline" disabled={saving} onClick={() => void pick(item)}>Add</Button>
            </div>
            {filesFor === item.name_key && <AssignmentFiles data={data} nameKey={item.name_key} />}
          </li>
        ))}
      </ul>
    </Modal>
  );
}

function ManualPicker({ month, weekSlot, saving, onAdd, onClose }) {
  const [category, setCategory] = useState("attendance");
  const [title, setTitle] = useState("");
  const [hours, setHours] = useState(0);
  const [date, setDate] = useState("");
  return (
    <Modal title={`Manual activity — Week ${weekSlot}, ${month.label}`} onClose={onClose}>
      <div className="space-y-3">
        <label className="block">
          <span className="label-caps">Category</span>
          <select className={`${field} mt-1.5`} value={category} onChange={(e) => setCategory(e.target.value)}>
            {["attendance", "video", "reading+quiz", "audio", "assignment"].map((option) => <option key={option} value={option}>{option}</option>)}
          </select>
        </label>
        <label className="block">
          <span className="label-caps">Title</span>
          <input className={`${field} mt-1.5`} value={title} onChange={(e) => setTitle(e.target.value)} placeholder="e.g. Face to face workshop" />
        </label>
        <div className="grid grid-cols-2 gap-3">
          <label className="block">
            <span className="label-caps">Planned hours</span>
            <input type="number" min={0} max={50} step={0.25} className={`${field} mt-1.5`} value={hours} onChange={(e) => setHours(Number(e.target.value) || 0)} />
          </label>
          <label className="block">
            <span className="label-caps">Date (optional)</span>
            <input type="date" className={`${field} mt-1.5`} value={date} onChange={(e) => setDate(e.target.value)} />
          </label>
        </div>
        <Button size="sm" disabled={saving || !title.trim()} onClick={() => void onAdd([{
          category, title: title.trim(), month_index: month.month_index, week_slot: weekSlot,
          planned_hours: hours, planned_date: date || null,
        }])}>Add to plan</Button>
      </div>
    </Modal>
  );
}

// --- Months editor ---------------------------------------------------------------

function MonthsEditor({ data, onClose, onDone }: { data: PlanGroupDetail; onClose: () => void; onDone: () => Promise<void> }) {
  const [rows, setRows] = useState(data.months.length ? data.months.map((m) => ({ ...m })) : [{ month_index: 1, calendar_month: "", label: "", anchor_date: null }]);
  const [saving, setSaving] = useState(false);

  async function save() {
    setSaving(true);
    try {
      await updatePlanMonths(data.id, rows.filter((row) => row.calendar_month));
      toast("Months updated");
      await onDone();
    } catch (cause) {
      fail("Could not save the months", cause);
    } finally {
      setSaving(false);
    }
  }

  return (
    <Modal title="Plan months (a break month? just skip it)" onClose={onClose}>
      <div className="space-y-2">
        {rows.map((row, index) => (
          <div key={index} className="flex items-center gap-2">
            <span className="w-10 font-mono text-xs text-muted-foreground">M{row.month_index}</span>
            <input type="month" className={`${field} max-w-44`} value={row.calendar_month} onChange={(e) => setRows((r) => r.map((item, i) => i === index ? { ...item, calendar_month: e.target.value } : item))} />
            <input type="date" title="Week 1 anchor (optional)" className={`${field} max-w-44`} value={row.anchor_date ?? ""} onChange={(e) => setRows((r) => r.map((item, i) => i === index ? { ...item, anchor_date: e.target.value || null } : item))} />
          </div>
        ))}
        <div className="flex items-center gap-2 pt-2">
          <Button size="sm" variant="outline" onClick={() => setRows((r) => [...r, { month_index: (r[r.length - 1]?.month_index ?? 0) + 1, calendar_month: "", label: "", anchor_date: null }])}>
            <Plus className="mr-1 h-3.5 w-3.5" /> Add month
          </Button>
          <Button size="sm" disabled={saving} onClick={() => void save()}>Save months</Button>
        </div>
      </div>
    </Modal>
  );
}

// --- KSB editor ---------------------------------------------------------------

function KsbEditor({ activity, onClose, onDone }: { activity: PlanActivity; onClose: () => void; onDone: () => Promise<void> }) {
  const [standard, setStandard] = useState("");
  const [selected, setSelected] = useState<PlanKsbs>(activity.ksbs ?? { K: [], S: [], B: [] });
  const [saving, setSaving] = useState(false);
  const catalogue = useQuery({ queryKey: ["plan-ksbs", standard], queryFn: () => pickKsbs(standard || undefined) });

  function toggle(bucket: "K" | "S" | "B", code: string, description?: string | null) {
    setSelected((current) => {
      const list = current[bucket] ?? [];
      const exists = list.some((item) => item.code === code);
      return {
        ...current,
        [bucket]: exists ? list.filter((item) => item.code !== code) : [...list, { code, description }],
      };
    });
  }

  async function save() {
    setSaving(true);
    try {
      await patchPlanActivity(activity.activity_key, { ksbs: selected });
      toast("KSBs saved");
      await onDone();
    } catch (cause) {
      fail("Could not save the KSBs", cause);
    } finally {
      setSaving(false);
    }
  }

  const chosenCount = (selected.K?.length ?? 0) + (selected.S?.length ?? 0) + (selected.B?.length ?? 0);
  return (
    <Modal title={`KSBs — ${activity.title}`} onClose={onClose} wide>
      <div className="mb-3 flex items-center gap-2">
        <select className={`${field} max-w-md`} value={standard} onChange={(e) => setStandard(e.target.value)}>
          <option value="">All standards</option>
          {(catalogue.data?.standards ?? []).map((option) => <option key={option} value={option}>{option}</option>)}
        </select>
        <span className="flex-1" />
        <span className="text-xs text-muted-foreground">{chosenCount} selected</span>
        <Button size="sm" disabled={saving} onClick={() => void save()}><ListChecks className="mr-1 h-3.5 w-3.5" /> Save</Button>
      </div>
      {(["K", "S", "B"] as const).map((bucket) => (
        <div key={bucket} className="mb-4">
          <p className="label-caps mb-2">{bucket === "K" ? "Knowledge" : bucket === "S" ? "Skills" : "Behaviours"}</p>
          <ul className="grid gap-1 sm:grid-cols-2">
            {(catalogue.data?.ksbs[bucket] ?? []).map((item) => {
              const active = (selected[bucket] ?? []).some((chosen) => chosen.code === item.code);
              return (
                <li key={item.code}>
                  <button type="button" onClick={() => toggle(bucket, item.code, item.description)}
                    className={`w-full rounded-md border px-2.5 py-1.5 text-left text-xs transition-colors ${active ? "border-[#182d48] bg-[#eef3f8] text-[#182d48]" : "border-border text-muted-foreground hover:bg-secondary"}`}>
                    <span className="font-semibold">{item.code}</span> — {(item.description ?? "").slice(0, 90)}
                  </button>
                </li>
              );
            })}
          </ul>
        </div>
      ))}
    </Modal>
  );
}

// --- Assignment evidence ---------------------------------------------------------

function AssignmentEvidenceModal({ data, activity, onClose }: {
  data: PlanGroupDetail; activity: { title: string; material_ref: string | null }; onClose: () => void;
}) {
  const nameKey = (activity.material_ref ?? "").startsWith("asg:") ? activity.material_ref!.slice(4) : "";
  const evidence = useQuery({
    queryKey: ["plan-asg-evidence", data.id, nameKey],
    queryFn: () => pickAssignmentEvidence(data.id, nameKey),
    enabled: Boolean(nameKey),
  });
  return (
    <Modal title={`Evidence — ${activity.title}`} onClose={onClose} wide>
      {evidence.isLoading && <p className="py-8 text-center text-sm text-muted-foreground">Loading evidence…</p>}
      <ul className="divide-y divide-border">
        {(evidence.data?.items ?? []).map((learner) => (
          <li key={learner.aptem_id} className="py-3">
            <p className="text-sm font-semibold text-foreground">{learner.name ?? learner.aptem_id}</p>
            {learner.documents.length === 0 ? (
              <p className="mt-1 text-xs text-muted-foreground">No submitted document fetched yet.</p>
            ) : (
              <ul className="mt-1 space-y-1">
                {learner.documents.map((doc) => (
                  <li key={doc.evidence_id} className="flex flex-wrap items-center gap-2 text-xs">
                    <FileText className="h-3.5 w-3.5 text-muted-foreground" />
                    <span className="min-w-0 flex-1 truncate text-foreground">{doc.name ?? `Evidence ${doc.evidence_id}`}</span>
                    <span className="text-muted-foreground">{doc.status ?? ""} {doc.submission_date ? `· ${doc.submission_date}` : ""}</span>
                    {doc.open_url ? (
                      <a href={doc.open_url} target="_blank" rel="noreferrer" className="rounded-md border border-border px-2 py-0.5 font-semibold text-foreground hover:bg-secondary">Preview</a>
                    ) : doc.aptem_url ? (
                      <a href={doc.aptem_url} target="_blank" rel="noreferrer" className="rounded-md border border-border px-2 py-0.5 text-muted-foreground hover:bg-secondary">Open externally</a>
                    ) : null}
                  </li>
                ))}
              </ul>
            )}
          </li>
        ))}
      </ul>
    </Modal>
  );
}
