"""Idempotent creation of the three "Learner" tables behind Progress Review PPTX
generation.

Mirrors learner_api.evidence_tables.ensure_evidence_tables and
enrolment_api.document_tables.ensure_enrolment_documents_table: the Neon schemas
are owned outside Django, so these are raw SQL (CREATE TABLE IF NOT EXISTS)
against the `enrolment` connection alias, not a Django migration.

  "Learner"."progress_review_runs"
      One row per generation attempt for one learner and one 12-week review
      period. `id` is an application-generated uuid4 hex string (not a Postgres
      uuid column) so the same id works unchanged under the SQLite test backend.

  "Learner"."progress_review_source_snapshots"
      The full JSON review pack (progress_review_pack shape) captured at
      generation time, one row per run. Kept separate from the run row so a
      large pack never has to be read back just to check a run's status.

  "Learner"."progress_review_pptx_files"
      The generated .pptx file's Azure location and metadata, one row per run
      (a run is regenerated by creating a new run, not by overwriting a file in
      place, so a previously downloaded deck never changes under its own link).

Prefer `python manage.py apply_progress_review_tables` at deploy time — this
function stays as the request-path safety net for a database that never had it
run (see enrolment_api.document_tables for why the safety net alone is not
enough on its own for columns added after the first release).
"""
from django.db import connections

CONN = "enrolment"
_READY = False


def ensure_progress_review_tables():
    global _READY
    if _READY:
        return
    with connections[CONN].cursor() as cur:
        cur.execute('create schema if not exists "Learner"')

        cur.execute(
            '''
            create table if not exists "Learner"."progress_review_runs" (
                id                   text primary key,
                learner_kind         varchar(32)  not null,
                learner_id           bigint       not null,
                review_number        integer,
                review_date          date         not null,
                review_period_start  date         not null,
                review_period_end    date         not null,
                action_period_start  date,
                action_period_end    date,
                generation_status    varchar(32)  not null default 'pending',
                errors               jsonb        not null default '[]'::jsonb,
                source_warnings      jsonb        not null default '[]'::jsonb,
                generated_by         varchar(255),
                generated_at         timestamptz,
                created_at           timestamptz  not null default now(),
                updated_at           timestamptz  not null default now()
            )
            '''
        )
        cur.execute(
            'create index if not exists idx_progress_review_runs_learner '
            'on "Learner"."progress_review_runs" (learner_kind, learner_id, review_period_end desc)'
        )
        cur.execute(
            'create index if not exists idx_progress_review_runs_status '
            'on "Learner"."progress_review_runs" (generation_status)'
        )

        cur.execute(
            '''
            create table if not exists "Learner"."progress_review_source_snapshots" (
                id          bigserial primary key,
                run_id      text        not null
                                        references "Learner"."progress_review_runs" (id) on delete cascade,
                pack        jsonb       not null,
                created_at  timestamptz not null default now()
            )
            '''
        )
        cur.execute(
            'create index if not exists idx_progress_review_snapshots_run '
            'on "Learner"."progress_review_source_snapshots" (run_id)'
        )

        cur.execute(
            '''
            create table if not exists "Learner"."progress_review_pptx_files" (
                id                 bigserial primary key,
                run_id             text         not null
                                                references "Learner"."progress_review_runs" (id) on delete cascade,
                container          varchar(128) not null,
                blob_name          varchar(1024) not null unique,
                original_filename  varchar(512) not null,
                content_type       varchar(255) not null
                    default 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                size_bytes         bigint,
                generated_by       varchar(255),
                generated_at       timestamptz  not null default now()
            )
            '''
        )
        cur.execute(
            'create index if not exists idx_progress_review_pptx_run '
            'on "Learner"."progress_review_pptx_files" (run_id)'
        )
    _READY = True
