import { useState, useRef, useCallback, useEffect } from 'react';
import { toPng } from 'html-to-image';
import { jsPDF } from 'jspdf';
import { AI_PRESENTATION, MONTHLY_COACHING_DASHBOARD } from '@/mocks/monthly-coaching';
import { useToast } from '@/hooks/useToast';
import { DonutRing, HBar, ProgressGrid, DonutSplit, BarGroup, PulseDot } from './CinematicCharts';

interface PresentationSlidesModalProps {
  open: boolean;
  onClose: () => void;
  onPreview: () => void;
}

export default function PresentationSlidesModal({ open, onClose, onPreview }: PresentationSlidesModalProps) {
  const [currentSlide, setCurrentSlide] = useState(0);
  const [editingSlide, setEditingSlide] = useState<string | null>(null);
  const [editedData, setEditedData] = useState<Record<string, any>>({});
  const [isExporting, setIsExporting] = useState(false);
  const [isSharing, setIsSharing] = useState(false);
  const [mounted, setMounted] = useState(false);
  const exportContainerRef = useRef<HTMLDivElement>(null);
  const { success: showToast } = useToast();

  const slides = AI_PRESENTATION.slides;
  const totalSlides = slides.length;

  useEffect(() => {
    if (open) {
      const t = setTimeout(() => setMounted(true), 80);
      return () => clearTimeout(t);
    }
    setMounted(false);
  }, [open]);

  const handleClose = () => {
    setMounted(false);
    setTimeout(() => {
      setCurrentSlide(0);
      setEditingSlide(null);
      setEditedData({});
      onClose();
    }, 200);
  };

  const handleEditToggle = (slideId: string) => {
    setEditingSlide(editingSlide === slideId ? null : slideId);
  };

  const handleEditChange = (slideId: string, field: string, value: any) => {
    setEditedData(prev => ({
      ...prev,
      [slideId]: { ...(prev[slideId] || {}), [field]: value },
    }));
  };

  const handleExportPDF = useCallback(async () => {
    setIsExporting(true);
    try {
      const pdf = new jsPDF({ orientation: 'landscape', unit: 'px', format: [960, 600] });
      const slideElements = exportContainerRef.current?.querySelectorAll('[data-export-slide]');
      if (!slideElements || slideElements.length === 0) {
        showToast('Export Failed', 'Could not capture slides for PDF generation.');
        setIsExporting(false);
        return;
      }
      for (let i = 0; i < slideElements.length; i++) {
        const el = slideElements[i] as HTMLElement;
        const dataUrl = await toPng(el, { quality: 0.95, pixelRatio: 2, backgroundColor: '#0a0a12', skipFonts: true });
        if (i > 0) pdf.addPage();
        pdf.addImage(dataUrl, 'PNG', 0, 0, 960, 600);
      }
      pdf.save(`Coaching-Presentation-${AI_PRESENTATION.learner.fullName.replace(/\s+/g, '-')}-${AI_PRESENTATION.meeting.cycle.replace(/\s+/g, '-')}.pdf`);
      showToast('PDF Exported', 'Your coaching presentation has been downloaded as a PDF.');
    } catch {
      showToast('Export Failed', 'Something went wrong while generating the PDF. Please try again.');
    } finally {
      setIsExporting(false);
    }
  }, [showToast]);

  const handleShareWithCoach = useCallback(async () => {
    setIsSharing(true);
    await new Promise(resolve => setTimeout(resolve, 1200));
    setIsSharing(false);
    showToast('Shared with Med Maher', 'Your coaching presentation has been sent to your coach for review before the meeting.');
  }, [showToast]);

  const currentSlideData = slides[currentSlide];

  /* ── SLIDE RENDERERS ── */

  const renderCoverSlide = (slide: typeof slides[0]) => (
    <div className="flex flex-col items-center justify-center min-h-[440px] text-center px-10">
      <div className="mb-6 relative">
        <div className="w-20 h-20 rounded-2xl bg-gradient-to-br from-primary-600 to-primary-800 flex items-center justify-center relative z-10 shadow-[0_0_40px_-8px_var(--glow-purple)]">
          <i className="ri-presentation-line text-3xl text-foreground-950" />
        </div>
        <div className="absolute inset-0 w-20 h-20 rounded-2xl bg-primary-500/20 blur-xl animate-pulse" style={{ animationDuration: '3s' }} />
      </div>
      <h1 className="text-3xl font-heading font-bold text-foreground-950 mb-3 tracking-tight">{slide.content.heading}</h1>
      <p className="text-sm text-foreground-600 mb-10">{slide.content.subheading}</p>
      <div className="grid grid-cols-2 gap-x-10 gap-y-3">
        {slide.content.details.map((d: any, i: number) => (
          <div key={i} className="flex items-center gap-3 text-left">
            <span className="text-xs font-medium text-foreground-500 w-24 whitespace-nowrap">{d.label}</span>
            <span className="text-sm font-semibold text-foreground-900">{d.value}</span>
          </div>
        ))}
      </div>
      <div className="mt-12 pt-8 border-t border-foreground-200/50">
        <p className="text-xs text-foreground-400">
          Auto-generated by {AI_PRESENTATION.generatedBy} · {AI_PRESENTATION.generatedAt}
        </p>
      </div>
    </div>
  );

  const renderProgressOverview = (slide: typeof slides[0]) => (
    <div className="space-y-6">
      <div>
        <h3 className="text-xl font-heading font-semibold text-foreground-950 mb-1">{slide.content.heading}</h3>
        <p className="text-sm text-foreground-500">{slide.content.subheading}</p>
      </div>

      {/* Main KSB + OTJH ring charts row */}
      <div className="flex items-center justify-center gap-10 py-2">
        <DonutRing value={42} max={100} size={120} strokeWidth={10} label="KSB Coverage" sublabel="18 of 72 validated" />
        <DonutRing value={35} max={100} size={120} strokeWidth={10} color="var(--accent-500)" trackColor="var(--foreground-800)" label="OTJH" sublabel="10.5 of 30 hrs" />
        <DonutRing value={80} max={100} size={120} strokeWidth={10} color="0.62 0.18 160" trackColor="var(--foreground-800)" label="Quiz Avg" sublabel="8 of 10 passed" />
      </div>

      {/* Metric Grid */}
      <ProgressGrid items={slide.content.metrics} />

      {/* KSB Progress Bar */}
      <div className="space-y-3">
        <p className="text-xs font-medium text-foreground-500 uppercase tracking-wider">KSB Breakdown by Type</p>
        <HBar label="Knowledge (K)" value={55} max={100} color="primary" detail="11 of 20" />
        <HBar label="Skills (S)" value={35} max={100} color="amber" detail="5 of 38" />
        <HBar label="Behaviours (B)" value={25} max={100} color="accent" detail="2 of 14" />
      </div>
    </div>
  );

  const renderLearningCompleted = (slide: typeof slides[0]) => (
    <div className="space-y-6">
      <div>
        <h3 className="text-xl font-heading font-semibold text-foreground-950 mb-1">{slide.content.heading}</h3>
        <p className="text-sm text-foreground-500">{slide.content.subheading}</p>
      </div>

      {/* Evidence Split Ring */}
      <div className="flex justify-center">
        <DonutSplit
          segments={[
            { value: 5, color: 'green', label: 'Completed' },
            { value: 1, color: 'amber', label: 'In Progress' },
            { value: 2, color: 'slate', label: 'Pending' },
          ]}
          size={130}
          strokeWidth={14}
          centerValue="5/8"
          centerLabel="Done"
        />
      </div>

      {/* Weekly Components */}
      <div className="grid grid-cols-2 gap-2">
        {slide.content.weeklyComponents.slice(0, 8).map((c: any, i: number) => {
          const statusStyles: Record<string, string> = {
            'Completed': 'border-emerald-500/30 bg-emerald-500/5',
            'In Progress': 'border-amber-500/30 bg-amber-500/5',
            'Evidence Submitted': 'border-primary-500/30 bg-primary-500/5',
            'Not Started': 'border-foreground-200/50 bg-foreground-100/30',
            'Evidence Required': 'border-red-500/30 bg-red-500/5',
          };
          const dotStyles: Record<string, string> = {
            'Completed': 'bg-emerald-400',
            'In Progress': 'bg-amber-400',
            'Evidence Submitted': 'bg-primary-400',
            'Not Started': 'bg-background-1000',
            'Evidence Required': 'bg-red-400',
          };
          return (
            <div key={i} className={`flex items-center gap-2.5 rounded-lg border px-3 py-2.5 ${statusStyles[c.status] || 'border-foreground-200/50 bg-foreground-100/30'}`}>
              <div className={`w-1.5 h-1.5 rounded-full flex-shrink-0 ${dotStyles[c.status] || 'bg-background-1000'}`} />
              <div className="min-w-0 flex-1">
                <div className="text-xs font-medium text-foreground-900 truncate">{c.title}</div>
                <div className="text-xs text-foreground-400">{c.type}</div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Modules & Assignments */}
      <div className="grid grid-cols-2 gap-5">
        <div>
          <p className="text-xs font-medium text-foreground-500 uppercase tracking-wider mb-2">Modules</p>
          {slide.content.modulesCovered.map((m: string, i: number) => (
            <div key={i} className="flex items-center gap-2 text-xs text-foreground-700 py-1">
              <div className="w-1 h-1 rounded-full bg-primary-400 flex-shrink-0" />
              {m}
            </div>
          ))}
        </div>
        <div>
          <p className="text-xs font-medium text-foreground-500 uppercase tracking-wider mb-2">Assignments</p>
          {slide.content.assignmentsCompleted.map((a: string, i: number) => (
            <div key={i} className="flex items-center gap-2 text-xs text-foreground-700 py-1">
              <div className="w-1 h-1 rounded-full bg-accent-400 flex-shrink-0" />
              {a}
            </div>
          ))}
        </div>
      </div>
    </div>
  );

  const renderEvidenceSummary = (slide: typeof slides[0]) => (
    <div className="space-y-6">
      <div>
        <h3 className="text-xl font-heading font-semibold text-foreground-950 mb-1">{slide.content.heading}</h3>
        <p className="text-sm text-foreground-500">{slide.content.subheading}</p>
      </div>

      {/* Evidence Donut */}
      <div className="flex justify-center">
        <DonutSplit
          segments={[
            { value: 9, color: 'green', label: 'Approved' },
            { value: 2, color: 'amber', label: 'Pending' },
            { value: 1, color: 'slate', label: 'Draft' },
          ]}
          size={130}
          strokeWidth={14}
          centerValue="12"
          centerLabel="Total"
        />
      </div>

      {/* Evidence Stats */}
      <div className="grid grid-cols-4 gap-3">
        <div className="rounded-xl bg-emerald-500/5 border border-emerald-500/15 p-4 text-center">
          <div className="text-xl font-bold text-emerald-400">{slide.content.summary.totalSubmitted}</div>
          <div className="text-xs text-emerald-400/50">Submitted</div>
        </div>
        <div className="rounded-xl bg-emerald-500/5 border border-emerald-500/15 p-4 text-center">
          <div className="text-xl font-bold text-emerald-400">{slide.content.summary.totalApproved}</div>
          <div className="text-xs text-emerald-400/50">Approved</div>
        </div>
        <div className="rounded-xl bg-amber-500/5 border border-amber-500/15 p-4 text-center">
          <div className="text-xl font-bold text-amber-400">{slide.content.summary.pendingReview}</div>
          <div className="text-xs text-amber-400/50">Pending</div>
        </div>
        <div className="rounded-xl bg-foreground-100/30 border border-foreground-200/50 p-4 text-center">
          <div className="text-xl font-bold text-foreground-600">{slide.content.summary.inDraft}</div>
          <div className="text-xs text-foreground-400">Draft</div>
        </div>
      </div>

      {/* KSB Mapping Bars */}
      <div className="space-y-2.5">
        <p className="text-xs font-medium text-foreground-500 uppercase tracking-wider">KSB Coverage</p>
        {slide.content.ksbMapping.map((ksb: any) => {
          const pct = ksb.status === 'Good Coverage' ? 85 : ksb.status === 'Needs More' ? 45 : 15;
          const color = ksb.status === 'Good Coverage' ? 'green' : ksb.status === 'Needs More' ? 'amber' : 'red';
          return (
            <HBar key={ksb.code} label={`${ksb.code} — ${ksb.label}`} value={pct} max={100} color={color} detail={ksb.status} showPct={false} />
          );
        })}
      </div>
    </div>
  );

  const renderWorkplaceApplication = (slide: typeof slides[0]) => {
    const isEditing = editingSlide === slide.id;
    const edits = editedData[slide.id] || {};
    return (
      <div className="space-y-5">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="text-xl font-heading font-semibold text-foreground-950 mb-1">{slide.content.heading}</h3>
            <p className="text-sm text-foreground-500">{slide.content.subheading}</p>
          </div>
          {slide.editable && (
            <button onClick={() => handleEditToggle(slide.id)} className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium cursor-pointer whitespace-nowrap transition-all duration-300 ${isEditing ? 'bg-primary-500/20 text-primary-300 border border-primary-500/30' : 'bg-foreground-100/50 text-foreground-600 border border-foreground-200/50 hover:bg-foreground-100/80 hover:text-foreground-800'}`}>
              <i className={`text-xs ${isEditing ? 'ri-check-line' : 'ri-edit-line'}`} />
              {isEditing ? 'Done Editing' : 'Edit'}
            </button>
          )}
        </div>
        <div className="space-y-3">
          {slide.content.examples.map((ex: any, i: number) => (
            <div key={ex.id} className="rounded-xl border border-foreground-200/50 bg-foreground-100/30 p-4 backdrop-blur-sm transition-all duration-300 hover:bg-foreground-100/50">
              <div className="flex items-start justify-between mb-2">
                {isEditing ? (
                  <input type="text" value={edits[`example-${i}-title`] ?? ex.title} onChange={(e) => handleEditChange(slide.id, `example-${i}-title`, e.target.value)} className="text-sm font-semibold text-foreground-950 bg-foreground-100/50 border border-foreground-200/50 rounded-lg px-2 py-1 w-full" />
                ) : (
                  <h4 className="text-sm font-semibold text-foreground-900">{ex.title}</h4>
                )}
                <div className="flex gap-1 flex-shrink-0 ml-2">
                  {ex.ksbCodes.map((code: string) => (
                    <span key={code} className="text-xs font-medium bg-primary-500/15 text-primary-300 px-1.5 py-0.5 rounded">{code}</span>
                  ))}
                </div>
              </div>
              {isEditing ? (
                <textarea value={edits[`example-${i}-description`] ?? ex.description} onChange={(e) => handleEditChange(slide.id, `example-${i}-description`, e.target.value)} className="text-xs text-foreground-700 bg-foreground-100/50 border border-foreground-200/50 rounded-lg px-2 py-1.5 w-full mb-2 resize-none" rows={3} />
              ) : (
                <p className="text-xs text-foreground-950/45 mb-2">{ex.description}</p>
              )}
              <div className="text-xs rounded-lg px-3 py-2 bg-accent-500/5 border border-accent-500/10">
                <span className="font-semibold text-foreground-800">Employer Impact: </span>
                {isEditing ? (
                  <input type="text" value={edits[`example-${i}-impact`] ?? ex.employerImpact} onChange={(e) => handleEditChange(slide.id, `example-${i}-impact`, e.target.value)} className="text-foreground-700 bg-foreground-100/50 border border-foreground-200/50 rounded-lg px-2 py-1 w-full mt-1" />
                ) : (
                  <span className="text-foreground-950/45">{ex.employerImpact}</span>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  };

  const renderProgressSince = (slide: typeof slides[0]) => (
    <div className="space-y-6">
      <div>
        <h3 className="text-xl font-heading font-semibold text-foreground-950 mb-1">{slide.content.heading}</h3>
        <p className="text-sm text-foreground-500">{slide.content.subheading}</p>
      </div>
      <div className="grid grid-cols-2 gap-5">
        <div>
          <p className="text-xs font-medium text-foreground-500 uppercase tracking-wider mb-3 flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-emerald-400" /> Achievements
          </p>
          {slide.content.achievements.map((a: string, i: number) => (
            <div key={i} className="flex items-start gap-2.5 py-1.5">
              <i className="ri-check-line text-emerald-400 text-sm mt-px" />
              <span className="text-xs text-foreground-950/55">{a}</span>
            </div>
          ))}
        </div>
        <div>
          <p className="text-xs font-medium text-foreground-500 uppercase tracking-wider mb-3 flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-primary-400" /> Improvements
          </p>
          {slide.content.improvements.map((imp: string, i: number) => (
            <div key={i} className="flex items-start gap-2.5 py-1.5">
              <i className="ri-arrow-up-line text-primary-400 text-sm mt-px" />
              <span className="text-xs text-foreground-950/55">{imp}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Actions status bars */}
      <div className="space-y-2.5">
        <p className="text-xs font-medium text-foreground-500 uppercase tracking-wider">Action Completion</p>
        <HBar label="Completed" value={2} max={6} color="green" detail="2 of 6" />
        <HBar label="In Progress" value={2} max={6} color="amber" detail="2 of 6" />
        <HBar label="Overdue" value={1} max={6} color="red" detail="1 of 6" />
        <HBar label="Not Started" value={1} max={6} color="secondary" detail="1 of 6" />
      </div>
    </div>
  );

  const renderChallenges = (slide: typeof slides[0]) => {
    const isEditing = editingSlide === slide.id;
    const edits = editedData[slide.id] || {};
    return (
      <div className="space-y-5">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="text-xl font-heading font-semibold text-foreground-950 mb-1">{slide.content.heading}</h3>
            <p className="text-sm text-foreground-500">{slide.content.subheading}</p>
          </div>
          {slide.editable && (
            <button onClick={() => handleEditToggle(slide.id)} className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium cursor-pointer whitespace-nowrap transition-all duration-300 ${isEditing ? 'bg-primary-500/20 text-primary-300 border border-primary-500/30' : 'bg-foreground-100/50 text-foreground-600 border border-foreground-200/50 hover:bg-foreground-100/80 hover:text-foreground-800'}`}>
              <i className={`text-xs ${isEditing ? 'ri-check-line' : 'ri-edit-line'}`} />
              {isEditing ? 'Done Editing' : 'Edit'}
            </button>
          )}
        </div>
        <div className="space-y-3">
          {slide.content.challenges.map((ch: any, i: number) => (
            <div key={ch.id} className={`rounded-xl border p-4 backdrop-blur-sm ${ch.impact === 'High' ? 'border-red-500/20 bg-red-500/5' : 'border-amber-500/15 bg-amber-500/3'}`}>
              <div className="flex items-center justify-between mb-2">
                {isEditing ? (
                  <input type="text" value={edits[`challenge-${i}-title`] ?? ch.title} onChange={(e) => handleEditChange(slide.id, `challenge-${i}-title`, e.target.value)} className="text-sm font-semibold text-foreground-950 bg-foreground-100/50 border border-foreground-200/50 rounded-lg px-2 py-1 w-full" />
                ) : (
                  <h4 className="text-sm font-semibold text-foreground-900">{ch.title}</h4>
                )}
                <span className={`text-xs font-bold px-2 py-0.5 rounded-full ml-2 flex-shrink-0 ${ch.impact === 'High' ? 'bg-red-500/15 text-red-300' : 'bg-amber-500/15 text-amber-300'}`}>
                  {ch.impact} Impact
                </span>
              </div>
              {isEditing ? (
                <textarea value={edits[`challenge-${i}-description`] ?? ch.description} onChange={(e) => handleEditChange(slide.id, `challenge-${i}-description`, e.target.value)} className="text-xs text-foreground-700 bg-foreground-100/50 border border-foreground-200/50 rounded-lg px-2 py-1.5 w-full mb-2 resize-none" rows={3} />
              ) : (
                <p className="text-xs text-foreground-950/45 mb-2">{ch.description}</p>
              )}
              <div className="text-xs rounded-lg px-3 py-2 bg-primary-500/5 border border-primary-500/10">
                <span className="font-semibold text-foreground-800">Support Needed: </span>
                {isEditing ? (
                  <input type="text" value={edits[`challenge-${i}-support`] ?? ch.supportNeeded} onChange={(e) => handleEditChange(slide.id, `challenge-${i}-support`, e.target.value)} className="text-foreground-700 bg-foreground-100/50 border border-foreground-200/50 rounded-lg px-2 py-1 w-full mt-1" />
                ) : (
                  <span className="text-foreground-950/45">{ch.supportNeeded}</span>
                )}
              </div>
            </div>
          ))}
        </div>

        {/* Barriers */}
        <div className="rounded-xl border border-foreground-200/50 bg-background-100 p-4">
          <p className="text-xs font-medium text-foreground-500 uppercase tracking-wider mb-2">Barriers</p>
          {slide.content.barriers.map((b: string, i: number) => (
            <div key={i} className="flex items-center gap-2 text-xs text-foreground-600 py-1">
              <i className="ri-error-warning-line text-amber-400/60" /> {b}
            </div>
          ))}
        </div>

        {/* Notes */}
        <div className="rounded-xl border border-primary-500/15 bg-primary-500/3 p-4">
          <p className="text-xs font-medium text-primary-300/60 uppercase tracking-wider mb-2">Learner Notes</p>
          {isEditing ? (
            <textarea value={edits.learnerNotes ?? slide.content.learnerNotes} onChange={(e) => handleEditChange(slide.id, 'learnerNotes', e.target.value)} className="text-sm text-foreground-900 bg-foreground-100/50 border border-foreground-200/50 rounded-lg px-3 py-2 w-full resize-none leading-relaxed" rows={4} />
          ) : (
            <p className="text-sm text-foreground-950/55 leading-relaxed">{slide.content.learnerNotes}</p>
          )}
        </div>
      </div>
    );
  };

  const renderGoals = (slide: typeof slides[0]) => {
    const isEditing = editingSlide === slide.id;
    const edits = editedData[slide.id] || {};
    const priorityColors: Record<string, string> = {
      Critical: 'bg-red-500/10 text-red-300 border-red-500/20',
      High: 'bg-amber-500/10 text-amber-300 border-amber-500/20',
      Normal: 'bg-foreground-100/50 text-foreground-600 border-foreground-200/50',
    };
    return (
      <div className="space-y-5">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="text-xl font-heading font-semibold text-foreground-950 mb-1">{slide.content.heading}</h3>
            <p className="text-sm text-foreground-500">{slide.content.subheading}</p>
          </div>
          {slide.editable && (
            <button onClick={() => handleEditToggle(slide.id)} className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium cursor-pointer whitespace-nowrap transition-all duration-300 ${isEditing ? 'bg-primary-500/20 text-primary-300 border border-primary-500/30' : 'bg-foreground-100/50 text-foreground-600 border border-foreground-200/50 hover:bg-foreground-100/80 hover:text-foreground-800'}`}>
              <i className={`text-xs ${isEditing ? 'ri-check-line' : 'ri-edit-line'}`} />
              {isEditing ? 'Done Editing' : 'Edit'}
            </button>
          )}
        </div>
        <div className="space-y-3">
          {slide.content.actions.map((act: any, i: number) => (
            <div key={act.id} className="rounded-xl border border-foreground-200/50 bg-foreground-100/30 p-4 backdrop-blur-sm">
              <div className="flex items-start justify-between mb-2">
                {isEditing ? (
                  <input type="text" value={edits[`action-${i}-title`] ?? act.title} onChange={(e) => handleEditChange(slide.id, `action-${i}-title`, e.target.value)} className="text-sm font-semibold text-foreground-950 bg-foreground-100/50 border border-foreground-200/50 rounded-lg px-2 py-1 w-full" />
                ) : (
                  <h4 className="text-sm font-semibold text-foreground-900">{act.title}</h4>
                )}
                <span className={`text-xs font-medium px-2 py-0.5 rounded-full ml-2 flex-shrink-0 border ${priorityColors[act.priority]}`}>{act.priority}</span>
              </div>
              {isEditing ? (
                <textarea value={edits[`action-${i}-description`] ?? act.description} onChange={(e) => handleEditChange(slide.id, `action-${i}-description`, e.target.value)} className="text-xs text-foreground-700 bg-foreground-100/50 border border-foreground-200/50 rounded-lg px-2 py-1.5 w-full mb-2 resize-none" rows={2} />
              ) : (
                <p className="text-xs text-foreground-950/45 mb-2">{act.description}</p>
              )}
              <div className="text-xs text-foreground-500">
                <span className="font-medium text-foreground-600">Target: </span>
                {isEditing ? (
                  <input type="text" value={edits[`action-${i}-target`] ?? act.target} onChange={(e) => handleEditChange(slide.id, `action-${i}-target`, e.target.value)} className="text-foreground-700 bg-foreground-100/50 border border-foreground-200/50 rounded-lg px-2 py-1 mt-1" />
                ) : (
                  act.target
                )}
              </div>
            </div>
          ))}
        </div>
        <div className="rounded-xl border border-foreground-200/50 bg-background-100 p-4">
          <p className="text-xs font-medium text-foreground-500 uppercase tracking-wider mb-3">Development Areas</p>
          <div className="flex flex-wrap gap-2">
            {slide.content.developmentAreas.map((area: string, i: number) => (
              <span key={i} className="text-xs font-medium bg-primary-500/10 text-primary-300 px-3 py-1.5 rounded-full border border-primary-500/15">{area}</span>
            ))}
          </div>
        </div>
        <div className="text-center pt-2">
          <p className="text-sm text-foreground-500">
            <i className="ri-calendar-check-line mr-1" />
            Next Coaching: {slide.content.nextCoachingDate}
          </p>
        </div>
      </div>
    );
  };

  const renderSlideContent = (slide: typeof slides[0]) => {
    if (slide.type === 'cover') return renderCoverSlide(slide);
    switch (slide.id) {
      case 'slide-2': return renderProgressOverview(slide);
      case 'slide-3': return renderLearningCompleted(slide);
      case 'slide-4': return renderWorkplaceApplication(slide);
      case 'slide-5': return renderEvidenceSummary(slide);
      case 'slide-6': return renderProgressSince(slide);
      case 'slide-7': return renderChallenges(slide);
      case 'slide-8': return renderGoals(slide);
      default: return renderProgressOverview(slide);
    }
  };

  if (!open) return null;

  return (
    <>
      {/* Hidden export container */}
      <div ref={exportContainerRef} className="fixed left-[-9999px] top-0 z-[-1]" style={{ width: '960px' }} aria-hidden="true">
        {slides.map((slide, idx) => (
          <div key={slide.id} data-export-slide className="p-10" style={{ width: '960px', minHeight: '600px', pageBreakAfter: 'always', backgroundColor: '#0a0a12' }}>
            <div className="flex items-center gap-3 mb-5">
              <span className="w-7 h-7 rounded-lg bg-primary-500/20 flex items-center justify-center text-xs font-bold text-primary-300">{idx + 1}</span>
              <span className="text-xs font-semibold text-foreground-500 uppercase tracking-wider">{slide.title}</span>
            </div>
            <div className="text-sm text-foreground-900">
              {slide.type === 'cover' ? (
                <div className="flex flex-col items-center justify-center" style={{ minHeight: '400px' }}>
                  <h1 className="text-2xl font-bold text-foreground-950 mb-2">{slide.content.heading}</h1>
                  <p className="text-sm text-foreground-600 mb-5">{slide.content.subheading}</p>
                  <div className="grid grid-cols-2 gap-x-6 gap-y-2">
                    {(slide.content.details as any[]).map((d: any, i: number) => (
                      <div key={i} className="flex items-center gap-2 text-xs">
                        <span className="text-foreground-500">{d.label}</span>
                        <span className="font-semibold text-foreground-900">{d.value}</span>
                      </div>
                    ))}
                  </div>
                </div>
              ) : (
                <div>
                  <h3 className="text-base font-semibold text-foreground-950 mb-3">{slide.content.heading}</h3>
                  {slide.id === 'slide-2' && slide.content.metrics && (
                    <div className="grid grid-cols-3 gap-2">
                      {(slide.content.metrics as any[]).map((m: any, i: number) => (
                        <div key={i} className="rounded-lg bg-foreground-100/50 p-3">
                          <div className="text-xs text-foreground-500">{m.label}</div>
                          <div className="text-base font-bold text-foreground-950 mt-1">{m.value} <span className="text-xs font-normal text-foreground-400">/ {m.target}</span></div>
                        </div>
                      ))}
                    </div>
                  )}
                  {slide.id === 'slide-4' && (
                    <div className="space-y-2">
                      {(slide.content.examples as any[]).map((ex: any, i: number) => (
                        <div key={i} className="text-xs text-foreground-700">&#8226; <span className="font-medium text-foreground-900">{ex.title}</span> — {ex.employerImpact}</div>
                      ))}
                    </div>
                  )}
                  {slide.id === 'slide-5' && (
                    <div className="flex gap-4 mb-3">
                      <div className="text-center"><span className="text-lg font-bold text-foreground-950">{slide.content.summary.totalSubmitted}</span><div className="text-xs text-foreground-500">Submitted</div></div>
                      <div className="text-center"><span className="text-lg font-bold text-emerald-400">{slide.content.summary.totalApproved}</span><div className="text-xs text-foreground-500">Approved</div></div>
                      <div className="text-center"><span className="text-lg font-bold text-amber-400">{slide.content.summary.pendingReview}</span><div className="text-xs text-foreground-500">Pending</div></div>
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>
        ))}
      </div>

      {/* Main cinematic modal */}
      <div className="fixed inset-0 z-50 flex items-stretch justify-center bg-foreground-900/20">
        <div
          className="relative w-full max-w-[1060px] h-full flex flex-col bg-background-50 transition-all duration-500 ease-out"
          style={{
            opacity: mounted ? 1 : 0,
            transform: mounted ? 'translateY(0) scale(1)' : 'translateY(20px) scale(0.98)',
          }}
        >
          {/* Ambient glow */}
          <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[200px] bg-primary-500/3 blur-[120px] pointer-events-none" />

          {/* Header */}
          <div className="relative z-10 flex items-center justify-between px-8 py-5 border-b border-foreground-200/50">
            <div className="flex items-center gap-5">
              <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-primary-600 to-primary-800 flex items-center justify-center shadow-[0_0_16px_-4px_var(--glow-purple)]">
                <i className="ri-presentation-line text-sm text-foreground-950" />
              </div>
              <div>
                <h2 className="text-sm font-heading font-semibold text-foreground-950">AI-Generated Coaching Presentation</h2>
                <p className="text-xs text-foreground-400">{AI_PRESENTATION.learner.fullName} · {AI_PRESENTATION.meeting.cycle} · Generated {AI_PRESENTATION.generatedAt}</p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <button onClick={onPreview} className="inline-flex items-center gap-1.5 px-4 py-2 bg-foreground-100/80 text-foreground-900 rounded-lg text-xs font-semibold hover:bg-background-100 transition-all duration-300 cursor-pointer whitespace-nowrap border border-foreground-200/50">
                <i className="ri-play-circle-line" /> Preview
              </button>
              <button onClick={handleClose} className="w-8 h-8 rounded-lg flex items-center justify-center text-foreground-500 hover:text-foreground-900 hover:bg-foreground-100/50 transition-all duration-300 cursor-pointer">
                <i className="ri-close-line" />
              </button>
            </div>
          </div>

          {/* Slide navigation */}
          <div className="relative z-10 flex items-center gap-1.5 px-6 py-3 border-b border-foreground-200/50 overflow-x-auto">
            {slides.map((s, idx) => (
              <button
                key={s.id}
                onClick={() => setCurrentSlide(idx)}
                className={`group flex items-center gap-2 px-3 py-2 rounded-lg text-xs font-medium cursor-pointer whitespace-nowrap transition-all duration-300 ${
                  idx === currentSlide
                    ? 'bg-primary-500/15 text-primary-300 border border-primary-500/20'
                    : 'text-foreground-500 hover:text-foreground-700 hover:bg-foreground-100/30 border border-transparent'
                }`}
              >
                <span className={`w-5 h-5 rounded-md flex items-center justify-center text-xs font-bold transition-all duration-300 ${
                  idx === currentSlide ? 'bg-primary-500 text-foreground-950 shadow-[0_0_10px_-3px_var(--glow-purple)]' : 'bg-foreground-100/80 text-foreground-500'
                }`}>{idx + 1}</span>
                <span className="hidden lg:inline">{s.title}</span>
                {s.editable && <i className="ri-edit-line text-[10px]" />}
              </button>
            ))}
          </div>

          {/* Content area */}
          <div className="relative z-10 flex-1 overflow-y-auto px-8 py-8">
            <div className="rounded-2xl border border-foreground-200/50 bg-background-100 backdrop-blur-sm p-8 min-h-[480px]">
              {/* Breadcrumb */}
              <div className="flex items-center gap-2 mb-6">
                <span className="w-7 h-7 rounded-lg bg-primary-500/15 flex items-center justify-center text-xs font-bold text-primary-300">
                  {currentSlide + 1}
                </span>
                <span className="text-xs font-semibold text-foreground-400 uppercase tracking-wider">{currentSlideData.title}</span>
                {currentSlideData.editable && (
                  <span className="text-xs text-primary-300/70 bg-primary-500/10 px-1.5 py-0.5 rounded border border-primary-500/15">
                    <i className="ri-edit-line mr-0.5 text-[10px]" />Editable
                  </span>
                )}
              </div>

              {/* Slide content */}
              <div key={currentSlide} className="animate-in fade-in slide-in-from-bottom-2 duration-400">
                {renderSlideContent(currentSlideData)}
              </div>
            </div>

            {/* Slide nav arrows */}
            <div className="flex items-center justify-between mt-5">
              <button onClick={() => setCurrentSlide(Math.max(0, currentSlide - 1))} disabled={currentSlide === 0} className="inline-flex items-center gap-1.5 px-4 py-2 rounded-lg text-xs font-medium border border-foreground-200/50 text-foreground-600 hover:text-foreground-900 hover:bg-foreground-100/50 disabled:opacity-20 disabled:cursor-not-allowed cursor-pointer transition-all duration-300 whitespace-nowrap">
                <i className="ri-arrow-left-line" /> Previous
              </button>
              <span className="text-xs text-foreground-950/20 font-mono">{currentSlide + 1} / {totalSlides}</span>
              <button onClick={() => setCurrentSlide(Math.min(totalSlides - 1, currentSlide + 1))} disabled={currentSlide === totalSlides - 1} className="inline-flex items-center gap-1.5 px-4 py-2 rounded-lg text-xs font-medium border border-foreground-200/50 text-foreground-600 hover:text-foreground-900 hover:bg-foreground-100/50 disabled:opacity-20 disabled:cursor-not-allowed cursor-pointer transition-all duration-300 whitespace-nowrap">
                Next <i className="ri-arrow-right-line" />
              </button>
            </div>
          </div>

          {/* Footer */}
          <div className="relative z-10 border-t border-foreground-200/50 px-8 py-4 flex items-center justify-between bg-background-100 backdrop-blur-sm">
            <p className="text-xs text-foreground-950/20">
              <i className="ri-magic-line mr-1" /> Auto-generated from platform data
            </p>
            <div className="flex items-center gap-2">
              <button onClick={handleShareWithCoach} disabled={isSharing} className={`inline-flex items-center gap-1.5 px-4 py-2 rounded-lg text-xs font-semibold border cursor-pointer transition-all duration-300 whitespace-nowrap ${
                isSharing ? 'bg-primary-500/10 border-primary-500/20 text-primary-300/60 cursor-wait' : 'bg-primary-500/10 border-primary-500/20 text-primary-300 hover:bg-primary-500/20 hover:border-primary-500/30'
              }`}>
                {isSharing ? <><i className="ri-loader-4-line animate-spin" /> Sharing...</> : <><i className="ri-send-plane-line" /> Share with Coach</>}
              </button>
              <button onClick={handleExportPDF} disabled={isExporting} className={`inline-flex items-center gap-1.5 px-4 py-2 rounded-lg text-xs font-medium border cursor-pointer transition-all duration-300 whitespace-nowrap ${
                isExporting ? 'text-foreground-950/15 border-foreground-200/50 cursor-wait' : 'text-foreground-500 border-foreground-200/50 hover:text-foreground-700 hover:bg-foreground-100/50'
              }`}>
                {isExporting ? <><i className="ri-loader-4-line animate-spin" /> Exporting...</> : <><i className="ri-download-line" /> Export PDF</>}
              </button>
              <button onClick={onPreview} className="inline-flex items-center gap-1.5 px-4 py-2 bg-white text-[#0a0a14] rounded-lg text-xs font-semibold hover:bg-white/90 cursor-pointer transition-all duration-300 whitespace-nowrap">
                <i className="ri-slideshow-line" /> Present
              </button>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}