# Generated by Django 6.0.7 on 2026-08-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz_api', '0002_rename_quiz_course_links_module_catalogue_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"curriculum"."quiz_answers"',
                'ordering': ['sort_order', 'id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuizPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('programme_id', models.CharField(blank=True, default='', max_length=128)),
                ('module', models.CharField(blank=True, max_length=160)),
                ('programme', models.CharField(blank=True, max_length=160)),
                ('version', models.CharField(default='v1.0', max_length=32)),
                ('questions', models.PositiveIntegerField(default=0)),
                ('default_question_type', models.CharField(default='single_choice', max_length=40)),
                ('assessment_type', models.CharField(default='quiz', max_length=40)),
                ('week_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('package_type', models.CharField(default='xml', max_length=20)),
                ('uploaded_file', models.FileField(blank=True, max_length=500, null=True, upload_to='quiz_packages/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('schema_valid', models.BooleanField(default=True)),
                ('validation_message', models.TextField(blank=True)),
                ('mapped_components', models.PositiveIntegerField(default=0)),
                ('author', models.CharField(blank=True, default='Curriculum Team', max_length=120)),
                ('linked_courses', models.PositiveIntegerField(default=0)),
                ('short_description', models.TextField(blank=True)),
                ('lesson_content', models.TextField(blank=True)),
                ('duration', models.PositiveIntegerField(default=60)),
                ('time_unit', models.CharField(default='minutes', max_length=20)),
                ('quiz_style', models.CharField(default='default', max_length=40)),
                ('randomize_questions', models.BooleanField(default=True)),
                ('randomize_answers', models.BooleanField(default=False)),
                ('show_correct_answer', models.BooleanField(default=True)),
                ('attempt_history', models.BooleanField(default=False)),
                ('retake_after_pass', models.BooleanField(default=False)),
                ('limit_attempts', models.BooleanField(default=False)),
                ('passing_grade', models.PositiveIntegerField(default=65)),
                ('retake_points_cut', models.PositiveIntegerField(default=5)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"curriculum"."quizzes"',
                'ordering': ['-updated_at', 'title'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(default='multiple_choice', max_length=40)),
                ('points', models.PositiveIntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('explanation', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"curriculum"."quiz_questions"',
                'ordering': ['sort_order', 'id'],
                'managed': False,
            },
        ),
    ]
