"""Private, re-encoded signature images using the project's Azure helpers."""
from io import BytesIO
from pathlib import Path
import re
import uuid
import warnings

from django.conf import settings
from django.core.files.base import ContentFile
from django.core.files.storage import FileSystemStorage
from PIL import Image, UnidentifiedImageError

from learner_api import evidence_storage
from .service import ServiceError

MAX_BYTES = 2 * 1024 * 1024
MAX_PIXELS = 4_000_000


def sanitize(upload):
    if not upload or upload.size > MAX_BYTES or upload.size == 0:
        raise ServiceError('Choose a PNG or JPEG signature image up to 2 MB.')
    data = upload.read(MAX_BYTES + 1)
    if len(data) > MAX_BYTES:
        raise ServiceError('The signature image must be no larger than 2 MB.')
    try:
        with warnings.catch_warnings():
            warnings.simplefilter('error', Image.DecompressionBombWarning)
            with Image.open(BytesIO(data)) as img:
                if img.format not in {'PNG', 'JPEG'} or img.width * img.height > MAX_PIXELS:
                    raise ValueError('unsupported image')
                img.verify()
            with Image.open(BytesIO(data)) as img:
                img.load()
                # Composite transparent drawings on white and discard metadata
                # and embedded payloads. Only these generated bytes are stored.
                rgba = img.convert('RGBA')
                clean = Image.new('RGB', img.size, 'white')
                clean.paste(rgba, mask=rgba.getchannel('A'))
                if all(low == high for low, high in clean.getextrema()):
                    raise ValueError('empty image')
                out = BytesIO()
                clean.save(out, format='PNG')
                if out.tell() > MAX_BYTES:
                    raise ValueError('encoded image too large')
                return out.getvalue()
    except (ValueError, OSError, UnidentifiedImageError, Image.DecompressionBombError, Image.DecompressionBombWarning):
        raise ServiceError('Upload a valid, non-empty PNG or JPEG signature image up to 2 MB.')


def _key(file_id):
    if not re.fullmatch(r'[a-f0-9]{32}', file_id):
        raise ServiceError('Signature not found.', 'not_found', 404)
    return f'old-otjh/{file_id}.png'


def _local():
    return FileSystemStorage(location=Path(settings.BASE_DIR) / 'private_media')


def save(data):
    file_id = uuid.uuid4().hex
    key = _key(file_id)
    try:
        if evidence_storage.azure_configured():
            evidence_storage.upload_blob(BytesIO(data), settings.AZURE_ENROLMENT_DOCS_CONTAINER,
                                         key, 'image/png', overwrite=False)
        else:
            _local().save(key, ContentFile(data))
    except Exception:
        delete(file_id)
        raise ServiceError('Could not save the signature image. Please try again.', 'storage_unavailable', 503)
    return file_id


def read(file_id):
    key = _key(file_id)
    if evidence_storage.azure_configured():
        return evidence_storage._service_client().get_blob_client(
            container=settings.AZURE_ENROLMENT_DOCS_CONTAINER, blob=key
        ).download_blob(connection_timeout=10, read_timeout=30).chunks()
    return _local().open(key, 'rb')


def delete(file_id):
    try:
        key = _key(file_id)
        if evidence_storage.azure_configured():
            evidence_storage.delete_blob(settings.AZURE_ENROLMENT_DOCS_CONTAINER, key)
        else:
            _local().delete(key)
    except Exception:
        # Do not log paths, signatures or credentials when cleanup fails.
        pass
