from django.urls import path

from . import views


urlpatterns = [
    path('curriculum/overview/', views.curriculum_overview, name='curriculum-overview'),
    path('curriculum/stats/', views.curriculum_stats, name='curriculum-stats'),
    path('curriculum/preview/cohort-end-date/', views.curriculum_preview_cohort_end_date, name='curriculum-preview-cohort-end-date'),
    path('curriculum/preview/module-session-plan/', views.curriculum_preview_module_session_plan, name='curriculum-preview-module-session-plan'),
    path('curriculum/programmes/', views.curriculum_programme_collection, name='curriculum-programmes'),
    path('curriculum/programmes/<str:identifier>/detail/', views.curriculum_programme_tree_detail, name='curriculum-programme-tree-detail'),
    path('curriculum/programmes/<str:programme_id>/cohorts/', views.curriculum_programme_cohort_collection, name='curriculum-programme-cohorts'),
    path('curriculum/programmes/<str:identifier>/', views.curriculum_programme_detail, name='curriculum-programme-detail'),
    path('curriculum/standards/', views.curriculum_standards, name='curriculum-standards'),
    path('curriculum/standards/<str:identifier>/', views.curriculum_standard_detail, name='curriculum-standard-detail'),
    path('curriculum/modules/', views.curriculum_module_collection, name='curriculum-modules'),
    path('curriculum/modules/<str:module_catalogue_id>/structure/', views.curriculum_module_structure, name='curriculum-module-structure'),
    path('curriculum/modules/<str:module_catalogue_id>/settings/', views.curriculum_module_settings, name='curriculum-module-settings'),
    path('curriculum/modules/<str:module_catalogue_id>/components/<str:component_id>/', views.curriculum_module_component_detail, name='curriculum-module-component-detail'),
    path('curriculum/modules/<str:module_catalogue_id>/weeks/<str:week_id>/', views.curriculum_module_week_detail, name='curriculum-module-week-detail'),
    path('curriculum/modules/<str:identifier>/', views.curriculum_module_detail, name='curriculum-module-detail'),
    path('curriculum/module-catalogue/', views.curriculum_module_collection, name='curriculum-module-catalogue'),
    path('curriculum/module-catalogue/<str:identifier>/', views.curriculum_module_detail, name='curriculum-module-catalogue-detail'),
    path('curriculum/components/', views.curriculum_component_collection, name='curriculum-components'),
    path('curriculum/components/<str:component_id>/', views.curriculum_component_detail, name='curriculum-component-detail'),
    path('curriculum/ksb-frameworks/', views.curriculum_ksb_framework_collection, name='curriculum-ksb-frameworks'),
    path('curriculum/ksb-frameworks/<str:identifier>/', views.curriculum_ksb_framework_detail, name='curriculum-ksb-framework-detail'),
    path('curriculum/ksb-profiles/', views.curriculum_ksb_framework_collection, name='curriculum-ksb-profiles'),
    path('curriculum/ksb-profiles/<str:identifier>/', views.curriculum_ksb_framework_detail, name='curriculum-ksb-profile-detail'),
    path('curriculum/ksb-sets/', views.curriculum_ksb_sets, name='curriculum-ksb-sets'),
    path('curriculum/cohorts/', views.curriculum_cohort_collection, name='curriculum-cohorts'),
    path('curriculum/cohorts/<str:cohort_id>/groups/', views.curriculum_cohort_group_collection, name='curriculum-cohort-groups'),
    path('curriculum/cohorts/<str:identifier>/', views.curriculum_cohort_detail, name='curriculum-cohort-detail'),
    path('curriculum/groups/', views.curriculum_group_collection, name='curriculum-groups'),
    path('curriculum/groups/<str:identifier>/', views.curriculum_group_detail, name='curriculum-group-detail'),
    path('curriculum/groups/<str:identifier>/modules/', views.curriculum_group_modules, name='curriculum-group-modules'),
    path('curriculum/group-modules/<str:identifier>/', views.curriculum_module_detail, name='curriculum-group-module-detail'),
    path('curriculum/sessions/', views.curriculum_session_collection, name='curriculum-sessions'),
    path('curriculum/sessions/<str:identifier>/', views.curriculum_session_detail, name='curriculum-session-detail'),
    path('curriculum/staffing/', views.curriculum_staffing_collection, name='curriculum-staffing'),
    path('curriculum/staffing/<str:identifier>/', views.curriculum_staffing_detail, name='curriculum-staffing-detail'),
    path('curriculum/holidays/', views.curriculum_holiday_collection, name='curriculum-holidays'),
    path('curriculum/holidays/<str:identifier>/', views.curriculum_holiday_detail, name='curriculum-holiday-detail'),
    path('curriculum/tutors/', views.curriculum_tutors, name='curriculum-tutors'),
    path('curriculum/coaches/', views.curriculum_coaches, name='curriculum-coaches'),
]
