# Generated by Django 6.0.7 on 2026-08-06 10:32

import learner_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedIlr',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('learner_kind', models.TextField(db_column='Learner_kind')),
                ('learner_id', models.BigIntegerField(db_column='Learner_id')),
                ('learner_name', models.TextField(blank=True, db_column='Learner_name', null=True)),
                ('answers', learner_api.models.SafeJSONField(blank=True, db_column='Answers', null=True)),
                ('wizard_draft', learner_api.models.SafeJSONField(blank=True, db_column='Wizard_draft', null=True)),
                ('learner_signed', models.BooleanField(db_column='Learner_signed', default=False)),
                ('learner_signed_date', models.TextField(blank=True, db_column='Learner_signed_date', null=True)),
                ('provider_signed', models.BooleanField(db_column='Provider_signed', default=False)),
                ('provider_signed_date', models.TextField(blank=True, db_column='Provider_signed_date', null=True)),
                ('completed', models.BooleanField(db_column='Completed', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Updated_at')),
            ],
            options={
                'db_table': 'enrolment"."Extended_ILR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WizardCvJob',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('learner_kind', models.TextField(db_column='Learner_kind')),
                ('learner_id', models.BigIntegerField(db_column='Learner_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Updated_at')),
                ('cv_file', models.TextField(blank=True, db_column='Cv_file', null=True)),
                ('experience_text', models.TextField(blank=True, db_column='Experience_text', null=True)),
                ('pm_qualifications', models.TextField(blank=True, db_column='PM_qualifications', null=True)),
                ('functional_skills_enrol', models.TextField(blank=True, db_column='Functional_skills_enrol', null=True)),
            ],
            options={
                'db_table': 'enrolment"."Wizard_Cv_Job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WizardKsbAssessment',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('learner_kind', models.TextField(db_column='Learner_kind')),
                ('learner_id', models.BigIntegerField(db_column='Learner_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Updated_at')),
                ('ksb_id', models.TextField(db_column='Ksb_id')),
                ('level', models.TextField(blank=True, db_column='Level', null=True)),
                ('score', models.IntegerField(blank=True, db_column='Score', null=True)),
                ('note', models.TextField(blank=True, db_column='Note', null=True)),
                ('action_text', models.TextField(blank=True, db_column='Action_text', null=True)),
                ('action', models.TextField(blank=True, db_column='Action', null=True)),
                ('goal', models.TextField(blank=True, db_column='Goal', null=True)),
                ('due_date', models.DateField(blank=True, db_column='Due_date', null=True)),
                ('evidence_files', learner_api.models.SafeJSONField(blank=True, db_column='Evidence_files', null=True)),
            ],
            options={
                'db_table': 'enrolment"."Wizard_Ksb_Assessments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WizardPersonalDetails',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('learner_kind', models.TextField(db_column='Learner_kind')),
                ('learner_id', models.BigIntegerField(db_column='Learner_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Updated_at')),
                ('first_name', models.TextField(blank=True, db_column='First_name', null=True)),
                ('last_name', models.TextField(blank=True, db_column='Last_name', null=True)),
                ('email', models.TextField(blank=True, db_column='Email', null=True)),
                ('phone', models.TextField(blank=True, db_column='Phone', null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('date_of_birth', models.DateField(blank=True, db_column='Date_of_birth', null=True)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('sex', models.TextField(blank=True, db_column='Sex', null=True)),
                ('signature', models.TextField(blank=True, db_column='Signature', null=True)),
                ('signature_date', models.DateField(blank=True, db_column='Signature_date', null=True)),
            ],
            options={
                'db_table': 'enrolment"."Wizard_Personal_Details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WizardPlr',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('learner_kind', models.TextField(db_column='Learner_kind')),
                ('learner_id', models.BigIntegerField(db_column='Learner_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Updated_at')),
                ('uln', models.TextField(blank=True, db_column='ULN', null=True)),
            ],
            options={
                'db_table': 'enrolment"."Wizard_Plr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WizardPlrRecord',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('learner_kind', models.TextField(db_column='Learner_kind')),
                ('learner_id', models.BigIntegerField(db_column='Learner_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Updated_at')),
                ('record_ref', models.TextField(db_column='Record_ref')),
                ('place_of_study', models.TextField(blank=True, db_column='Place_of_study', null=True)),
                ('qualification_type', models.TextField(blank=True, db_column='Qualification_type', null=True)),
                ('subject', models.TextField(blank=True, db_column='Subject', null=True)),
                ('level', models.TextField(blank=True, db_column='Level', null=True)),
                ('award_date', models.DateField(blank=True, db_column='Award_date', null=True)),
                ('credits', models.IntegerField(blank=True, db_column='Credits', null=True)),
                ('grade', models.TextField(blank=True, db_column='Grade', null=True)),
                ('record_type', models.TextField(blank=True, db_column='Record_type', null=True)),
            ],
            options={
                'db_table': 'enrolment"."Wizard_Plr_Records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WizardPolicyAck',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('learner_kind', models.TextField(db_column='Learner_kind')),
                ('learner_id', models.BigIntegerField(db_column='Learner_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Updated_at')),
                ('policy_id', models.TextField(db_column='Policy_id')),
                ('acknowledged', models.BooleanField(db_column='Acknowledged', default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, db_column='Acknowledged_at', null=True)),
            ],
            options={
                'db_table': 'enrolment"."Wizard_Policy_Acks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WizardSkillsRadar',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('learner_kind', models.TextField(db_column='Learner_kind')),
                ('learner_id', models.BigIntegerField(db_column='Learner_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Updated_at')),
                ('standard_id', models.TextField(blank=True, db_column='Standard_id', null=True)),
            ],
            options={
                'db_table': 'enrolment"."Wizard_Skills_Radar',
                'managed': False,
            },
        ),
    ]
