# Generated by Django 6.0.7 on 2026-09-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WizardIlrLearnerDetails',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('learner_kind', models.TextField(db_column='Learner_kind')),
                ('learner_id', models.BigIntegerField(db_column='Learner_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Updated_at')),
                ('years_at_address', models.IntegerField(blank=True, db_column='Years_at_address', null=True)),
                ('at_address_since_birth', models.BooleanField(blank=True, db_column='At_address_since_birth', null=True)),
                ('postcode_prior_to_enrolment', models.TextField(blank=True, db_column='Postcode_prior_to_enrolment', null=True)),
                ('national_insurance_number', models.TextField(blank=True, db_column='National_insurance_number', null=True)),
                ('ni_number_applied', models.BooleanField(blank=True, db_column='Ni_number_applied', null=True)),
                ('legal_sex', models.TextField(blank=True, db_column='Legal_sex', null=True)),
                ('pronouns', models.TextField(blank=True, db_column='Pronouns', null=True)),
                ('ethnicity', models.TextField(blank=True, db_column='Ethnicity', null=True)),
                ('long_term_disability', models.BooleanField(blank=True, db_column='Long_term_disability', null=True)),
                ('highest_qualification', models.TextField(blank=True, db_column='Highest_qualification', null=True)),
                ('employment_status', models.TextField(blank=True, db_column='Employment_status', null=True)),
                ('employment_start_date', models.DateField(blank=True, db_column='Employment_start_date', null=True)),
                ('job_title', models.TextField(blank=True, db_column='Job_title', null=True)),
                ('self_employed', models.BooleanField(blank=True, db_column='Self_employed', null=True)),
                ('full_time_education', models.BooleanField(blank=True, db_column='Full_time_education', null=True)),
                ('expected_leaving_date', models.DateField(blank=True, db_column='Expected_leaving_date', null=True)),
                ('length_of_unemployment', models.TextField(blank=True, db_column='Length_of_unemployment', null=True)),
                ('volunteers', models.BooleanField(blank=True, db_column='Volunteers', null=True)),
                ('state_benefits', models.TextField(blank=True, db_column='State_benefits', null=True)),
                ('benefit_claim_basis', models.TextField(blank=True, db_column='Benefit_claim_basis', null=True)),
                ('declaration_signature', models.TextField(blank=True, db_column='Declaration_signature', null=True)),
                ('declaration_signed_date', models.DateField(blank=True, db_column='Declaration_signed_date', null=True)),
            ],
            options={
                'db_table': 'enrolment"."Wizard_Ilr_Learner_Details',
                'managed': False,
            },
        ),
    ]
