# Generated by Django 6.0.1 on 2026-07-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoachCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=255, unique=True)),
                ('owner_email', models.EmailField(db_index=True, max_length=255)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('learner_id', models.IntegerField(db_index=True)),
                ('learner_name', models.CharField(blank=True, max_length=255)),
                ('learner_email', models.EmailField(blank=True, max_length=255)),
                ('event_type', models.CharField(db_index=True, max_length=32)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('target_date', models.DateField(db_index=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('not-scheduled', 'Not Scheduled'), ('scheduled', 'Scheduled'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='not-scheduled', max_length=32)),
                ('meeting_provider', models.CharField(blank=True, max_length=64)),
                ('meeting_link', models.URLField(blank=True, max_length=1000)),
                ('graph_event_id', models.CharField(blank=True, max_length=255)),
                ('graph_web_link', models.URLField(blank=True, max_length=1000)),
                ('notes', models.TextField(blank=True)),
                ('last_graph_sync_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['target_date', 'learner_name', 'event_type', 'sequence'],
            },
        ),
    ]
