# Generated by Django 6.0.7 on 2026-08-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_api', '0004_normalize_absence_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachcalendarevent',
            name='manager_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachcalendarevent',
            name='manager_signed_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='coachcalendarevent',
            name='review_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachcalendarevent',
            name='review_responses',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='coachcalendarevent',
            name='status',
            field=models.CharField(choices=[('not-scheduled', 'Not Scheduled'), ('scheduled', 'Scheduled'), ('in-progress', 'In Progress'), ('awaiting-signature', 'Awaiting Signature'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='not-scheduled', max_length=32),
        ),
        migrations.CreateModel(
            name='CoachAbsenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_id', models.BigIntegerField(unique=True)),
                ('owner_email', models.EmailField(db_index=True, max_length=255)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('learner_id', models.IntegerField(db_index=True)),
                ('learner_name', models.CharField(max_length=255)),
                ('learner_email', models.EmailField(blank=True, max_length=255)),
                ('session_title', models.CharField(max_length=255)),
                ('session_date', models.DateField(db_index=True)),
                ('session_time', models.TimeField(blank=True, null=True)),
                ('reason_category', models.CharField(blank=True, max_length=64)),
                ('reason', models.TextField()),
                ('reported_by', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], db_index=True, default='pending', max_length=20)),
                ('evidence_provided', models.BooleanField(default=False)),
                ('evidence_kind', models.CharField(default='none', max_length=20)),
                ('evidence_text', models.TextField(blank=True)),
                ('evidence_image_url', models.URLField(blank=True, max_length=1000)),
                ('previous_absences', models.PositiveIntegerField(default=0)),
                ('attendance_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('coach_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Coach"."coach_absence_report',
                'ordering': ['-session_date', 'learner_name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('attendance_rate__isnull', True), models.Q(('attendance_rate__gte', 0), ('attendance_rate__lte', 100)), _connector='OR'), name='coach_absence_attendance_0_100')],
            },
        ),
    ]
