# Generated by Django 6.0.7 on 2026-08-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_api', '0005_coachcalendarevent_manager_signed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachcalendarevent',
            name='graph_organizer_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
