# Generated by Django 6.0.7 on 2026-08-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_api', '0008_calendar_idempotency_state'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coachabsencereport',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'declined'])), name='coach_absence_report_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='coachcalendarevent',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['not-scheduled', 'scheduled', 'in-progress', 'awaiting-signature', 'completed', 'cancelled'])), name='coach_calendar_event_status_valid'),
        ),
    ]
