# Generated by Django 6.0.7 on 2026-09-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_api', '0009_coachabsencereport_coach_absence_report_status_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachabsencereport',
            name='catchup_event_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coachabsencereport',
            name='recovery_method',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='coachcalendarevent',
            name='occurrence_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachcalendarevent',
            name='review_instance_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='coachcalendarevent',
            name='review_template_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
