# Generated by Django 6.0.7 on 2026-09-14 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach_api', '0010_absence_report_meeting_attendance_ids'),
        ('coach_api', '0010_coachabsencereport_catchup_event_key_and_more'),
    ]

    operations = [
    ]
