# Generated by Django 6.0.7 on 2026-09-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_api', '0011_merge_20260914_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachCalendarColorPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_email', models.EmailField(db_index=True, max_length=255)),
                ('scope', models.CharField(choices=[('category', 'Category'), ('event', 'Event')], max_length=16)),
                ('scope_key', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Coach"."coach_calendar_color_preference',
            },
        ),
        migrations.AddIndex(
            model_name='coachcalendarcolorpreference',
            index=models.Index(fields=['owner_email', 'scope'], name='coach_color_owner_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='coachcalendarcolorpreference',
            constraint=models.UniqueConstraint(fields=('owner_email', 'scope', 'scope_key'), name='coach_color_pref_owner_scope_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='coachcalendarcolorpreference',
            constraint=models.CheckConstraint(condition=models.Q(('scope__in', ['category', 'event'])), name='coach_color_pref_scope_valid'),
        ),
        migrations.AddConstraint(
            model_name='coachcalendarcolorpreference',
            constraint=models.CheckConstraint(condition=models.Q(('color__regex', '^#[0-9A-Fa-f]{6}$')), name='coach_color_pref_color_format_valid'),
        ),
    ]
