# Generated by Django 6.0.7 on 2026-08-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ambassador', models.CharField(max_length=255)),
                ('ambassador_role', models.CharField(max_length=255)),
                ('members', models.IntegerField(default=0)),
                ('sample_members', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Engagement"."clubs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClubMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('scheduled', models.BooleanField(default=False)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.CharField(blank=True, max_length=100, null=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('attendees', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Engagement"."club_meetings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('workshop', 'Workshop'), ('social', 'Social'), ('networking', 'Networking'), ('competition', 'Competition'), ('celebration', 'Celebration')], max_length=20)),
                ('attendees', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('organizer', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Engagement"."events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_id', models.CharField(max_length=100)),
                ('learner_name', models.CharField(max_length=255)),
                ('learner_email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled')], default='booked', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Engagement"."event_bookings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Engagement"."flash_cards',
                'ordering': ['sort_order', 'id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FlashCardDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('programme_id', models.IntegerField(blank=True, null=True)),
                ('programme', models.CharField(blank=True, default='', max_length=255)),
                ('module', models.CharField(blank=True, default='', max_length=255)),
                ('week_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('card_count', models.IntegerField(default=0)),
                ('ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Engagement"."flash_card_decks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FlashCardView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_id', models.CharField(max_length=100)),
                ('learner_name', models.CharField(max_length=255)),
                ('points_awarded', models.IntegerField(default=0)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Engagement"."flash_card_views',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PointsGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_id', models.CharField(max_length=100)),
                ('learner_name', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('event_reference', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Engagement"."points_grants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PointsRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('points', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('trigger', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Engagement"."points_rules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_id', models.CharField(max_length=100)),
                ('learner_name', models.CharField(max_length=255)),
                ('avatar_img', models.TextField(blank=True, null=True)),
                ('programme_code', models.CharField(max_length=50)),
                ('programme', models.CharField(max_length=255)),
                ('cohort', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('badge', 'Badge'), ('certificate', 'Certificate'), ('spotlight', 'Spotlight'), ('milestone', 'Milestone'), ('achievement', 'Achievement')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('awarded_by', models.CharField(max_length=255)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Engagement"."recognitions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('points', models.IntegerField()),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('delivery_type', models.CharField(choices=[('physical', 'Physical'), ('digital', 'Digital')], max_length=20)),
                ('stock', models.IntegerField(default=0)),
                ('total_claimed', models.IntegerField(default=0)),
                ('image', models.TextField(blank=True, default='')),
                ('popular', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Engagement"."rewards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VoucherClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_id', models.CharField(max_length=100)),
                ('learner_name', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_type', models.CharField(choices=[('physical', 'Physical'), ('digital', 'Digital')], max_length=20)),
                ('delivery_method', models.CharField(blank=True, default='', max_length=20)),
                ('delivery_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_instructions', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Engagement"."voucher_claims',
                'managed': False,
            },
        ),
    ]
