# Generated by Django 6.0.7 on 2026-09-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_id', models.CharField(max_length=100)),
                ('learner_name', models.CharField(max_length=255)),
                ('action', models.TextField()),
                ('employer_notified', models.BooleanField(default=False)),
                ('intervention_date', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Engagement"."attendance_interventions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClubMeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_id', models.CharField(max_length=100)),
                ('learner_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=20)),
                ('marked_by', models.CharField(blank=True, max_length=255, null=True)),
                ('marked_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Engagement"."club_meeting_attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_id', models.CharField(max_length=100)),
                ('learner_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('removed', 'Removed')], default='active', max_length=20)),
                ('assigned_by', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Engagement"."club_memberships',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_id', models.CharField(max_length=100)),
                ('learner_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=20)),
                ('marked_by', models.CharField(blank=True, max_length=255, null=True)),
                ('marked_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Engagement"."event_attendance',
                'managed': False,
            },
        ),
    ]
