# Generated by Django 6.0.7 on 2026-09-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner_api', '0009_merge_learner_api_0008s'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerFreeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('free_course_ref', models.TextField(blank=True, null=True)),
                ('free_course_title', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Learner"."learner_free_courses',
                'ordering': ('position', 'id'),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LearnerFreeCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_id', models.BigIntegerField()),
                ('component_ref', models.TextField()),
                ('free_course_ref', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'Learner"."learner_free_course_progress',
                'managed': False,
            },
        ),
    ]
