# Generated by Django 6.0.7 on 2026-10-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner_api', '0015_assignment_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='UlnPrivacyReviewDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_key', models.TextField(db_column='Event_key')),
                ('learner_id', models.BigIntegerField(db_column='Learner_id')),
                ('learner_name', models.TextField(blank=True, db_column='Learner_name')),
                ('completed', models.BooleanField(db_column='Completed', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Updated_at')),
                ('privacy_notice_read', models.TextField(blank=True, db_column='Privacy_notice_read')),
                ('learner_acknowledged', models.TextField(blank=True, db_column='Learner_acknowledged')),
            ],
            options={
                'db_table': 'enrolment"."Review_ULN_Privacy',
                'managed': False,
            },
        ),
    ]
