// @ts-nocheck -- route search types are generated by the embedded app.
import { useEffect, useRef, useState } from "react";
import { keepPreviousData, useQuery } from "@tanstack/react-query";
import { createFileRoute, Link, useRouter } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, FileText, Plus, Search, UserRound } from "lucide-react";
import { ActivityTableHeader, InlineActivityCreateRow, InlineActivityRow } from "@/features/audit/learner-log-pro-hours-test/components/InlineActivityRow";
import { Button } from "@/features/audit/learner-log-pro-hours-test/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/features/audit/learner-log-pro-hours-test/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/features/audit/learner-log-pro-hours-test/components/ui/table";
import { getLearnerActivities, getLearners } from "@/features/audit/learner-log-pro-hours-test/lib/api";

export const Route = createFileRoute("/search")({
  // Filters and pagination live in the URL so coming back to this page —
  // browser Back or an in-app Back button — restores the exact table state.
  validateSearch: (search) => ({
    q: typeof search.q === "string" ? search.q : "",
    period: typeof search.period === "string" ? search.period : "",
    gap: typeof search.gap === "string" ? search.gap : "all",
    programme: typeof search.programme === "string" ? search.programme : "",
    lpage: Number.isInteger(search.lpage) && search.lpage > 0 ? search.lpage : 0,
    aq: typeof search.aq === "string" ? search.aq : "",
    alearner: typeof search.alearner === "string" ? search.alearner : "",
    acat: typeof search.acat === "string" ? search.acat : "",
    apage: Number.isInteger(search.apage) && search.apage > 0 ? search.apage : 0,
  }),
  component: SearchPage,
});

const field =
  "h-9 w-full rounded-md border border-border bg-card px-2.5 text-sm text-foreground outline-none focus:border-primary";
const pageSize = 30;
const learnerPageSize = 10;

function Filter({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label className="block">
      <span className="label-caps">{label}</span>
      <span className="mt-1.5 block">{children}</span>
    </label>
  );
}

function learnerStatusClass(status: string) {
  const value = status.trim().toLowerCase();
  if (value === "active" || value === "completed") return "bg-success/10 text-success";
  if (value === "onbreak") return "bg-warning/20 text-foreground ring-1 ring-warning/40";
  if (value === "withdrawn" || value === "nonstarter") return "bg-destructive/10 text-destructive";
  return "bg-muted text-muted-foreground";
}

// Human label + colour for an OTJH month status.
function otjhLabel(status: string) {
  switch ((status || "").toLowerCase()) {
    case "over_target": return "over target";
    case "below_target": return "below target";
    case "happy_conflict": return "conflict";
    case "rebuilt": return "rebuilt";
    case "happy": return "in band";
    case "skipped_empty": return "no activity";
    default: return status || "—";
  }
}
function otjhChipClass(status: string) {
  switch ((status || "").toLowerCase()) {
    case "below_target": return "bg-destructive/10 text-destructive ring-1 ring-destructive/40";
    case "over_target":
    case "happy_conflict": return "bg-warning/20 text-foreground ring-1 ring-warning/40";
    default: return "bg-muted text-muted-foreground";
  }
}

// Data-quality flags from the live cohort feed. "withdrawn" already shows via the
// programme-status chip, so it is not repeated here.
function flagLabel(flag: string) {
  switch (flag) {
    case "no_attendance_recorded": return "No attendance recorded";
    case "lms_not_matched": return "LMS not matched";
    case "hours_not_mapped": return "Hours not mapped";
    case "withdrawn": return "Withdrawn";
    default: return flag.replace(/_/g, " ");
  }
}
function flagChipClass(flag: string) {
  if (flag === "withdrawn") return "bg-destructive/10 text-destructive ring-1 ring-destructive/40";
  return "bg-warning/20 text-foreground ring-1 ring-warning/40";
}

function StyledFilterSelect({
  value,
  options,
  allLabel,
  includeAllOption = true,
  onChange,
}: {
  value: string;
  options: Array<{ value: string; label: string }>;
  allLabel: string;
  includeAllOption?: boolean;
  onChange: (value: string) => void;
}) {
  return (
    <Select
      value={value || (includeAllOption ? "all" : undefined)}
      onValueChange={(nextValue) => onChange(includeAllOption && nextValue === "all" ? "" : nextValue)}
    >
      <SelectTrigger className="bg-card shadow-none">
        <SelectValue placeholder={allLabel} />
      </SelectTrigger>
      <SelectContent position="popper" className="max-h-72">
        {includeAllOption && <SelectItem value="all">{allLabel}</SelectItem>}
        {options.filter((option) => option.value !== "all").map((option) => (
          <SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}

function formatHours(value: number) {
  return `${value.toFixed(2)} h`;
}

// Per-activity hours are shown as whole hours in the log tables; the section
// totals above still use the exact values, so a column can differ from its
// total by the rounding remainder.
function roundHours(value: number | null | undefined) {
  // Round to 2 dp (not whole hours — 2.5h must stay "2.5", not become "3"),
  // dropping any trailing zeros so 11.0 shows as "11".
  return value == null ? "—" : String(Math.round(value * 100) / 100);
}

function SearchPage() {
  const router = useRouter();
  const routeSearch = Route.useSearch();
  const [learnerSearch, setLearnerSearch] = useState(routeSearch.q);
  const [sharedPeriod, setSharedPeriod] = useState(routeSearch.period);
  const [gapBand, setGapBand] = useState(routeSearch.gap);
  const [programmeName, setProgrammeName] = useState(routeSearch.programme);
  const [learnerPage, setLearnerPage] = useState(routeSearch.lpage);

  const [activitySearch, setActivitySearch] = useState(routeSearch.aq);
  const [activityLearner, setActivityLearner] = useState(routeSearch.alearner);
  const [activityCategory, setActivityCategory] = useState(routeSearch.acat);
  const [page, setPage] = useState(routeSearch.apage);
  const [addingActivity, setAddingActivity] = useState(false);

  // Mirror the filters into the URL (replace: no history spam) so that Back
  // from a learner profile / journal lands on the same filtered table.
  useEffect(() => {
    const next = {
      q: learnerSearch,
      period: sharedPeriod,
      gap: gapBand,
      programme: programmeName,
      lpage: learnerPage,
      aq: activitySearch,
      alearner: activityLearner,
      acat: activityCategory,
      apage: page,
    };
    if (Object.entries(next).every(([key, value]) => routeSearch[key] === value)) return;
    void router.navigate({ to: "/search", search: next, replace: true });
  }, [learnerSearch, sharedPeriod, gapBand, programmeName, learnerPage, activitySearch, activityLearner, activityCategory, page, routeSearch, router]);

  const filterOptions = useQuery({
    queryKey: ["search-filter-options"],
    queryFn: () => getLearners(),
  });

  // The cohort table defaults to "All months" (empty period) so it shows each
  // learner's cumulative planned_total vs actual_total — the cohort-overview
  // reading. Picking a month then narrows both the table and the activity log
  // to that month.

  const summaries = useQuery({
    queryKey: ["learner-summaries", sharedPeriod, learnerSearch, gapBand, programmeName],
    queryFn: () =>
      getLearners({
        period: sharedPeriod || undefined,
        search: learnerSearch || undefined,
        position: gapBand === "all" ? undefined : gapBand,
        programme: programmeName || undefined,
      }),
    enabled: Boolean(filterOptions.data),
  });

  const activities = useQuery({
    queryKey: [
      "learner-activities-search",
      activitySearch,
      activityLearner,
      sharedPeriod,
      activityCategory,
      programmeName,
      page,
    ],
    queryFn: () =>
      getLearnerActivities({
        search: activitySearch,
        learner: activityLearner || undefined,
        period: sharedPeriod || undefined,
        category: activityCategory || undefined,
        programme: programmeName || undefined,
        limit: pageSize,
        offset: page * pageSize,
      }),
    placeholderData: keepPreviousData,
    // A learner's full (all-month) activity history is large (~1 MB+), so the
    // activity log only loads once a learner OR a specific month is chosen —
    // never a whole-cohort, all-months fan-out on first paint.
    enabled: Boolean(filterOptions.data) && Boolean(activityLearner || (sharedPeriod && sharedPeriod !== "undated")),
  });
  const activitiesEnabled = Boolean(activityLearner || (sharedPeriod && sharedPeriod !== "undated"));
  const selectedActivityLearner = filterOptions.data?.learners.find(
    (learner) =>
      (learner.id === activityLearner || learner.name.toLowerCase() === activityLearner.toLowerCase()) &&
      (!programmeName || (learner.programmes ?? [learner.programme]).includes(programmeName)),
  );
  const programmeOptions = [...new Set(filterOptions.data?.learners.flatMap((learner) => learner.programmes?.length ? learner.programmes : [learner.programme]).filter(Boolean) ?? [])]
    .sort()
    .map((programme) => ({ value: programme, label: programme }));
  const summaryLearners = summaries.data?.learners ?? [];
  // "Still coming" covers the gap where summaries is disabled behind
  // filterOptions — without it an in-flight cohort looks like an empty one.
  const learnersPending = !summaries.data && !summaries.isError && !filterOptions.isError;
  const learnerTotalPages = Math.max(1, Math.ceil(summaryLearners.length / learnerPageSize));
  const pagedLearners = summaryLearners.slice(
    learnerPage * learnerPageSize,
    (learnerPage + 1) * learnerPageSize,
  );

  // Reset pagination only when a filter actually CHANGES — on mount the
  // filters and page were just seeded from the URL and must survive Back.
  const lastLearnerFilters = useRef({ sharedPeriod, learnerSearch, gapBand, programmeName });
  useEffect(() => {
    const prev = lastLearnerFilters.current;
    if (
      prev.sharedPeriod === sharedPeriod &&
      prev.learnerSearch === learnerSearch &&
      prev.gapBand === gapBand &&
      prev.programmeName === programmeName
    ) return;
    lastLearnerFilters.current = { sharedPeriod, learnerSearch, gapBand, programmeName };
    setLearnerPage(0);
  }, [sharedPeriod, learnerSearch, gapBand, programmeName]);
  useEffect(() => {
    // Don't clamp against the placeholder page count while summaries load —
    // that would wipe a page restored from the URL.
    if (!summaries.data) return;
    if (learnerPage >= learnerTotalPages) setLearnerPage(learnerTotalPages - 1);
  }, [learnerPage, learnerTotalPages, summaries.data]);

  const totalPages = Math.max(1, Math.ceil((activities.data?.total ?? 0) / pageSize));
  const resetPage = () => setPage(0);

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border bg-surface">
        <div className="mx-auto flex max-w-[1700px] flex-wrap items-center justify-between gap-4 px-6 py-4">
          <div className="flex items-baseline gap-3">
            <span className="font-serif text-base text-foreground">OTJ&nbsp;Ledger</span>
            <span className="label-caps">Live learner search</span>
          </div>
          <div className="flex items-center gap-4 text-xs text-muted-foreground">
            <Link to="/activity" search={{ learner: "" }} className="font-medium hover:underline">
              Activity log
            </Link>
            <Link to="/journal" search={{ learner: "", period: "" }} className="font-medium hover:underline">
              Monthly journal
            </Link>
          </div>
        </div>
      </header>

      <main className="mx-auto w-full max-w-[1700px] space-y-6 px-6 py-8">
        <section className="rounded-lg border border-border bg-card shadow-panel">
          <header className="border-b border-border px-7 py-5">
            <h1 className="font-serif text-lg text-foreground">Learner search</h1>
          </header>

          <div className="grid gap-4 border-b border-border px-7 py-5 sm:grid-cols-2 lg:grid-cols-4">
            <Filter label="Learner name">
              <span className="relative block">
                <Search className="pointer-events-none absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                <input
                  className={`${field} pl-8`}
                  placeholder="Search learner…"
                  value={learnerSearch}
                  onChange={(event) => {
                    // Only filters the cohort table above; the activity log has
                    // its own independent "Learner" filter.
                    setLearnerSearch(event.target.value);
                  }}
                />
              </span>
            </Filter>
            <Filter label="Programme name">
              <StyledFilterSelect
                value={programmeName}
                options={programmeOptions}
                allLabel="All programmes"
                onChange={(value) => {
                  setProgrammeName(value);
                  setActivityLearner("");
                  resetPage();
                }}
              />
            </Filter>
            <Filter label="Activity month">
              <StyledFilterSelect
                value={sharedPeriod}
                options={filterOptions.data?.periods ?? []}
                allLabel="All months"
                includeAllOption={true}
                onChange={(value) => { setSharedPeriod(value); resetPage(); }}
              />
            </Filter>
            <Filter label="Hours position">
              <StyledFilterSelect
                value={gapBand}
                allLabel="All learners"
                options={[
                  { value: "behind", label: "Behind plan" },
                  { value: "ahead", label: "On or ahead of plan" },
                ]}
                onChange={(value) => setGapBand(value || "all")}
              />
            </Filter>
          </div>

          {summaries.isError || filterOptions.isError ? (
            <p className="px-7 py-10 text-center text-sm text-destructive">
              {(summaries.error ?? filterOptions.error) instanceof Error
                ? ((summaries.error ?? filterOptions.error) as Error).message
                : "Could not load learner data."}
            </p>
          ) : (
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow className="hover:bg-transparent">
                    <TableHead className="label-caps w-20 pl-7">No.</TableHead>
                    <TableHead className="label-caps">Learner</TableHead>
                    <TableHead className="label-caps">Status</TableHead>
                    <TableHead className="label-caps">Coach</TableHead>
                    <TableHead className="label-caps text-right">Activities</TableHead>
                    <TableHead className="label-caps text-right">Planned hours</TableHead>
                    <TableHead className="label-caps text-right">Actual hours</TableHead>
                    <TableHead className="label-caps text-right">Actual vs plan</TableHead>
                    <TableHead className="label-caps text-right">Learner profile</TableHead>
                    <TableHead className="label-caps pr-7 text-right">Details</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {/* The learner query WAITS for the filter query, so while that
                      first cohort fetch is in flight `summaries` is disabled —
                      isLoading is false and the table used to render as an empty
                      "0 learners" cohort, which reads as broken rather than slow. */}
                  {learnersPending && (
                    <TableRow><TableCell colSpan={10} className="py-10 text-center text-sm text-muted-foreground">Loading learners…</TableCell></TableRow>
                  )}
                  {!learnersPending && !pagedLearners.length && (
                    <TableRow><TableCell colSpan={10} className="py-10 text-center text-sm text-muted-foreground">No learner matches these filters.</TableCell></TableRow>
                  )}
                  {pagedLearners.map((learner, index) => (
                    <TableRow key={learner.id} className={learner.has_break_in_learning ? "bg-warning/5 hover:bg-warning/10" : undefined}>
                      <TableCell className="pl-7 font-mono text-sm font-semibold text-muted-foreground">{learnerPage * learnerPageSize + index + 1}</TableCell>
                      <TableCell>
                        <p className="text-sm font-semibold text-foreground">{learner.name}</p>
                        {learner.email ? <p className="mt-0.5 text-xs text-muted-foreground">{learner.email}</p> : null}
                      </TableCell>
                      <TableCell>
                        <div className="flex flex-wrap items-center gap-1.5">
                          <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${learnerStatusClass(learner.program_status)}`}>{learner.program_status}</span>
                          {learner.has_break_in_learning && <span className="rounded-full bg-warning/20 px-2.5 py-1 text-xs font-semibold text-foreground ring-1 ring-warning/40">Break in learning</span>}
                          {(learner.flags ?? []).filter(
                            (flag) => !["withdrawn", "lms_not_matched", "hours_not_mapped"].includes(flag),
                          ).map((flag) => (
                            <span key={flag} className={`rounded-full px-2.5 py-1 text-xs font-semibold ${flagChipClass(flag)}`}>⚑ {flagLabel(flag)}</span>
                          ))}
                          {learner.otjh?.month_flagged && learner.otjh.month ? (
                            <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${otjhChipClass(learner.otjh.month.status)}`}>⚑ OTJH: {otjhLabel(learner.otjh.month.status)}</span>
                          ) : (learner.otjh?.flagged_count ?? 0) > 0 ? (
                            <span className="rounded-full bg-warning/20 px-2.5 py-1 text-xs font-semibold text-foreground ring-1 ring-warning/40">⚑ {learner.otjh.flagged_count} OTJH flag{learner.otjh.flagged_count === 1 ? "" : "s"}</span>
                          ) : null}
                        </div>
                      </TableCell>
                      <TableCell>
                        <p className="text-sm font-medium text-foreground">{learner.coach.name ?? "—"}</p>
                        {learner.coach.email && <p className="mt-0.5 text-xs text-muted-foreground">{learner.coach.email}</p>}
                      </TableCell>
                      <TableCell className="text-right font-mono text-sm">{learner.entries}</TableCell>
                      {/* Planned = Aptem's own plan; Actual = the claimed total
                          this learner's monthly report adds up, so the two
                          screens can never disagree. */}
                      <TableCell className="text-right font-mono text-sm" title={learner.planned_hours_available === false ? "Aptem holds no plan for this learner yet" : "Planned hours from Aptem"}>
                        {learner.planned_hours_available === false ? "—" : formatHours(learner.planned_hours)}
                      </TableCell>
                      <TableCell className="text-right font-mono text-sm text-success" title="Claimed hours arranged on the monthly report">
                        {formatHours(learner.actual_hours)}
                      </TableCell>
                      <TableCell className={`text-right font-mono text-sm ${learner.gap_hours < 0 ? "text-warning" : "text-success"}`}>
                        {learner.planned_hours_available === false ? "—" : <>{learner.gap_hours > 0 ? "+" : ""}{formatHours(learner.gap_hours)}</>}
                      </TableCell>
                      <TableCell className="text-right">
                        <Link
                          to="/learner/$learnerId"
                          params={{ learnerId: learner.id }}
                          className="inline-flex items-center gap-1.5 rounded-md border border-border bg-card px-2.5 py-1.5 text-xs font-semibold text-foreground transition-colors hover:bg-secondary"
                        >
                          <UserRound className="h-3.5 w-3.5" /> View profile
                        </Link>
                      </TableCell>
                      <TableCell className="pr-7 text-right">
                        <Link
                          to="/journal"
                          search={{ learner: learner.id, period: sharedPeriod || "" }}
                          className="inline-flex items-center gap-1.5 text-xs font-medium text-foreground hover:underline"
                        >
                          <FileText className="h-3.5 w-3.5" /> Monthly report
                        </Link>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
          <footer className="flex items-center justify-between border-t border-border px-7 py-4 text-xs text-muted-foreground">
            <span>
              {learnersPending
                ? "Loading learners…"
                : summaryLearners.length === 0
                  ? "0 learners"
                  : `${learnerPage * learnerPageSize + 1}–${Math.min((learnerPage + 1) * learnerPageSize, summaryLearners.length)} of ${summaryLearners.length} learners`}
            </span>
            <div className="flex items-center gap-3">
              <span>Page {learnerPage + 1} of {learnerTotalPages}</span>
              <div className="flex gap-2">
                <Button variant="outline" size="sm" disabled={learnerPage === 0} onClick={() => setLearnerPage((value) => Math.max(0, value - 1))}>
                  <ArrowLeft className="mr-1 h-3.5 w-3.5" /> Previous
                </Button>
                <Button variant="outline" size="sm" disabled={learnerPage + 1 >= learnerTotalPages} onClick={() => setLearnerPage((value) => Math.min(learnerTotalPages - 1, value + 1))}>
                  Next <ArrowRight className="ml-1 h-3.5 w-3.5" />
                </Button>
              </div>
            </div>
          </footer>
        </section>

        <section className="rounded-lg border border-border bg-card shadow-panel">
          <header className="flex flex-wrap items-end justify-between gap-4 border-b border-border px-7 py-5">
            <div>
              <h2 className="font-serif text-lg text-foreground">Activity log search</h2>
            </div>
            <dl className="flex gap-6">
              <div><dt className="label-caps">Matches</dt><dd className="font-mono text-sm">{activities.data?.total ?? 0}</dd></div>
              <div><dt className="label-caps">Planned total</dt><dd className="font-mono text-sm">{formatHours(activities.data?.planned_total ?? 0)}</dd></div>
              <div><dt className="label-caps">Actual total</dt><dd className="font-mono text-sm text-success">{formatHours(activities.data?.actual_total ?? 0)}</dd></div>
            </dl>
          </header>

          <div className="grid gap-4 border-b border-border px-7 py-5 sm:grid-cols-2 lg:grid-cols-4">
            <Filter label="Search">
              <input className={field} placeholder="Plan or activity…" value={activitySearch} onChange={(event) => { setActivitySearch(event.target.value); resetPage(); }} />
            </Filter>
            <Filter label="Learner">
              <StyledFilterSelect
                value={activityLearner}
                allLabel="All learners"
                options={filterOptions.data?.learners
                  .filter((learner) => !programmeName || (learner.programmes ?? [learner.programme]).includes(programmeName))
                  .map((learner) => ({ value: learner.id, label: learner.name })) ?? []}
                onChange={(value) => {
                  // Only scopes the activity log below; leaves the cohort table untouched.
                  setActivityLearner(value);
                  resetPage();
                }}
              />
            </Filter>
            <Filter label="Activity month">
              <StyledFilterSelect
                value={sharedPeriod}
                options={filterOptions.data?.periods ?? []}
                allLabel="All months"
                includeAllOption={true}
                onChange={(value) => { setSharedPeriod(value); resetPage(); }}
              />
            </Filter>
            <Filter label="Category">
              <StyledFilterSelect
                value={activityCategory}
                allLabel="All categories"
                options={filterOptions.data?.categories.map((category) => ({ value: category, label: category })) ?? []}
                onChange={(value) => { setActivityCategory(value); resetPage(); }}
              />
            </Filter>
          </div>

          <div className="flex justify-end border-t border-border px-7 py-3">
            <Button size="sm" disabled={!selectedActivityLearner || addingActivity} onClick={() => setAddingActivity(true)} title={!selectedActivityLearner ? "Choose one learner before adding an activity" : undefined}>
              <Plus className="mr-1.5 h-3.5 w-3.5" /> Add activity
            </Button>
          </div>

          {activities.isError ? (
            <p className="px-7 py-10 text-center text-sm text-destructive">
              {activities.error instanceof Error ? activities.error.message : "Could not load activities."}
            </p>
          ) : (
            <div className="max-h-[36rem] overflow-auto">
              <Table>
                <TableHeader><ActivityTableHeader /></TableHeader>
                <TableBody>
                  {addingActivity && selectedActivityLearner ? (
                    <InlineActivityCreateRow learnerId={Number(selectedActivityLearner.id)} learnerName={selectedActivityLearner.name} onCancel={() => setAddingActivity(false)} />
                  ) : null}
                  {!activitiesEnabled && (
                    <TableRow><TableCell colSpan={10} className="py-10 text-center text-sm text-muted-foreground">Pick a learner or an activity month above to load the evidence log.</TableCell></TableRow>
                  )}
                  {activitiesEnabled && activities.isLoading && (
                    <TableRow><TableCell colSpan={10} className="py-10 text-center text-sm text-muted-foreground">Loading activity records…</TableCell></TableRow>
                  )}
                  {activities.data?.items.map((row) => (
                    <InlineActivityRow key={row.id} row={row} />
                  ))}
                </TableBody>
              </Table>
            </div>
          )}

          <footer className="flex items-center justify-between border-t border-border px-7 py-4 text-xs text-muted-foreground">
            <span>Page {page + 1} of {totalPages}</span>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" disabled={page === 0} onClick={() => setPage((value) => value - 1)}><ArrowLeft className="mr-1 h-3.5 w-3.5" /> Previous</Button>
              <Button variant="outline" size="sm" disabled={page + 1 >= totalPages} onClick={() => setPage((value) => value + 1)}>Next <ArrowRight className="ml-1 h-3.5 w-3.5" /></Button>
            </div>
          </footer>
        </section>
      </main>
    </div>
  );
}
