# Generated by Django 6.0.7 on 2026-09-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_api', '0061_cohort_excluded_holiday_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglandHoliday',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('division', models.CharField(default='england-and-wales', max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('holiday_date', models.DateField(db_index=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('bunting', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'curriculum"."england_holidays',
                'managed': False,
            },
        ),
    ]
