# Generated by Django 6.0.7 on 2026-09-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_api', '0066_live_session_recording_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSessionAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_id', models.CharField(db_index=True, max_length=128)),
                ('learner_profile_id', models.BigIntegerField(db_index=True)),
                ('source_kind', models.CharField(blank=True, default='', max_length=32)),
                ('source_learner_id', models.IntegerField(blank=True, null=True)),
                ('learner_email', models.EmailField(blank=True, default='', max_length=320)),
                ('learner_name', models.CharField(blank=True, default='', max_length=500)),
                ('recovery_status', models.CharField(choices=[('none', 'No recovery requested'), ('requested', 'Recovery requested'), ('catchup_booked', 'Catch-up booked'), ('completed', 'Catch-up completed')], default='none', max_length=24)),
                ('recovery_method', models.CharField(blank=True, default='', max_length=16)),
                ('recovery_reference', models.CharField(blank=True, default='', max_length=255)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'curriculum"."live_session_absences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LiveSessionAttendanceAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_catalogue_id', models.CharField(db_index=True, max_length=128)),
                ('alias_email', models.EmailField(max_length=320)),
                ('learner_profile_id', models.BigIntegerField(db_index=True)),
                ('canonical_email', models.EmailField(max_length=320)),
                ('created_by', models.CharField(blank=True, default='', max_length=320)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'curriculum"."live_session_attendance_aliases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LiveSessionAttendanceIdentityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_id', models.CharField(db_index=True, max_length=128)),
                ('attendance_row_id', models.CharField(max_length=128)),
                ('learner_profile_id', models.BigIntegerField(db_index=True)),
                ('canonical_email', models.EmailField(max_length=320)),
                ('display_name', models.CharField(blank=True, default='', max_length=500)),
                ('created_by', models.CharField(blank=True, default='', max_length=320)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'curriculum"."live_session_attendance_identity_links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LiveSessionLearnerAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_id', models.CharField(db_index=True, max_length=128)),
                ('live_session_id', models.CharField(db_index=True, max_length=128)),
                ('module_catalogue_id', models.CharField(db_index=True, max_length=128)),
                ('learner_profile_id', models.BigIntegerField(db_index=True)),
                ('learner_email', models.EmailField(blank=True, default='', max_length=320)),
                ('learner_name', models.CharField(blank=True, default='', max_length=500)),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=16)),
                ('recovery_status', models.CharField(choices=[('none', 'Not requested'), ('requested', 'Recovery requested'), ('catchup_booked', 'Catch-up booked'), ('completed', 'Catch-up completed')], default='none', max_length=24)),
                ('attended_seconds', models.PositiveIntegerField(default=0)),
                ('attendance_report_id', models.TextField(blank=True, default='')),
                ('first_join_at', models.DateTimeField(blank=True, null=True)),
                ('last_leave_at', models.DateTimeField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'curriculum"."live_session_learner_attendance',
                'managed': False,
            },
        ),
    ]
