// ============================================================================
// Country list — shared by every address form (create user, create employer,
// create organisation).
//
// The full ISO 3166-1 set of sovereign states and dependent territories, using
// common short-form English names ("United Kingdom", not "United Kingdom of
// Great Britain and Northern Ireland") since these are picked by staff, not
// machines.
//
// UK first: this is a UK-funded provider, so it's the overwhelmingly common
// answer and shouldn't need scrolling to. The rest are alphabetical.
// ============================================================================

/** The default, and the first entry in COUNTRY_OPTIONS. */
export const DEFAULT_COUNTRY = 'United Kingdom';

const ALPHABETICAL = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Congo (Democratic Republic)',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czechia',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'East Timor',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Ivory Coast',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar (Burma)',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'St Kitts and Nevis',
  'St Lucia',
  'St Vincent and the Grenadines',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];

// ISO 3166-1 also includes the smaller island nations and dependent
// territories below. They are kept here so country and nationality fields
// accept the same complete set of places.
const ADDITIONAL_COUNTRIES = [
  'Åland Islands',
  'American Samoa',
  'Anguilla',
  'Antarctica',
  'Aruba',
  'Bermuda',
  'Bonaire, Sint Eustatius and Saba',
  'Bouvet Island',
  'British Indian Ocean Territory',
  'British Virgin Islands',
  'Cayman Islands',
  'Christmas Island',
  'Cocos (Keeling) Islands',
  'Cook Islands',
  'Curaçao',
  'Falkland Islands',
  'Faroe Islands',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'Gibraltar',
  'Greenland',
  'Guadeloupe',
  'Guam',
  'Guernsey',
  'Heard Island and McDonald Islands',
  'Isle of Man',
  'Jersey',
  'Martinique',
  'Mayotte',
  'Montserrat',
  'New Caledonia',
  'Niue',
  'Norfolk Island',
  'Northern Mariana Islands',
  'Pitcairn',
  'Puerto Rico',
  'Réunion',
  'Saint Barthélemy',
  'Saint Helena, Ascension and Tristan da Cunha',
  'Saint Martin (French part)',
  'Saint Pierre and Miquelon',
  'Sint Maarten (Dutch part)',
  'South Georgia and the South Sandwich Islands',
  'Svalbard and Jan Mayen',
  'Tokelau',
  'Turks and Caicos Islands',
  'United States Minor Outlying Islands',
  'United States Virgin Islands',
  'Wallis and Futuna',
  'Western Sahara',
];

/**
 * Every country, UK first then alphabetical.
 *
 * The UK is excluded from ALPHABETICAL above so it can't appear twice — a
 * duplicate would give two <option>s the same key and value.
 */
export const COUNTRY_OPTIONS: string[] = [
  DEFAULT_COUNTRY,
  ...[...ALPHABETICAL, ...ADDITIONAL_COUNTRIES]
    .filter((country) => country !== DEFAULT_COUNTRY)
    .sort((a, b) => a.localeCompare(b, 'en')),
];

/** Nationality is collected using the same complete country set. */
export const NATIONALITY_OPTIONS = COUNTRY_OPTIONS;
